-- 【法务官】通用语音包
local loc_YoRHa2B = "loc_adamant_male_a/YoRHa2B/"
local play_YoRHa2B = "wwise/events/player/play_adamant_male_a/YoRHa2B"
E:set_class("adamant", "YoRHa2B_ja", "法务官"):old_version()
E:add_audio("adamant", "YoRHa2B_ja", "guidance_correct_path_", loc_YoRHa2B, "ja_loc_adamant_male_a__guidance_correct_path_", 3):add_subtext("法务官", {"保持队形，继续前进。", "按既定路线行进。", "执行前进指令。"})
E:add_audio("adamant", "YoRHa2B_ja", "guidance_correct_path_up_", loc_YoRHa2B, "ja_loc_adamant_male_a__guidance_correct_path_up_", 3):add_subtext("法务官", {"目标在上方，移动。", "准备向上攀登。", "全员听令，向上层推进。"})
E:add_audio("adamant", "YoRHa2B_ja", "guidance_correct_path_drop_", loc_YoRHa2B, "ja_loc_adamant_male_a__guidance_correct_path_drop_", 5):add_subtext("法务官", {"准备速降。", "下方突进。", "列队，向下行进。", "集合，准备跳跃！", "全员注意，向下移动。"})
E:add_audio("adamant", "YoRHa2B_ja", "stairs_sighted_", loc_YoRHa2B, "ja_loc_adamant_male_a__stairs_sighted_", 2):add_subtext("法务官", {"发现楼梯，从这里走。", "全员，准备登梯。"})
E:add_audio("adamant", "YoRHa2B_ja", "guidance_starting_area_", loc_YoRHa2B, "ja_loc_adamant_male_a__guidance_starting_area_", 4):add_subtext("法务官", {"任务开始。", "出动。", "法务官就位，通信正常。", "全员安全抵达，开始肃清。"})
E:add_audio("adamant", "YoRHa2B_ja", "region_carnival_a_", loc_YoRHa2B, "ja_loc_adamant_male_a__region_carnival_a_", 2):add_subtext("法务官", {"检查装备，不要遗漏。", "自检完毕，各项机能正常。"})
E:add_audio("adamant", "YoRHa2B_ja", "info_event_det_pack_a_", loc_YoRHa2B, "ja_loc_adamant_male_a__info_event_det_pack_a_", 4):add_subtext("法务官", {"炸药安放完毕。", "爆破装置已就绪。", "准备强行突破。", "开始攻坚作业！"})
E:add_audio("adamant", "YoRHa2B_ja", "event_survive_keep_coming_a_", loc_YoRHa2B, "ja_loc_adamant_male_a__event_survive_keep_coming_a_", 2):add_subtext("法务官", {"全员，坚守阵地！", "防线不可退缩，死守！"})
E:add_audio("adamant", "YoRHa2B_ja", "event_demolition_first_corruptor_destroyed_a_", loc_YoRHa2B, "ja_loc_adamant_male_a__event_demolition_first_corruptor_destroyed_a_", 4):add_subtext("法务官", {"目标已清除！", "确认目标消灭！", "已摧毁目标！", "肃清完毕。"})
E:add_audio("adamant", "YoRHa2B_ja", "event_survive_almost_done_", loc_YoRHa2B, "ja_loc_adamant_male_a__event_survive_almost_done_", 2):add_subtext("法务官", {"防线稳固，继续保持！", "即将完成镇压！"})
E:add_audio("adamant", "YoRHa2B_ja", "info_event_one_down_", loc_YoRHa2B, "ja_loc_adamant_male_a__info_event_one_down_", 4):add_subtext("法务官", {"消灭一个目标。", "任务节点达成。", "确认击杀。", "指示下一个目标。"})
E:add_audio("adamant", "YoRHa2B_ja", "response_to_hacking_fix_decode_", loc_YoRHa2B, "ja_loc_adamant_male_a__response_to_hacking_fix_decode_", 4):add_subtext("法务官", {"设备损坏，需要维修。", "请求技术支援。", "需要进行设备维护！", "立刻修复这个装置！"})
E:add_audio("adamant", "YoRHa2B_ja", "info_event_almost_done_", loc_YoRHa2B, "ja_loc_adamant_male_a__info_event_almost_done_", 2):add_subtext("法务官", {"快结束了！", "镇压即将完成！"})
E:add_audio("adamant", "YoRHa2B_ja", "warning_exploding_barrel_", loc_YoRHa2B, "ja_loc_adamant_male_a__warning_exploding_barrel_", 1):add_subtext("法务官", {"注意爆炸物！"})
E:add_audio("adamant", "YoRHa2B_ja", "response_rechargable_for_look_at_healthstation_", loc_YoRHa2B, "ja_loc_adamant_male_a__response_rechargable_for_look_at_healthstation_", 4):add_subtext("法务官", {"发现医疗站，进行补给。", "确认到医疗设施。", "前往医疗站休整。", "需要医疗援助的立刻前往。"})
E:add_audio("adamant", "YoRHa2B_ja", "smart_tag_vo_station_health_", loc_YoRHa2B, "ja_loc_adamant_male_a__smart_tag_vo_station_health_", 2):add_subtext("法务官", {"标记医疗站。", "这里有医疗设施。"})
E:add_audio("adamant", "YoRHa2B_ja", "ability_stance_a_", loc_YoRHa2B, "ja_loc_adamant_male_a__ability_stance_a_", 6):add_subtext("法务官", {"进入战斗姿态。", "准备交战。", "迅速解决。", "执行死刑！", "罪无可恕！", "发现大量敌对目标，申请武力介入。"}):set_priority(2)
E:add_audio("adamant", "YoRHa2B_ja", "blitz_nuncio_a_", loc_YoRHa2B, "ja_loc_adamant_male_a__blitz_nuncio_a_", 5, 4):add_subtext("法务官", {"启动辅助装备。", "护盾充能完毕。", "物理防御就绪。", "请求掩护！", "由我来提供火力支援！"}):set_priority(2)
E:add_audio("adamant", "YoRHa2B_ja", "ability_charge_a_", loc_YoRHa2B, "ja_loc_adamant_male_a__ability_charge_a_", 6, 4):add_subtext("法务官", {"突击！", "让开！", "肃静！", "冲锋！", "破阵！", "从这里突破！"}):set_priority(2)
E:add_audio("adamant", "YoRHa2B_ja", "blitz_mine_a_", loc_YoRHa2B, "ja_loc_adamant_male_a__blitz_mine_a_", 4, 4):add_subtext("法务官", {"部署地雷。", "设置陷阱。", "爆破陷阱就绪。", "警戒装置已安置。"})
E:add_audio("adamant", "YoRHa2B_ja", "blitz_grenade_a_", loc_YoRHa2B, "ja_loc_adamant_male_a__blitz_grenade_a_", 4):add_subtext("法务官", {"震撼弹！", "爆破！", "清场！", "手雷！"})
E:add_audio("adamant", "YoRHa2B_ja", "blitz_kill_attack_a_", loc_YoRHa2B, "ja_loc_adamant_male_a__blitz_kill_attack_a_", 5):add_subtext("法务官", {"收到。", "了解。", "执行。", "确认。", "遵命。"})
E:add_audio("adamant", "YoRHa2B_ja", "blitz_grenade_box_a_", loc_YoRHa2B, "ja_loc_adamant_male_a__blitz_grenade_box_a_", 4):add_subtext("法务官", {"投掷爆炸物！", "当心手雷！", "炸弹来袭！", "清场准备！"})
E:add_audio("adamant", "YoRHa2B_ja", "throwing_grenade_", loc_YoRHa2B, "ja_loc_adamant_male_a__throwing_grenade_", 4):add_subtext("法务官", {"投掷爆炸物！", "当心手雷！", "炸弹来袭！", "清场准备！"})
E:add_audio("adamant", "YoRHa2B_ja", "com_wheel_vo_location_ping_", loc_YoRHa2B, "ja_loc_adamant_male_a__com_wheel_vo_location_ping_", 4):add_subtext("法务官", {"目标地点在这。", "前往该坐标。", "加快速度。", "沿此路线推进。"})
E:add_audio("adamant", "YoRHa2B_ja", "com_wheel_vo_location_attention_", loc_YoRHa2B, "ja_loc_adamant_male_a__com_wheel_vo_location_attention_", 4):add_subtext("法务官", {"注意这里。", "看那个坐标。", "警惕该区域。", "在此处集合。"})
E:add_audio("adamant", "YoRHa2B_ja", "com_wheel_vo_yes_", loc_YoRHa2B, "ja_loc_adamant_male_a__com_wheel_vo_yes_", 6):add_subtext("法务官", {"收到。", "了解。", "执行命令。", "明白。", "目标确认。", "同意。"})
E:add_audio("adamant", "YoRHa2B_ja", "com_wheel_vo_no_", loc_YoRHa2B, "ja_loc_adamant_male_a__com_wheel_vo_no_", 5):add_subtext("法务官", {"否定。", "拒绝。", "不行。", "驳回。", "不可行。"})
E:add_audio("adamant", "YoRHa2B_ja", "com_wheel_vo_enemy_over_here_", loc_YoRHa2B, "ja_loc_adamant_male_a__com_wheel_vo_enemy_over_here_", 2):add_subtext("法务官", {"警惕伏击！", "前方区域有危险！"})
E:add_audio("adamant", "YoRHa2B_ja", "com_wheel_vo_thank_you_", loc_YoRHa2B, "ja_loc_adamant_male_a__com_wheel_vo_thank_you_", 4):add_subtext("法务官", {"收到支援，感谢。", "感谢协助。", "欠你个人情。", "做得好。"})
E:add_audio("adamant", "YoRHa2B_ja", "com_wheel_vo_need_ammo_", loc_YoRHa2B, "ja_loc_adamant_male_a__com_wheel_vo_need_ammo_", 2):add_subtext("法务官", {"弹药匮乏！", "请求弹药补给！"})
E:add_audio("adamant", "YoRHa2B_ja", "com_wheel_vo_need_health_", loc_YoRHa2B, "ja_loc_adamant_male_a__com_wheel_vo_need_health_", 3):add_subtext("法务官", {"我需要医疗支援！", "请求治疗！", "需要急救包！"})
E:add_audio("adamant", "YoRHa2B_ja", "com_wheel_vo_for_the_emperor_", loc_YoRHa2B, "ja_loc_adamant_male_a__com_wheel_vo_for_the_emperor_", 4):add_subtext("法务官", {"为了神皇！", "帝皇庇佑！", "神皇至高无上！", "为了王座！"})
E:add_audio("adamant", "YoRHa2B_ja", "com_wheeel_vo_follow_you_", loc_YoRHa2B, "ja_loc_adamant_male_a__com_wheeel_vo_follow_you_", 3):add_subtext("法务官", {"我掩护你。", "跟在你后面。", "你来带路。"})
E:add_audio("adamant", "YoRHa2B_ja", "reloading_", loc_YoRHa2B, "ja_loc_adamant_male_a__reloading_", 3):add_subtext("法务官", {"更换弹匣！", "装填中！", "掩护我，正在换弹！"})
E:add_audio("adamant", "YoRHa2B_ja", "look_at_grenade_", loc_YoRHa2B, "ja_loc_adamant_male_a__look_at_grenade_", 3):add_subtext("法务官", {"发现手雷。", "爆炸物补给。", "手雷箱在这里。"})
E:add_audio("adamant", "YoRHa2B_ja", "look_at_healthstation_", loc_YoRHa2B, "ja_loc_adamant_male_a__look_at_healthstation_", 2):add_subtext("法务官", {"医疗站在此。", "发现医疗设备。"})
E:add_audio("adamant", "YoRHa2B_ja", "smart_tag_vo_pickup_deployed_medical_crate_", loc_YoRHa2B, "ja_loc_adamant_male_a__smart_tag_vo_pickup_deployed_medical_crate_", 3):add_subtext("法务官", {"医疗包！", "急救物资！", "拿上医疗包！"})
E:add_audio("adamant", "YoRHa2B_ja", "smart_tag_vo_pickup_deployed_ammo_crate_", loc_YoRHa2B, "ja_loc_adamant_male_a__smart_tag_vo_pickup_deployed_ammo_crate_", 2):add_subtext("法务官", {"弹药箱！", "及时补充弹药！"})
E:add_audio("adamant", "YoRHa2B_ja", "reload_failed_out_of_ammo_", loc_YoRHa2B, "ja_loc_adamant_male_a__reload_failed_out_of_ammo_", 4):add_subtext("法务官", {"弹药耗尽！", "没有备用弹药了！", "弹匣空了！", "急需弹药！"})
E:add_audio("adamant", "YoRHa2B_ja", "smart_tag_vo_pickup_ammo_", loc_YoRHa2B, "ja_loc_adamant_male_a__smart_tag_vo_pickup_ammo_", 4):add_subtext("法务官", {"发现弹药。", "补充弹药。", "弹药在此。", "获取弹药。"})
E:add_audio("adamant", "YoRHa2B_ja", "smart_tag_vo_pickup_health_booster_", loc_YoRHa2B, "ja_loc_adamant_male_a__smart_tag_vo_pickup_health_booster_", 3):add_subtext("法务官", {"医疗针。", "急救药。", "恢复剂。"})
E:add_audio("adamant", "YoRHa2B_ja", "smart_tag_vo_pickup_forge_metal_", loc_YoRHa2B, "ja_loc_adamant_male_a__smart_tag_vo_pickup_forge_metal_", 4):add_subtext("法务官", {"发现塑钢。", "回收物资。", "这是有价值的材料。", "材料回收。"})
E:add_audio("adamant", "YoRHa2B_ja", "smart_tag_vo_pickup_platinum_", loc_YoRHa2B, "ja_loc_adamant_male_a__smart_tag_vo_pickup_platinum_", 4):add_subtext("法务官", {"发现钻石金。", "高价值物资。", "回收特殊材料。", "材料回收。"})
E:add_audio("adamant", "YoRHa2B_ja", "smart_tag_vo_pickup_small_grenade_", loc_YoRHa2B, "ja_loc_adamant_male_a__smart_tag_vo_pickup_small_grenade_", 3):add_subtext("法务官", {"手雷补给。", "爆炸物。", "补充破片手雷。"})
E:add_audio("adamant", "YoRHa2B_ja", "cover_me_", loc_YoRHa2B, "ja_loc_adamant_male_a__cover_me_", 4):add_subtext("法务官", {"掩护我！", "提供火力压制！", "请求掩护！", "掩护射击！"})
E:add_audio("adamant", "YoRHa2B_ja", "away_from_squad_", loc_YoRHa2B, "ja_loc_adamant_male_a__away_from_squad_", 4):add_subtext("法务官", {"脱离队伍了，正在返回。", "距离过远，重新归队。", "需要缩短距离。", "正在向小队靠拢。"})
E:add_audio("adamant", "YoRHa2B_ja", "come_back_to_squad_", loc_YoRHa2B, "ja_loc_adamant_male_a__come_back_to_squad_", 4):add_subtext("法务官", {"不要擅自离队！", "保持阵型！", "归队！", "缩小防线距离！"})
E:add_audio("adamant", "YoRHa2B_ja", "adamant_seen_killstreak_psyker_", loc_YoRHa2B, "ja_loc_adamant_male_a__adamant_seen_killstreak_psyker_", 5, 5):add_subtext("法务官", {"出色的镇压行动。", "继续保持火力。", "不要放松警惕。", "高效率的处决。", "干得漂亮。"}):set_priority(2)
E:add_audio("adamant", "YoRHa2B_ja", "adamant_seen_killstreak_zealot_", loc_YoRHa2B, "ja_loc_adamant_male_a__adamant_seen_killstreak_zealot_", 5, 5):add_subtext("法务官", {"出色的镇压行动。", "继续保持火力。", "不要放松警惕。", "高效率的处决。", "干得漂亮。"}):set_priority(2)
E:add_audio("adamant", "YoRHa2B_ja", "adamant_seen_killstreak_veteran_", loc_YoRHa2B, "ja_loc_adamant_male_a__adamant_seen_killstreak_veteran_", 5, 5):add_subtext("法务官", {"出色的镇压行动。", "继续保持火力。", "不要放松警惕。", "高效率的处决。", "干得漂亮。"}):set_priority(2)
E:add_audio("adamant", "YoRHa2B_ja", "adamant_seen_killstreak_ogryn_", loc_YoRHa2B, "ja_loc_adamant_male_a__adamant_seen_killstreak_ogryn_", 5, 5):add_subtext("法务官", {"出色的镇压行动。", "继续保持火力。", "不要放松警惕。", "高效率的处决。", "干得漂亮。"}):set_priority(2)
E:add_audio("adamant", "YoRHa2B_ja", "adamant_seen_killstreak_adamant_", loc_YoRHa2B, "ja_loc_adamant_male_a__adamant_seen_killstreak_adamant_", 5, 5):add_subtext("法务官", {"出色的镇压行动。", "继续保持火力。", "不要放松警惕。", "高效率的处决。", "干得漂亮。"}):set_priority(2)
E:add_audio("adamant", "YoRHa2B_ja", "response_for_zealot_seen_killstreak_adamant_", loc_YoRHa2B, "ja_loc_adamant_male_a__response_for_zealot_seen_killstreak_adamant_", 5, 4):add_subtext("法务官", {"这只是分内之事。", "集中注意力在敌人身上。", "无需多言，继续战斗。", "不要浪费时间闲聊。", "节省体力，继续推进。"}):set_priority(2)
E:add_audio("adamant", "YoRHa2B_ja", "response_for_veteran_seen_killstreak_adamant_", loc_YoRHa2B, "ja_loc_adamant_male_a__response_for_veteran_seen_killstreak_adamant_", 5, 4):add_subtext("法务官", {"这只是分内之事。", "集中注意力在敌人身上。", "无需多言，继续战斗。", "不要浪费时间闲聊。", "节省体力，继续推进。"}):set_priority(2)
E:add_audio("adamant", "YoRHa2B_ja", "response_for_psyker_seen_killstreak_adamant_", loc_YoRHa2B, "ja_loc_adamant_male_a__response_for_psyker_seen_killstreak_adamant_", 5, 4):add_subtext("法务官", {"这只是分内之事。", "集中注意力在敌人身上。", "无需多言，继续战斗。", "不要浪费时间闲聊。", "节省体力，继续推进。"}):set_priority(2)
E:add_audio("adamant", "YoRHa2B_ja", "response_for_ogryn_seen_killstreak_adamant_", loc_YoRHa2B, "ja_loc_adamant_male_a__response_for_ogryn_seen_killstreak_adamant_", 5, 4):add_subtext("法务官", {"这只是分内之事。", "集中注意力在敌人身上。", "无需多言，继续战斗。", "不要浪费时间闲聊。", "节省体力，继续推进。"}):set_priority(2)
E:add_audio("adamant", "YoRHa2B_ja", "response_for_adamant_seen_killstreak_adamant_", loc_YoRHa2B, "ja_loc_adamant_male_a__response_for_adamant_seen_killstreak_adamant_", 5, 4):add_subtext("法务官", {"这只是分内之事。", "集中注意力在敌人身上。", "无需多言，继续战斗。", "不要浪费时间闲聊。", "节省体力，继续推进。"}):set_priority(2)
E:add_audio("adamant", "YoRHa2B_ja", "response_for_friendly_fire_from_zealot_", loc_YoRHa2B, "ja_loc_adamant_male_a__response_for_friendly_fire_from_zealot_", 2):add_subtext("法务官", {"注意你的火线！", "停火，是友军！"})
E:add_audio("adamant", "YoRHa2B_ja", "response_for_friendly_fire_from_veteran_", loc_YoRHa2B, "ja_loc_adamant_male_a__response_for_friendly_fire_from_veteran_", 2):add_subtext("法务官", {"注意你的火线！", "停火，是友军！"})
E:add_audio("adamant", "YoRHa2B_ja", "response_for_friendly_fire_from_psyker_", loc_YoRHa2B, "ja_loc_adamant_male_a__response_for_friendly_fire_from_psyker_", 2):add_subtext("法务官", {"注意你的火线！", "停火，是友军！"})
E:add_audio("adamant", "YoRHa2B_ja", "response_for_friendly_fire_from_ogryn_", loc_YoRHa2B, "ja_loc_adamant_male_a__response_for_friendly_fire_from_ogryn_", 2):add_subtext("法务官", {"注意你的火线！", "停火，是友军！"})
E:add_audio("adamant", "YoRHa2B_ja", "response_for_friendly_fire_from_adamant_", loc_YoRHa2B, "ja_loc_adamant_male_a__response_for_friendly_fire_from_adamant_", 2):add_subtext("法务官", {"注意你的火线！", "停火，是友军！"})
E:add_audio("adamant", "YoRHa2B_ja", "friendly_fire_from_zealot_to_adamant_", loc_YoRHa2B, "ja_loc_adamant_male_a__friendly_fire_from_zealot_to_adamant_", 3):add_subtext("法务官", {"报告，遭遇友军火力！", "控制你的准星！", "你在向友军射击！"})
E:add_audio("adamant", "YoRHa2B_ja", "friendly_fire_from_veteran_to_adamant_", loc_YoRHa2B, "ja_loc_adamant_male_a__friendly_fire_from_veteran_to_adamant_", 3):add_subtext("法务官", {"报告，遭遇友军火力！", "控制你的准星！", "你在向友军射击！"})
E:add_audio("adamant", "YoRHa2B_ja", "friendly_fire_from_psyker_to_adamant_", loc_YoRHa2B, "ja_loc_adamant_male_a__friendly_fire_from_psyker_to_adamant_", 3):add_subtext("法务官", {"报告，遭遇友军火力！", "控制你的准星！", "你在向友军射击！"})
E:add_audio("adamant", "YoRHa2B_ja", "friendly_fire_from_ogryn_to_adamant_", loc_YoRHa2B, "ja_loc_adamant_male_a__friendly_fire_from_ogryn_to_adamant_", 3):add_subtext("法务官", {"报告，遭遇友军火力！", "控制你的准星！", "你在向友军射击！"})
E:add_audio("adamant", "YoRHa2B_ja", "friendly_fire_from_adamant_to_adamant_", loc_YoRHa2B, "ja_loc_adamant_male_a__friendly_fire_from_adamant_to_adamant_", 3):add_subtext("法务官", {"报告，遭遇友军火力！", "控制你的准星！", "你在向友军射击！"})
E:add_audio("adamant", "YoRHa2B_ja", "head_shot_", loc_YoRHa2B, "ja_loc_adamant_male_a__head_shot_", 3):add_subtext("法务官", {"精准命中！", "爆头！", "完美的击杀！"})
E:add_audio("adamant", "YoRHa2B_ja", "response_for_zealot_disabled_by_enemy_", loc_YoRHa2B, "ja_loc_adamant_male_a__response_for_zealot_disabled_by_enemy_", 4):add_subtext("法务官", {"有干员倒下！", "防线出现缺口！", "立刻展开救援！", "干员失去战斗力！"})
E:add_audio("adamant", "YoRHa2B_ja", "response_for_veteran_disabled_by_enemy_", loc_YoRHa2B, "ja_loc_adamant_male_a__response_for_veteran_disabled_by_enemy_", 4):add_subtext("法务官", {"有干员倒下！", "防线出现缺口！", "立刻展开救援！", "干员失去战斗力！"})
E:add_audio("adamant", "YoRHa2B_ja", "response_for_psyker_disabled_by_enemy_", loc_YoRHa2B, "ja_loc_adamant_male_a__response_for_psyker_disabled_by_enemy_", 4):add_subtext("法务官", {"有干员倒下！", "防线出现缺口！", "立刻展开救援！", "干员失去战斗力！"})
E:add_audio("adamant", "YoRHa2B_ja", "response_for_ogryn_disabled_by_enemy_", loc_YoRHa2B, "ja_loc_adamant_male_a__response_for_ogryn_disabled_by_enemy_", 4):add_subtext("法务官", {"有干员倒下！", "防线出现缺口！", "立刻展开救援！", "干员失去战斗力！"})
E:add_audio("adamant", "YoRHa2B_ja", "response_for_adamant_disabled_by_enemy_", loc_YoRHa2B, "ja_loc_adamant_male_a__response_for_adamant_disabled_by_enemy_", 4):add_subtext("法务官", {"有干员倒下！", "防线出现缺口！", "立刻展开救援！", "干员失去战斗力！"})
E:add_audio("adamant", "YoRHa2B_ja", "adamant_start_revive_ogryn_", loc_YoRHa2B, "ja_loc_adamant_male_a__adamant_start_revive_ogryn_", 5):add_subtext("法务官", {"坚持住，正在实施救援！", "我来掩护你！", "立刻站起来，战斗还没结束！", "紧急医疗处理中！", "保持清醒，马上就好！"})
E:add_audio("adamant", "YoRHa2B_ja", "adamant_start_revive_zealot_", loc_YoRHa2B, "ja_loc_adamant_male_a__adamant_start_revive_zealot_", 5):add_subtext("法务官", {"坚持住，正在实施救援！", "我来掩护你！", "立刻站起来，战斗还没结束！", "紧急医疗处理中！", "保持清醒，马上就好！"})
E:add_audio("adamant", "YoRHa2B_ja", "adamant_start_revive_veteran_", loc_YoRHa2B, "ja_loc_adamant_male_a__adamant_start_revive_veteran_", 5):add_subtext("法务官", {"坚持住，正在实施救援！", "我来掩护你！", "立刻站起来，战斗还没结束！", "紧急医疗处理中！", "保持清醒，马上就好！"})
E:add_audio("adamant", "YoRHa2B_ja", "adamant_start_revive_psyker_", loc_YoRHa2B, "ja_loc_adamant_male_a__adamant_start_revive_psyker_", 5):add_subtext("法务官", {"坚持住，正在实施救援！", "我来掩护你！", "立刻站起来，战斗还没结束！", "紧急医疗处理中！", "保持清醒，马上就好！"})
E:add_audio("adamant", "YoRHa2B_ja", "adamant_start_revive_adamant_", loc_YoRHa2B, "ja_loc_adamant_male_a__adamant_start_revive_adamant_", 5):add_subtext("法务官", {"坚持住，正在实施救援！", "我来掩护你！", "立刻站起来，战斗还没结束！", "紧急医疗处理中！", "保持清醒，马上就好！"})
E:add_audio("adamant", "YoRHa2B_ja", "combat_pause_quirk_sing_a_", loc_YoRHa2B, "ja_loc_adamant_male_a__combat_pause_quirk_sing_a_", 3):add_subtext("法务官", {"保持警戒状态。", "原地休整，检查装备。", "不要放松，随时准备接敌。"})
E:add_audio("adamant", "YoRHa2B_ja", "combat_pause_one_liner_", loc_YoRHa2B, "ja_loc_adamant_male_a__combat_pause_one_liner_", 3):add_subtext("法务官", {"保持警戒状态。", "原地休整，检查装备。", "不要放松，随时准备接敌。"})
E:add_audio("adamant", "YoRHa2B_ja", "surrounded_", loc_YoRHa2B, "ja_loc_adamant_male_a__surrounded_", 7):add_subtext("法务官", {"被包围了，准备突围！", "敌人数量激增！", "保持阵型，不要被冲散！", "四面受敌！", "准备迎击尸潮！", "全方向火力压制！", "防线承压，集中火力！"})
E:add_audio("adamant", "YoRHa2B_ja", "surrounded_response_", loc_YoRHa2B, "ja_loc_adamant_male_a__surrounded_response_", 5):add_subtext("法务官", {"准备战斗！", "不要惊慌！", "固守反击！", "来多少杀多少！", "执行镇压！"})
E:add_audio("adamant", "YoRHa2B_ja", "heard_horde_vector_", loc_YoRHa2B, "ja_loc_adamant_male_a__heard_horde_vector_", 6):add_subtext("法务官", {"侦测到大规模敌对反应！", "尸潮逼近！", "准备迎击大规模集群！", "敌人正在涌来！", "建立防线！", "全员戒备，敌群来袭！"})
E:add_audio("adamant", "YoRHa2B_ja", "heard_horde_ambush_", loc_YoRHa2B, "ja_loc_adamant_male_a__heard_horde_ambush_", 4):add_subtext("法务官", {"敌军伏击！", "接敌准备！", "突袭警报！", "敌人从侧翼出现了！"})
E:add_audio("adamant", "YoRHa2B_ja", "heard_enemy_beast_of_nurgle_", loc_YoRHa2B, "ja_loc_adamant_male_a__heard_enemy_beast_of_nurgle_", 4):add_subtext("法务官", {"警告：侦测到高价值威胁！", "注意，有巨型变种生物！", "大型敌对目标接近！", "威胁等级：极高！"})
E:add_audio("adamant", "YoRHa2B_ja", "heard_enemy_chaos_spawn_", loc_YoRHa2B, "ja_loc_adamant_male_a__heard_enemy_chaos_spawn_", 4):add_subtext("法务官", {"警告：侦测到高价值威胁！", "注意，有巨型变种生物！", "大型敌对目标接近！", "威胁等级：极高！"})
E:add_audio("adamant", "YoRHa2B_ja", "heard_enemy_plague_ogryn_", loc_YoRHa2B, "ja_loc_adamant_male_a__heard_enemy_plague_ogryn_", 4):add_subtext("法务官", {"警告：侦测到高价值威胁！", "注意，有巨型变种生物！", "大型敌对目标接近！", "威胁等级：极高！"})
E:add_audio("adamant", "YoRHa2B_ja", "conversation_plague_ogryn_weakpoint_01_", loc_YoRHa2B, "ja_loc_adamant_male_a__conversation_plague_ogryn_weakpoint_01_", 4):add_subtext("法务官", {"攻击它的弱点！", "集中火力攻击头部！", "集火其脆弱部位！", "优先破坏其弱点！"})
E:add_audio("adamant", "YoRHa2B_ja", "conversation_beast_of_nurgle_weakpoint_a_", loc_YoRHa2B, "ja_loc_adamant_male_a__conversation_beast_of_nurgle_weakpoint_a_", 4):add_subtext("法务官", {"攻击它的弱点！", "集中火力攻击背部！", "集火其脆弱部位！", "优先破坏其弱点！"})
E:add_audio("adamant", "YoRHa2B_ja", "conversation_beast_of_nurgle_weakpoint_c_", loc_YoRHa2B, "ja_loc_adamant_male_a__conversation_beast_of_nurgle_weakpoint_c_", 4):add_subtext("法务官", {"攻击它的弱点！", "集中火力攻击背部！", "集火其脆弱部位！", "优先破坏其弱点！"})
E:add_audio("adamant", "YoRHa2B_ja", "seen_enemy_plague_ogryn_", loc_YoRHa2B, "ja_loc_adamant_male_a__seen_enemy_plague_ogryn_", 6):add_subtext("法务官", {"发现瘟疫欧格林！", "发现巨型变体！", "大型目标，请求集火！", "优先排除该目标！", "准备迎战巨兽！", "执行破坏指令！"})
E:add_audio("adamant", "YoRHa2B_ja", "seen_enemy_beast_of_nurgle_", loc_YoRHa2B, "ja_loc_adamant_male_a__seen_enemy_beast_of_nurgle_", 6):add_subtext("法务官", {"发现巨兽！", "发现巨型变体！", "大型目标，请求集火！", "优先排除该目标！", "准备迎战巨兽！", "执行破坏指令！"})
E:add_audio("adamant", "YoRHa2B_ja", "seen_enemy_chaos_spawn_", loc_YoRHa2B, "ja_loc_adamant_male_a__seen_enemy_chaos_spawn_", 6):add_subtext("法务官", {"发现混沌卵！", "发现巨型变体！", "大型目标，请求集火！", "优先排除该目标！", "准备迎战巨兽！", "执行破坏指令！"})
E:add_audio("adamant", "YoRHa2B_ja", "smart_tag_vo_enemy_chaos_spawn_a_", loc_YoRHa2B, "ja_loc_adamant_male_a__smart_tag_vo_enemy_chaos_spawn_a_", 6):add_subtext("法务官", {"锁定混沌卵！", "标记巨型变体！", "大型目标，请求集火！", "优先排除该目标！", "准备迎战巨兽！", "执行破坏指令！"})
E:add_audio("adamant", "YoRHa2B_ja", "smart_tag_vo_enemy_chaos_spawn_b_", loc_YoRHa2B, "ja_loc_adamant_male_a__smart_tag_vo_enemy_chaos_spawn_b_", 6):add_subtext("法务官", {"锁定混沌卵！", "标记巨型变体！", "大型目标，请求集火！", "优先排除该目标！", "准备迎战巨兽！", "执行破坏指令！"})
E:add_audio("adamant", "YoRHa2B_ja", "smart_tag_vo_enemy_beast_of_nurgle_", loc_YoRHa2B, "ja_loc_adamant_male_a__smart_tag_vo_enemy_beast_of_nurgle_", 6):add_subtext("法务官", {"锁定纳垢兽！", "标记巨型变体！", "大型目标，请求集火！", "优先排除该目标！", "准备迎战巨兽！", "执行破坏指令！"})
E:add_audio("adamant", "YoRHa2B_ja", "smart_tag_vo_enemy_plague_ogryn_", loc_YoRHa2B, "ja_loc_adamant_male_a__smart_tag_vo_enemy_plague_ogryn_", 6):add_subtext("法务官", {"锁定瘟疫欧格林！", "标记巨型变体！", "大型目标，请求集火！", "优先排除该目标！", "准备迎战巨兽！", "执行破坏指令！"})
E:add_audio("adamant", "YoRHa2B_ja", "heard_enemy_daemonhost_", loc_YoRHa2B, "ja_loc_adamant_male_a__heard_enemy_daemonhost_", 1):add_subtext("法务官", {"侦测到恶魔宿主反应。"})
E:add_audio("adamant", "YoRHa2B_ja", "seen_enemy_daemonhost_", loc_YoRHa2B, "ja_loc_adamant_male_a__seen_enemy_daemonhost_", 1):add_subtext("法务官", {"发现恶魔宿主，关掉手电，保持安静。"})
E:add_audio("adamant", "YoRHa2B_ja", "alerted_ememy_daemonhost_", loc_YoRHa2B, "ja_loc_adamant_male_a__alerted_ememy_daemonhost_", 2):add_subtext("法务官", {"恶魔宿主被惊动了！", "准备迎战恶魔！"})
E:add_audio("adamant", "YoRHa2B_ja", "smart_tag_vo_enemy_daemonhost_", loc_YoRHa2B, "ja_loc_adamant_male_a__smart_tag_vo_enemy_daemonhost_", 4):add_subtext("法务官", {"恶魔宿主！", "绕开那个恶魔！", "高危目标，不要惊动它！", "发现恶魔宿主！"})
E:add_audio("adamant", "YoRHa2B_ja", "monster_fight_start_reaction_", loc_YoRHa2B, "ja_loc_adamant_male_a__monster_fight_start_reaction_", 5, 4):add_subtext("法务官", {"开始讨伐巨型目标！", "集火那个怪物！", "阵型散开，避免被一击溃散！", "执行重火力压制！", "消灭这个异端！"}):set_priority(2)
E:add_audio("adamant", "YoRHa2B_ja", "enemy_near_death_monster_", loc_YoRHa2B, "ja_loc_adamant_male_a__enemy_near_death_monster_", 6, 4):add_subtext("法务官", {"目标即将崩溃！", "继续射击，它快不行了！", "给它最后一击！", "不要停火！", "消灭它！", "目标生命体征衰竭！"}):set_priority(2)
E:add_audio("adamant", "YoRHa2B_ja", "enemy_kill_monster_", loc_YoRHa2B, "ja_loc_adamant_male_a__enemy_kill_monster_", 6, 4):add_subtext("法务官", {"巨型威胁已消除。", "目标肃清完毕。", "怪物已被处决。", "干得好，继续前进。", "威胁解除。", "镇压成功。"}):set_priority(2)
E:add_audio("adamant", "YoRHa2B_ja", "mission_cargo_something_big_", loc_YoRHa2B, "ja_loc_adamant_male_a__mission_cargo_something_big_", 2):add_subtext("法务官", {"侦测到强烈震动。", "有巨大的东西在移动。"})
E:add_audio("adamant", "YoRHa2B_ja", "heard_enemy_chaos_hound_", loc_YoRHa2B, "ja_loc_adamant_male_a__heard_enemy_chaos_hound_", 4):add_subtext("法务官", {"听到猎犬的声音！", "警惕瘟疫猎犬！", "有猎犬在附近！", "注意猎犬的突袭！"})
E:add_audio("adamant", "YoRHa2B_ja", "seen_enemy_chaos_hound_", loc_YoRHa2B, "ja_loc_adamant_male_a__seen_enemy_chaos_hound_", 4):add_subtext("法务官", {"发现猎犬！", "猎犬出现了！", "击杀那只猎犬！", "瘟疫猎犬来袭！"})
E:add_audio("adamant", "YoRHa2B_ja", "smart_tag_vo_enemy_chaos_hound_", loc_YoRHa2B, "ja_loc_adamant_male_a__smart_tag_vo_enemy_chaos_hound_", 3):add_subtext("法务官", {"标记猎犬。", "猎犬在这里。", "锁定猎犬。"})
E:add_audio("adamant", "YoRHa2B_ja", "enemy_kill_chaos_hound_", loc_YoRHa2B, "ja_loc_adamant_male_a__enemy_kill_chaos_hound_", 4):add_subtext("法务官", {"猎犬已击毙。", "成功处理猎犬。", "猎犬消除。", "排除完毕。"})
E:add_audio("adamant", "YoRHa2B_ja", "seen_netgunner_", loc_YoRHa2B, "ja_loc_adamant_male_a__seen_netgunner_", 4):add_subtext("法务官", {"发现陷阱手！", "注意捕网陷阱！", "陷阱手出现了！", "优先击杀陷阱手！"})
E:add_audio("adamant", "YoRHa2B_ja", "seen_netgunner_flee_", loc_YoRHa2B, "ja_loc_adamant_male_a__seen_netgunner_flee_", 1):add_subtext("法务官", {"陷阱手正在逃窜！"})
E:add_audio("adamant", "YoRHa2B_ja", "smart_tag_vo_enemy_netgunner_", loc_YoRHa2B, "ja_loc_adamant_male_a__smart_tag_vo_enemy_netgunner_", 3):add_subtext("法务官", {"标记陷阱手。", "陷阱手在这里。", "锁定陷阱手。"})
E:add_audio("adamant", "YoRHa2B_ja", "enemy_kill_netgunner_", loc_YoRHa2B, "ja_loc_adamant_male_a__enemy_kill_netgunner_", 4):add_subtext("法务官", {"陷阱手已被处决。", "成功处理陷阱手。", "威胁消除。", "排除完毕。"})
E:add_audio("adamant", "YoRHa2B_ja", "seen_enemy_mutant_charger_", loc_YoRHa2B, "ja_loc_adamant_male_a__seen_enemy_mutant_charger_", 4):add_subtext("法务官", {"变种人冲锋！", "注意躲避变种人！", "变种人来袭！", "打断它的冲锋！"})
E:add_audio("adamant", "YoRHa2B_ja", "smart_tag_vo_enemy_chaos_mutant_charger_", loc_YoRHa2B, "ja_loc_adamant_male_a__smart_tag_vo_enemy_chaos_mutant_charger_", 3):add_subtext("法务官", {"标记变种人。", "锁定变种人目标。", "变种人在这里。"})
E:add_audio("adamant", "YoRHa2B_ja", "enemy_kill_mutant_charger_", loc_YoRHa2B, "ja_loc_adamant_male_a__enemy_kill_mutant_charger_", 4):add_subtext("法务官", {"变种人已击毙。", "冲锋被终结。", "威胁消除。", "排除完毕。"})
E:add_audio("adamant", "YoRHa2B_ja", "heard_enemy_poxwalker_bomber_", loc_YoRHa2B, "ja_loc_adamant_male_a__heard_enemy_poxwalker_bomber_", 4):add_subtext("法务官", {"听到炸弹人的引信声！", "警惕炸弹人！", "附近有炸弹人！", "注意爆破威胁！"})
E:add_audio("adamant", "YoRHa2B_ja", "seen_enemy_poxwalker_bomber_", loc_YoRHa2B, "ja_loc_adamant_male_a__seen_enemy_poxwalker_bomber_", 4):add_subtext("法务官", {"发现炸弹人！", "炸弹人出现了！", "击杀炸弹人，不要让它靠近！", "拉开距离，是炸弹人！"})
E:add_audio("adamant", "YoRHa2B_ja", "smart_tag_vo_enemy_chaos_poxwalker_bomber_", loc_YoRHa2B, "ja_loc_adamant_male_a__smart_tag_vo_enemy_chaos_poxwalker_bomber_", 3):add_subtext("法务官", {"标记炸弹人。", "锁定炸弹人目标。", "炸弹人在这里。"})
E:add_audio("adamant", "YoRHa2B_ja", "enemy_kill_poxwalker_bomber_", loc_YoRHa2B, "ja_loc_adamant_male_a__enemy_kill_poxwalker_bomber_", 4):add_subtext("法务官", {"炸弹人已引爆。", "成功处理爆破威胁。", "威胁消除。", "排除完毕。"})
E:add_audio("adamant", "YoRHa2B_ja", "smart_tag_vo_enemy_scab_flamer_a_", loc_YoRHa2B, "ja_loc_adamant_male_a__smart_tag_vo_enemy_scab_flamer_a_", 3):add_subtext("法务官", {"标记火焰兵。", "锁定火焰兵。", "火焰兵在这里。"})
E:add_audio("adamant", "YoRHa2B_ja", "smart_tag_vo_tox_flamer_", loc_YoRHa2B, "ja_loc_adamant_male_a__smart_tag_vo_tox_flamer_", 3):add_subtext("法务官", {"标记火焰兵。", "锁定火焰兵。", "火焰兵在这里。"})
E:add_audio("adamant", "YoRHa2B_ja", "seen_enemy_tox_flamer_", loc_YoRHa2B, "ja_loc_adamant_male_a__seen_enemy_tox_flamer_", 2):add_subtext("法务官", {"发现火焰兵！", "躲避火焰喷射！"})
E:add_audio("adamant", "YoRHa2B_ja", "seen_enemy_scab_flamer_a_", loc_YoRHa2B, "ja_loc_adamant_male_a__seen_enemy_scab_flamer_a_", 2):add_subtext("法务官", {"发现火焰兵！", "躲避火焰喷射！"})
E:add_audio("adamant", "YoRHa2B_ja", "enemy_kill_tox_flamer_", loc_YoRHa2B, "ja_loc_adamant_male_a__enemy_kill_tox_flamer_", 4):add_subtext("法务官", {"火焰兵已击毙。", "燃料罐引爆。", "威胁消除。", "排除完毕。"})
E:add_audio("adamant", "YoRHa2B_ja", "enemy_kill_scab_flamer_a_", loc_YoRHa2B, "ja_loc_adamant_male_a__enemy_kill_scab_flamer_a_", 4):add_subtext("法务官", {"火焰兵已击毙。", "燃料罐引爆。", "威胁消除。", "排除完毕。"})
E:add_audio("adamant", "YoRHa2B_ja", "seen_enemy_traitor_grenadier_", loc_YoRHa2B, "ja_loc_adamant_male_a__seen_enemy_traitor_grenadier_", 4):add_subtext("法务官", {"发现掷弹兵！", "注意手雷！", "掷弹兵来袭！", "优先清除掷弹兵！"})
E:add_audio("adamant", "YoRHa2B_ja", "smart_tag_vo_enemy_traitor_grenadier_", loc_YoRHa2B, "ja_loc_adamant_male_a__smart_tag_vo_enemy_traitor_grenadier_", 3):add_subtext("法务官", {"标记掷弹兵。", "锁定掷弹兵。", "掷弹兵在这里。"})
E:add_audio("adamant", "YoRHa2B_ja", "enemy_kill_traitor_grenadier_", loc_YoRHa2B, "ja_loc_adamant_male_a__enemy_kill_traitor_grenadier_", 4):add_subtext("法务官", {"掷弹兵已击毙。", "成功处理掷弹兵。", "威胁消除。", "排除完毕。"})
E:add_audio("adamant", "YoRHa2B_ja", "seen_enemy_cultist_grenadier_", loc_YoRHa2B, "ja_loc_adamant_male_a__seen_enemy_cultist_grenadier_", 4):add_subtext("法务官", {"发现掷弹兵！", "注意手雷！", "掷弹兵来袭！", "优先清除掷弹兵！"})
E:add_audio("adamant", "YoRHa2B_ja", "smart_tag_vo_enemy_cultist_grenadier_", loc_YoRHa2B, "ja_loc_adamant_male_a__smart_tag_vo_enemy_cultist_grenadier_", 3):add_subtext("法务官", {"标记掷弹兵。", "锁定掷弹兵。", "掷弹兵在这里。"})
E:add_audio("adamant", "YoRHa2B_ja", "enemy_kill_grenadier_", loc_YoRHa2B, "ja_loc_adamant_male_a__enemy_kill_grenadier_", 4):add_subtext("法务官", {"掷弹兵已击毙。", "成功处理掷弹兵。", "威胁消除。", "排除完毕。"})
E:add_audio("adamant", "YoRHa2B_ja", "smart_tag_vo_enemy_traitor_sniper_", loc_YoRHa2B, "ja_loc_adamant_male_a__smart_tag_vo_enemy_traitor_sniper_", 3):add_subtext("法务官", {"标记狙击手。", "锁定狙击手。", "狙击手在这里。"})
E:add_audio("adamant", "YoRHa2B_ja", "seen_enemy_sniper_", loc_YoRHa2B, "ja_loc_adamant_male_a__seen_enemy_sniper_", 4):add_subtext("法务官", {"发现狙击手！", "找掩体，有狙击手！", "狙击手正在瞄准！", "卧倒！"})
E:add_audio("adamant", "YoRHa2B_ja", "enemy_kill_sniper_a_", loc_YoRHa2B, "ja_loc_adamant_male_a__enemy_kill_sniper_a_", 4):add_subtext("法务官", {"狙击手已拔除。", "反狙击成功。", "威胁消除。", "排除完毕。"})
E:add_audio("adamant", "YoRHa2B_ja", "seen_enemy_traitor_gunner_", loc_YoRHa2B, "ja_loc_adamant_male_a__seen_enemy_traitor_gunner_", 4):add_subtext("法务官", {"发现机枪手！", "火力压制，有重机枪！", "机枪手来袭！", "寻找掩体！"})
E:add_audio("adamant", "YoRHa2B_ja", "smart_tag_vo_enemy_traitor_gunner_", loc_YoRHa2B, "ja_loc_adamant_male_a__smart_tag_vo_enemy_traitor_gunner_", 4):add_subtext("法务官", {"标记机枪手。", "锁定机枪手。", "消灭那个机枪手！", "机枪阵地在这里。"})
E:add_audio("adamant", "YoRHa2B_ja", "seen_enemy_cultist_holy_stubber_gunner_", loc_YoRHa2B, "ja_loc_adamant_male_a__seen_enemy_cultist_holy_stubber_gunner_", 4):add_subtext("法务官", {"发现机枪手！", "火力压制，有重机枪！", "机枪手来袭！", "寻找掩体！"})
E:add_audio("adamant", "YoRHa2B_ja", "smart_tag_vo_enemy_cultist_holy_stubber_gunner_", loc_YoRHa2B, "ja_loc_adamant_male_a__smart_tag_vo_enemy_cultist_holy_stubber_gunner_", 4):add_subtext("法务官", {"标记机枪手。", "锁定机枪手。", "消灭那个机枪手！", "机枪阵地在这里。"})
E:add_audio("adamant", "YoRHa2B_ja", "seen_enemy_heavy_gunner_", loc_YoRHa2B, "ja_loc_adamant_male_a__seen_enemy_heavy_gunner_", 4):add_subtext("法务官", {"发现机枪手！", "火力压制，有重机枪！", "机枪手来袭！", "寻找掩体！"})
E:add_audio("adamant", "YoRHa2B_ja", "smart_tag_vo_enemy_heavy_gunner_", loc_YoRHa2B, "ja_loc_adamant_male_a__smart_tag_vo_enemy_heavy_gunner_", 4):add_subtext("法务官", {"标记机枪手。", "锁定机枪手。", "消灭那个机枪手！", "机枪阵地在这里。"})
E:add_audio("adamant", "YoRHa2B_ja", "seen_enemy_shocktrooper_", loc_YoRHa2B, "ja_loc_adamant_male_a__seen_enemy_shocktrooper_", 4):add_subtext("法务官", {"发现霰弹枪手！", "近战射手逼近！", "霰弹枪手来袭！", "保持距离！"})
E:add_audio("adamant", "YoRHa2B_ja", "smart_tag_vo_enemy_traitor_scout_shocktrooper_", loc_YoRHa2B, "ja_loc_adamant_male_a__smart_tag_vo_enemy_traitor_scout_shocktrooper_", 4):add_subtext("法务官", {"标记霰弹枪手。", "锁定霰弹枪手。", "霰弹枪手在这里。", "优先处理近战射手。"})
E:add_audio("adamant", "YoRHa2B_ja", "seen_enemy_cultist_shocktrooper_", loc_YoRHa2B, "ja_loc_adamant_male_a__seen_enemy_cultist_shocktrooper_", 4):add_subtext("法务官", {"发现霰弹枪手！", "近战射手逼近！", "霰弹枪手来袭！", "保持距离！"})
E:add_audio("adamant", "YoRHa2B_ja", "smart_tag_vo_enemy_cultist_shocktrooper_", loc_YoRHa2B, "ja_loc_adamant_male_a__smart_tag_vo_enemy_cultist_shocktrooper_", 4):add_subtext("法务官", {"标记霰弹枪手。", "锁定霰弹枪手。", "霰弹枪手在这里。", "优先处理近战射手。"})
E:add_audio("adamant", "YoRHa2B_ja", "seen_enemy_executor_", loc_YoRHa2B, "ja_loc_adamant_male_a__seen_enemy_executor_", 4):add_subtext("法务官", {"发现重锤兵！", "重甲近战兵来袭！", "重锤兵逼近！", "不要被他近身！"})
E:add_audio("adamant", "YoRHa2B_ja", "smart_tag_vo_enemy_traitor_executor_", loc_YoRHa2B, "ja_loc_adamant_male_a__smart_tag_vo_enemy_traitor_executor_", 4):add_subtext("法务官", {"标记重锤兵。", "锁定重锤兵。", "集火那个近战兵！", "重锤兵在这里。"})
E:add_audio("adamant", "YoRHa2B_ja", "smart_tag_vo_enemy_chaos_ogryn_bulwark_", loc_YoRHa2B, "ja_loc_adamant_male_a__smart_tag_vo_enemy_chaos_ogryn_bulwark_", 2):add_subtext("法务官", {"标记盾卫。", "绕过他的盾牌！"})
E:add_audio("adamant", "YoRHa2B_ja", "seen_enemy_bulwark_", loc_YoRHa2B, "ja_loc_adamant_male_a__seen_enemy_bulwark_", 2):add_subtext("法务官", {"发现盾卫！", "有盾牌掩护的敌人！"})
E:add_audio("adamant", "YoRHa2B_ja", "seen_enemy_chaos_ogryn_armored_executor_", loc_YoRHa2B, "ja_loc_adamant_male_a__seen_enemy_chaos_ogryn_armored_executor_", 4):add_subtext("法务官", {"发现粉碎者！", "重甲欧格林逼近！", "粉碎者来袭！", "使用穿甲武器！"})
E:add_audio("adamant", "YoRHa2B_ja", "smart_tag_vo_enemy_chaos_ogryn_armored_executor_", loc_YoRHa2B, "ja_loc_adamant_male_a__smart_tag_vo_enemy_chaos_ogryn_armored_executor_", 4):add_subtext("法务官", {"标记粉碎者。", "锁定重甲欧格林。", "粉碎者在这里。", "集火那个粉碎者！"})
E:add_audio("adamant", "YoRHa2B_ja", "seen_enemy_chaos_ogryn_heavy_gunner_", loc_YoRHa2B, "ja_loc_adamant_male_a__seen_enemy_chaos_ogryn_heavy_gunner_", 4):add_subtext("法务官", {"发现收割者！", "重型火力压制！", "收割者来袭！", "找掩体！"})
E:add_audio("adamant", "YoRHa2B_ja", "smart_tag_vo_enemy_chaos_ogryn_heavy_gunner_", loc_YoRHa2B, "ja_loc_adamant_male_a__smart_tag_vo_enemy_chaos_ogryn_heavy_gunner_", 4):add_subtext("法务官", {"标记收割者。", "锁定收割者。", "收割者在这里。", "压制那个重机枪！"})
E:add_audio("adamant", "YoRHa2B_ja", "seen_enemy_berserker_", loc_YoRHa2B, "ja_loc_adamant_male_a__seen_enemy_berserker_", 4):add_subtext("法务官", {"发现狂战士！", "狂热者冲锋！", "狂战士来袭！", "在他们靠近前击毙！"})
E:add_audio("adamant", "YoRHa2B_ja", "smart_tag_vo_enemy_berserker_", loc_YoRHa2B, "ja_loc_adamant_male_a__smart_tag_vo_enemy_berserker_", 4):add_subtext("法务官", {"标记狂战士。", "锁定狂战士。", "狂战士在这里。", "拦住他们！"})
E:add_audio("adamant", "YoRHa2B_ja", "enemy_kill_berserker_", loc_YoRHa2B, "ja_loc_adamant_male_a__enemy_kill_berserker_", 5):add_subtext("法务官", {"狂战士已击毙。", "成功阻止冲锋。", "异端已伏法。", "威胁消除。", "排除完毕。"})
E:add_audio("adamant", "YoRHa2B_ja", "enemy_kill_berserker_ext_03_c_", loc_YoRHa2B, "ja_loc_adamant_male_a__enemy_kill_berserker_ext_03_c_", 5):add_subtext("法务官", {"狂战士已击毙。", "成功阻止冲锋。", "异端已伏法。", "威胁消除。", "排除完毕。"})
E:add_audio("adamant", "YoRHa2B_ja", "seen_enemy_group_far_range_shooting_behind_cover_", loc_YoRHa2B, "ja_loc_adamant_male_a__seen_enemy_group_far_range_shooting_behind_cover_", 3):add_subtext("法务官", {"敌人在掩体后方射击！", "实施火力压制！", "把他们从掩体后面逼出来！"})
E:add_audio("adamant", "YoRHa2B_ja", "seen_enemy_group_assaulting_", loc_YoRHa2B, "ja_loc_adamant_male_a__seen_enemy_group_assaulting_", 4):add_subtext("法务官", {"敌方小队突击！", "迎击敌方冲锋！", "准备交战！", "坚守防线！"})
E:add_audio("adamant", "YoRHa2B_ja", "quick_agnostic_enemy_kill_a_", loc_YoRHa2B, "ja_loc_adamant_male_a__quick_agnostic_enemy_kill_a_", 8, 3):add_subtext("法务官", {"正法。", "处决。", "肃清。", "击杀。", "下一个。", "障碍清除。", "异端已死。", "毫无价值。"}):set_priority(2)
E:add_audio("adamant", "YoRHa2B_ja", "player_tip_armor_hit_generic_", loc_YoRHa2B, "ja_loc_adamant_male_a__player_tip_armor_hit_generic_", 4):add_subtext("法务官", {"无效射击，攻击无装甲部位！", "武器无法击穿装甲！", "瞄准弱点！", "改变攻击角度！"})
E:add_audio("adamant", "YoRHa2B_ja", "event_kill_tareget_damaged_", loc_YoRHa2B, "ja_loc_adamant_male_a__event_kill_tareget_damaged_", 2):add_subtext("法务官", {"目标受到重创！", "继续火力压制！"})
E:add_audio("adamant", "YoRHa2B_ja", "event_kill_target_heavy_damage_a_", loc_YoRHa2B, "ja_loc_adamant_male_a__event_kill_target_heavy_damage_a_", 2):add_subtext("法务官", {"目标濒临崩溃！", "执行最终处决！"})
E:add_audio("adamant", "YoRHa2B_ja", "event_kill_target_destroyed_a_", loc_YoRHa2B, "ja_loc_adamant_male_a__event_kill_target_destroyed_a_", 2):add_subtext("法务官", {"目标已被彻底摧毁。", "肃清任务完成。"})
E:add_audio("adamant", "YoRHa2B_ja", "guidance_switch_", loc_YoRHa2B, "ja_loc_adamant_male_a__guidance_switch_", 2):add_subtext("法务官", {"找到控制开关。", "操作终端在这里。"})
E:add_audio("adamant", "YoRHa2B_ja", "luggable_mission_pick_up_", loc_YoRHa2B, "ja_loc_adamant_male_a__luggable_mission_pick_up_", 3):add_subtext("法务官", {"我拿到了任务物品。", "物资回收完毕。", "我正在搬运目标。"})
E:add_audio("adamant", "YoRHa2B_ja", "critical_health_", loc_YoRHa2B, "ja_loc_adamant_male_a__critical_health_", 5, 7):add_subtext("法务官", {"护甲受损严重！", "机能下降，需要急救！", "我撑不了多久了！", "受到重创！", "立刻请求医疗支援！"}):set_priority(2)
E:add_audio("adamant", "YoRHa2B_ja", "smart_tag_stimm_power_a_", loc_YoRHa2B, "ja_loc_adamant_male_a__smart_tag_stimm_power_a_", 4):add_subtext("法务官", {"攻击力强化剂！", "红色针剂！", "获取火力增益！", "力量强化！"})
E:add_audio("adamant", "YoRHa2B_ja", "smart_tag_stimm_speed_a_", loc_YoRHa2B, "ja_loc_adamant_male_a__smart_tag_stimm_speed_a_", 4):add_subtext("法务官", {"敏捷强化剂！", "蓝色针剂！", "获取速度增益！", "机动强化！"})
E:add_audio("adamant", "YoRHa2B_ja", "smart_tag_stimm_concentration_a_", loc_YoRHa2B, "ja_loc_adamant_male_a__smart_tag_stimm_concentration_a_", 4):add_subtext("法务官", {"专注强化剂！", "黄色针剂！", "获取技能增益！", "效能强化！"})
E:add_audio("adamant", "YoRHa2B_ja", "smart_tag_vo_small_grenade_", loc_YoRHa2B, "ja_loc_adamant_male_a__smart_tag_vo_small_grenade_", 3):add_subtext("法务官", {"这里有破片手雷。", "手雷补给在此。", "拿上这些爆炸物。"})
E:add_audio("adamant", "YoRHa2B_ja", "calling_for_help_", loc_YoRHa2B, "ja_loc_adamant_male_a__calling_for_help_", 4):add_subtext("法务官", {"紧急呼叫支援！", "我被困住了！", "立刻提供掩护！", "情况危急！"})
E:add_audio("adamant", "YoRHa2B_ja", "response_for_calling_for_help_", loc_YoRHa2B, "ja_loc_adamant_male_a__response_for_calling_for_help_", 4):add_subtext("法务官", {"收到呼叫，正在前往！", "坚持住，支援马上到！", "掩护你！", "我来帮你！"})
E:add_audio("adamant", "YoRHa2B_ja", "response_for_zealot_critical_health_", loc_YoRHa2B, "ja_loc_adamant_male_a__response_for_zealot_critical_health_", 4):add_subtext("法务官", {"你的状态很差，立刻使用急救包！", "别硬撑了，去医疗站！", "掩护伤员！", "你需要医疗援助！"})
E:add_audio("adamant", "YoRHa2B_ja", "response_for_veteran_critical_health_", loc_YoRHa2B, "ja_loc_adamant_male_a__response_for_veteran_critical_health_", 4):add_subtext("法务官", {"你的状态很差，立刻使用急救包！", "别硬撑了，去医疗站！", "掩护伤员！", "你需要医疗援助！"})
E:add_audio("adamant", "YoRHa2B_ja", "response_for_psyker_critical_health_", loc_YoRHa2B, "ja_loc_adamant_male_a__response_for_psyker_critical_health_", 4):add_subtext("法务官", {"你的状态很差，立刻使用急救包！", "别硬撑了，去医疗站！", "掩护伤员！", "你需要医疗援助！"})
E:add_audio("adamant", "YoRHa2B_ja", "response_for_ogryn_critical_health_", loc_YoRHa2B, "ja_loc_adamant_male_a__response_for_ogryn_critical_health_", 4):add_subtext("法务官", {"你的状态很差，立刻使用急救包！", "别硬撑了，去医疗站！", "掩护伤员！", "你需要医疗援助！"})
E:add_audio("adamant", "YoRHa2B_ja", "response_for_adamant_critical_health_", loc_YoRHa2B, "ja_loc_adamant_male_a__response_for_adamant_critical_health_", 4):add_subtext("法务官", {"你的状态很差，立刻使用急救包！", "别硬撑了，去医疗站！", "掩护伤员！", "你需要医疗援助！"})
E:add_audio("adamant", "YoRHa2B_ja", "knocked_down_multiple_times_zealot_", loc_YoRHa2B, "ja_loc_adamant_male_a__knocked_down_multiple_times_zealot_", 4):add_subtext("法务官", {"伤员倒地，需要紧急救援！", "快把友军拉起来！", "提供火力压制，掩护救援！", "立刻进行抢救！"})
E:add_audio("adamant", "YoRHa2B_ja", "knocked_down_multiple_times_veteran_", loc_YoRHa2B, "ja_loc_adamant_male_a__knocked_down_multiple_times_veteran_", 4):add_subtext("法务官", {"伤员倒地，需要紧急救援！", "快把友军拉起来！", "提供火力压制，掩护救援！", "立刻进行抢救！"})
E:add_audio("adamant", "YoRHa2B_ja", "knocked_down_multiple_times_psyker_", loc_YoRHa2B, "ja_loc_adamant_male_a__knocked_down_multiple_times_psyker_", 4):add_subtext("法务官", {"伤员倒地，需要紧急救援！", "快把友军拉起来！", "提供火力压制，掩护救援！", "立刻进行抢救！"})
E:add_audio("adamant", "YoRHa2B_ja", "knocked_down_multiple_times_ogryn_", loc_YoRHa2B, "ja_loc_adamant_male_a__knocked_down_multiple_times_ogryn_", 4):add_subtext("法务官", {"伤员倒地，需要紧急救援！", "快把友军拉起来！", "提供火力压制，掩护救援！", "立刻进行抢救！"})
E:add_audio("adamant", "YoRHa2B_ja", "knocked_down_multiple_times_adamant_", loc_YoRHa2B, "ja_loc_adamant_male_a__knocked_down_multiple_times_adamant_", 4):add_subtext("法务官", {"伤员倒地，需要紧急救援！", "快把友军拉起来！", "提供火力压制，掩护救援！", "立刻进行抢救！"})
E:add_audio("adamant", "YoRHa2B_ja", "player_death_zealot_", loc_YoRHa2B, "ja_loc_adamant_male_a__player_death_zealot_", 2):add_subtext("法务官", {"一名队友阵亡！", "出现伤亡！"})
E:add_audio("adamant", "YoRHa2B_ja", "player_death_veteran_", loc_YoRHa2B, "ja_loc_adamant_male_a__player_death_veteran_", 2):add_subtext("法务官", {"一名队友阵亡！", "出现伤亡！"})
E:add_audio("adamant", "YoRHa2B_ja", "player_death_psyker_", loc_YoRHa2B, "ja_loc_adamant_male_a__player_death_psyker_", 2):add_subtext("法务官", {"一名队友阵亡！", "出现伤亡！"})
E:add_audio("adamant", "YoRHa2B_ja", "player_death_ogryn_", loc_YoRHa2B, "ja_loc_adamant_male_a__player_death_ogryn_", 2):add_subtext("法务官", {"一名队友阵亡！", "出现伤亡！"})
E:add_audio("adamant", "YoRHa2B_ja", "player_death_adamant_", loc_YoRHa2B, "ja_loc_adamant_male_a__player_death_adamant_", 2):add_subtext("法务官", {"一名队友阵亡！", "出现伤亡！"})
E:add_audio("adamant", "YoRHa2B_ja", "pinned_by_enemies_", loc_YoRHa2B, "ja_loc_adamant_male_a__pinned_by_enemies_", 4):add_subtext("法务官", {"遭遇火力压制！", "寻找掩体，不要露头！", "敌方火力过猛！", "我们被钉死在这里了！"})
E:add_audio("adamant", "YoRHa2B_ja", "response_for_zealot_cover_me_", loc_YoRHa2B, "ja_loc_adamant_male_a__response_for_zealot_cover_me_", 4):add_subtext("法务官", {"正在提供掩护！", "收到，火力压制中！", "掩护射击！", "前进，我掩护你！"})
E:add_audio("adamant", "YoRHa2B_ja", "response_for_veteran_cover_me_", loc_YoRHa2B, "ja_loc_adamant_male_a__response_for_veteran_cover_me_", 4):add_subtext("法务官", {"正在提供掩护！", "收到，火力压制中！", "掩护射击！", "前进，我掩护你！"})
E:add_audio("adamant", "YoRHa2B_ja", "response_for_psyker_cover_me_", loc_YoRHa2B, "ja_loc_adamant_male_a__response_for_psyker_cover_me_", 4):add_subtext("法务官", {"正在提供掩护！", "收到，火力压制中！", "掩护射击！", "前进，我掩护你！"})
E:add_audio("adamant", "YoRHa2B_ja", "response_for_ogryn_cover_me_", loc_YoRHa2B, "ja_loc_adamant_male_a__response_for_ogryn_cover_me_", 4):add_subtext("法务官", {"正在提供掩护！", "收到，火力压制中！", "掩护射击！", "前进，我掩护你！"})
E:add_audio("adamant", "adamant", "YoRHa2B_ja", "response_for_adamant_cover_me_", loc_YoRHa2B, "ja_loc_adamant_male_a__response_for_adamant_cover_me_", 4):add_subtext("法务官", {"正在提供掩护！", "收到，火力压制中！", "掩护射击！", "前进，我掩护你！"})
E:add_audio("adamant", "YoRHa2B_ja", "conversation_combat_chaos_spawn_chew_a_", loc_YoRHa2B, "ja_loc_adamant_male_a__conversation_combat_chaos_spawn_chew_a_", 4):add_subtext("法务官", {"它抓住了队友！", "救出友军！", "集火怪物，让他松手！", "打断它的动作！"})
E:add_audio("adamant", "YoRHa2B_ja", "conversation_combat_chaos_spawn_chew_b_", loc_YoRHa2B, "ja_loc_adamant_male_a__conversation_combat_chaos_spawn_chew_b_", 4):add_subtext("法务官", {"它抓住了队友！", "救出友军！", "集火怪物，让他松手！", "打断它的动作！"})
E:add_audio("adamant", "YoRHa2B_ja", "conversation_combat_chaos_spawn_chew_c_", loc_YoRHa2B, "ja_loc_adamant_male_a__conversation_combat_chaos_spawn_chew_c_", 4):add_subtext("法务官", {"它抓住了队友！", "救出友军！", "集火怪物，让他松手！", "打断它的动作！"})
E:add_audio("adamant", "YoRHa2B_ja", "vce_hurt_heavy", play_YoRHa2B, "play_adamant_male_a__vce_hurt_heavy", 4):set_priority(1)
E:add_audio("adamant", "YoRHa2B_ja", "vce_catapulted", play_YoRHa2B, "play_adamant_male_a__vce_catapulted", 2):set_priority(2)
E:add_audio("adamant", "YoRHa2B_ja", "vce_catapulted_land", play_YoRHa2B, "play_adamant_male_a__vce_catapulted_land", 1):set_priority(4)
E:add_audio("adamant", "YoRHa2B_ja", "vce_scream_long", play_YoRHa2B, "play_adamant_male_a__vce_scream_long", 2):set_priority(2)
E:add_audio("adamant", "YoRHa2B_ja", "vce_hurt_light", play_YoRHa2B, "play_adamant_male_a__vce_hurt_light", 6):set_priority(4)
E:add_audio("adamant", "YoRHa2B_ja", "vce_jump", play_YoRHa2B, "play_adamant_male_a__vce_jump", 1):set_priority(4)
E:add_audio("adamant", "YoRHa2B_ja", "vce_land_heavy", play_YoRHa2B, "play_adamant_male_a__vce_land_heavy", 4):set_priority(4)
E:add_audio("adamant", "YoRHa2B_ja", "vce_grunt_short", play_YoRHa2B, "play_adamant_male_a__vce_grunt_short", 10):set_priority(4)
E:add_audio("adamant", "YoRHa2B_ja", "vce_attack_short", play_YoRHa2B, "play_adamant_male_a__vce_attack_short", 10):set_priority(4)
E:add_audio("adamant", "YoRHa2B_ja", "vce_attack_long", play_YoRHa2B, "play_adamant_male_a__vce_attack_long", 5):set_priority(4)
E:add_audio("adamant", "YoRHa2B_ja", "vce_coughing", play_YoRHa2B, "play_adamant_male_a__vce_coughing", 1):set_priority(4)
E:add_audio("adamant", "YoRHa2B_ja", "vce_getting_up", play_YoRHa2B, "play_adamant_male_a__vce_getting_up", 1):set_priority(4)
E:add_audio("adamant", "YoRHa2B_ja", "vce_struggle_heavy", play_YoRHa2B, "play_adamant_male_a__vce_struggle_heavy", 1):set_priority(4)
E:add_audio("adamant", "YoRHa2B_ja", "play_hud_heal_2d", play_YoRHa2B, "play_adamant_male_a__vce_healing", 1, nil, "play_hud_heal_2d")
E:add_audio("adamant", "YoRHa2B_ja", "play_syringe_power_start", play_YoRHa2B, "play_syringe_power_start", 1, nil, "play_syringe_power_start"):set_priority(0)
E:add_audio("adamant", "YoRHa2B_ja", "play_syringe_ability_start", play_YoRHa2B, "play_syringe_ability_start", 1, nil, "play_syringe_ability_start"):set_priority(0)
E:add_audio("adamant", "YoRHa2B_ja", "play_syringe_speed_start", play_YoRHa2B, "play_syringe_speed_start", 1, nil, "play_syringe_speed_start"):set_priority(0)