-- 【巢都渣滓】巢都渣滓
local loc_Tokisaki = "loc_broker_male_b/Tokisaki/"
local play_Tokisaki = "wwise/events/player/play_broker_male_b/Tokisaki"
E:set_class("broker", "Tokisaki_ja", "巢都渣滓"):old_version()
E:add_audio("broker", "Tokisaki_ja", "guidance_correct_path_", loc_Tokisaki, "ja_loc_broker_male_b__guidance_correct_path_", 3):add_subtext("巢都渣滓", {"这边走，别掉队了。", "走这条破路。", "跟紧点，渣滓们。"})
E:add_audio("broker", "Tokisaki_ja", "guidance_correct_path_up_", loc_Tokisaki, "ja_loc_broker_male_b__guidance_correct_path_up_", 4):add_subtext("巢都渣滓", {"往上爬！", "去上层！", "快点爬上去！", "往上走，动作快！"})
E:add_audio("broker", "Tokisaki_ja", "guidance_correct_path_drop_", loc_Tokisaki, "ja_loc_broker_male_b__guidance_correct_path_drop_", 5):add_subtext("巢都渣滓", {"跳下去！", "往下走，别摔断腿！", "下面有路！", "跳！", "快滚下去！"})
E:add_audio("broker", "Tokisaki_ja", "stairs_sighted_", loc_Tokisaki, "ja_loc_broker_male_b__stairs_sighted_", 2):add_subtext("巢都渣滓", {"有楼梯。", "走楼梯，别瞎跑！"})
E:add_audio("broker", "Tokisaki_ja", "guidance_starting_area_", loc_Tokisaki, "ja_loc_broker_male_b__guidance_starting_area_", 3):add_subtext("巢都渣滓", {"拿钱办事，都别磨蹭。", "活着干完这票。", "快点完事去喝一杯。"})
E:add_audio("broker", "Tokisaki_ja", "region_carnival_a_", loc_Tokisaki, "ja_loc_broker_male_b__region_carnival_a_", 1):add_subtext("巢都渣滓", {"这破地方真他妈臭。"})
E:add_audio("broker", "Tokisaki_ja", "info_event_det_pack_a_", loc_Tokisaki, "ja_loc_broker_male_b__info_event_det_pack_a_", 4):add_subtext("巢都渣滓", {"炸药放好了！", "起爆准备！", "准备把门炸开！", "退后，要炸了！"})
E:add_audio("broker", "Tokisaki_ja", "event_survive_keep_coming_a_", loc_Tokisaki, "ja_loc_broker_male_b__event_survive_keep_coming_a_", 2):add_subtext("巢都渣滓", {"守住这儿！", "别让那帮杂碎过来！"})
E:add_audio("broker", "Tokisaki_ja", "event_demolition_first_corruptor_destroyed_a_", loc_Tokisaki, "ja_loc_broker_male_b__event_demolition_first_corruptor_destroyed_a_", 4):add_subtext("巢都渣滓", {"炸烂了！", "搞定一个！", "碎成渣了！", "继续干活！"})
E:add_audio("broker", "Tokisaki_ja", "event_survive_almost_done_", loc_Tokisaki, "ja_loc_broker_male_b__event_survive_almost_done_", 4):add_subtext("巢都渣滓", {"快结束了！", "再撑一会！", "马上搞定！", "给老子顶住！"})
E:add_audio("broker", "Tokisaki_ja", "info_event_one_down_", loc_Tokisaki, "ja_loc_broker_male_b__info_event_one_down_", 4):add_subtext("巢都渣滓", {"解决一个！", "干掉一个麻烦！", "下一个在哪！", "继续继续！"})
E:add_audio("broker", "Tokisaki_ja", "response_to_hacking_fix_decode_", loc_Tokisaki, "ja_loc_broker_male_b__response_to_hacking_fix_decode_", 4):add_subtext("巢都渣滓", {"这破机器卡了！", "快来修这玩意！", "机魂不高兴了！", "谁来搞定这破终端！"})
E:add_audio("broker", "Tokisaki_ja", "info_event_almost_done_", loc_Tokisaki, "ja_loc_broker_male_b__info_event_almost_done_", 4):add_subtext("巢都渣滓", {"快完事了！", "撑住！", "马上结束！", "再坚持下！"})
E:add_audio("broker", "Tokisaki_ja", "warning_exploding_barrel_", loc_Tokisaki, "ja_loc_broker_male_b__warning_exploding_barrel_", 3):add_subtext("巢都渣滓", {"小心桶子！", "离那破桶远点！", "要炸了！"})
E:add_audio("broker", "Tokisaki_ja", "response_rechargable_for_look_at_healthstation_", loc_Tokisaki, "ja_loc_broker_male_b__response_rechargable_for_look_at_healthstation_", 4):add_subtext("巢都渣滓", {"医疗站没电了！", "去把那玩意修好！", "谁去给医疗站充能！", "医疗机停工了！"})
E:add_audio("broker", "Tokisaki_ja", "smart_tag_vo_station_health_", loc_Tokisaki, "ja_loc_broker_male_b__smart_tag_vo_station_health_", 2):add_subtext("巢都渣滓", {"有医疗站！", "赶紧治伤！"})
E:add_audio("broker", "Tokisaki_ja", "ability_03_a_", loc_Tokisaki, "ja_loc_broker_male_b__ability_03_a_", 4, 4):add_subtext("巢都渣滓", {"吃老子一记！", "去死吧异端！", "火力全开！", "尝尝这个！"}):set_priority(2)
E:add_audio("broker", "Tokisaki_ja", "ability_02_a_", loc_Tokisaki, "ja_loc_broker_male_b__ability_02_a_", 5, 4):add_subtext("巢都渣滓", {"死吧！", "哈哈，去死！", "干死你们！", "尝尝这破烂的厉害！", "给我趴下！"}):set_priority(2)
E:add_audio("broker", "Tokisaki_ja", "ability_01_a_", loc_Tokisaki, "ja_loc_broker_male_b__ability_01_a_", 8, 4):add_subtext("巢都渣滓", {"全给老子死！", "巢都人的问候！", "炸烂你们！", "吃我一招！", "火力压制！", "尝尝底巢的怒火！", "别挡道！", "去死吧！"}):set_priority(2)
E:add_audio("broker", "Tokisaki_ja", "blitz_03_a_", loc_Tokisaki, "ja_loc_broker_male_b__blitz_03_a_", 5):add_subtext("巢都渣滓", {"烧死你们！", "吃炸弹！", "炸碎他们！", "尝尝这个！", "炸烂了！"}):set_priority(2)
E:add_audio("broker", "Tokisaki_ja", "blitz_02_a_", loc_Tokisaki, "ja_loc_broker_male_b__blitz_02_a_", 4, 4):add_subtext("巢都渣滓", {"扔雷了！", "炸死你们！", "去死！", "小心手雷！" }):set_priority(2)
E:add_audio("broker", "Tokisaki_ja", "blitz_01_a_", loc_Tokisaki, "ja_loc_broker_male_b__blitz_01_a_", 5):add_subtext("巢都渣滓", {"滚开！", "吃雷！", "尝尝爆炸！", "炸死你这杂碎！", "手雷！"}):set_priority(2)
E:add_audio("broker", "Tokisaki_ja", "com_wheel_vo_location_ping_", loc_Tokisaki, "ja_loc_broker_male_b__com_wheel_vo_location_ping_", 6):add_subtext("巢都渣滓", {"去那边。", "看那里。", "往那走。", "这边走。", "目标在那。", "快点过去。"})
E:add_audio("broker", "Tokisaki_ja", "com_wheel_vo_location_attention_", loc_Tokisaki, "ja_loc_broker_male_b__com_wheel_vo_location_attention_", 2):add_subtext("巢都渣滓", {"看那边！", "注意那儿！"})
E:add_audio("broker", "Tokisaki_ja", "com_wheel_vo_yes_", loc_Tokisaki, "ja_loc_broker_male_b__com_wheel_vo_yes_", 6):add_subtext("巢都渣滓", {"收到。", "明白。", "没问题。", "这就去。", "知道了。", "行。"})
E:add_audio("broker", "Tokisaki_ja", "com_wheel_vo_no_", loc_Tokisaki, "ja_loc_broker_male_b__com_wheel_vo_no_", 1):add_subtext("巢都渣滓", {"没门。"})
E:add_audio("broker", "Tokisaki_ja", "com_wheel_vo_enemy_over_here_", loc_Tokisaki, "ja_loc_broker_male_b__com_wheel_vo_enemy_over_here_", 2):add_subtext("巢都渣滓", {"敌人！", "有异端！"})
E:add_audio("broker", "Tokisaki_ja", "com_wheel_vo_thank_you_", loc_Tokisaki, "ja_loc_broker_male_b__com_wheel_vo_thank_you_", 1):add_subtext("巢都渣滓", {"谢了。"})
E:add_audio("broker", "Tokisaki_ja", "com_wheel_vo_need_ammo_", loc_Tokisaki, "ja_loc_broker_male_b__com_wheel_vo_need_ammo_", 2):add_subtext("巢都渣滓", {"没子弹了！", "给点弹药！"})
E:add_audio("broker", "Tokisaki_ja", "com_wheel_vo_need_health_", loc_Tokisaki, "ja_loc_broker_male_b__com_wheel_vo_need_health_", 3):add_subtext("巢都渣滓", {"需要治疗！", "我快死了，来点药！", "给我医疗包！"})
E:add_audio("broker", "Tokisaki_ja", "com_wheel_vo_for_the_emperor_", loc_Tokisaki, "ja_loc_broker_male_b__com_wheel_vo_for_the_emperor_", 1):add_subtext("巢都渣滓", {"为了王座，大概吧！"})
E:add_audio("broker", "Tokisaki_ja", "com_wheel_vo_follow_you_", loc_Tokisaki, "ja_loc_broker_male_b__com_wheel_vo_follow_you_", 3):add_subtext("巢都渣滓", {"跟着你。", "你带路。", "走吧。"})
E:add_audio("broker", "Tokisaki_ja", "reloading_", loc_Tokisaki, "ja_loc_broker_male_b__reloading_", 3):add_subtext("巢都渣滓", {"换弹匣！", "没子弹了，掩护！", "装填中！"})
E:add_audio("broker", "Tokisaki_ja", "look_at_grenade_", loc_Tokisaki, "ja_loc_broker_male_b__look_at_grenade_", 3):add_subtext("巢都渣滓", {"有炸弹。", "手雷补给。", "拿雷。"})
E:add_audio("broker", "Tokisaki_ja", "look_at_healthstation_", loc_Tokisaki, "ja_loc_broker_male_b__look_at_healthstation_", 2):add_subtext("巢都渣滓", {"医疗站。", "去治伤。"})
E:add_audio("broker", "Tokisaki_ja", "smart_tag_vo_pickup_deployed_medical_crate_", loc_Tokisaki, "ja_loc_broker_male_b__smart_tag_vo_pickup_deployed_medical_crate_", 4):add_subtext("巢都渣滓", {"医疗包在这！", "拿药！", "快治伤！", "好东西。"})
E:add_audio("broker", "Tokisaki_ja", "smart_tag_vo_pickup_deployed_ammo_crate_", loc_Tokisaki, "ja_loc_broker_male_b__smart_tag_vo_pickup_deployed_ammo_crate_", 3):add_subtext("巢都渣滓", {"弹药箱！", "拿子弹！", "补给子弹！"})
E:add_audio("broker", "Tokisaki_ja", "smart_tag_vo_pickup_ammo_", loc_Tokisaki, "ja_loc_broker_male_b__smart_tag_vo_pickup_ammo_", 3):add_subtext("巢都渣滓", {"有弹药。", "子弹。", "拿子弹。"})
E:add_audio("broker", "Tokisaki_ja", "reload_failed_out_of_ammo_", loc_Tokisaki, "ja_loc_broker_male_b__reload_failed_out_of_ammo_", 3):add_subtext("巢都渣滓", {"该死，打光了！", "没子弹了！", "武器空了！"})
E:add_audio("broker", "Tokisaki_ja", "smart_tag_vo_pickup_health_booster_", loc_Tokisaki, "ja_loc_broker_male_b__smart_tag_vo_pickup_health_booster_", 2):add_subtext("巢都渣滓", {"有药！", "拿针！"})
E:add_audio("broker", "Tokisaki_ja", "smart_tag_vo_pickup_forge_metal_", loc_Tokisaki, "ja_loc_broker_male_b__smart_tag_vo_pickup_forge_metal_", 2):add_subtext("巢都渣滓", {"塑钢，能换点钱。", "捡破烂了。"})
E:add_audio("broker", "Tokisaki_ja", "smart_tag_vo_pickup_platinum_", loc_Tokisaki, "ja_loc_broker_male_b__smart_tag_vo_pickup_platinum_", 2):add_subtext("巢都渣滓", {"钻石金，好东西。", "发财了。"})
E:add_audio("broker", "Tokisaki_ja", "smart_tag_vo_pickup_small_grenade_", loc_Tokisaki, "ja_loc_broker_male_b__smart_tag_vo_pickup_small_grenade_", 3):add_subtext("巢都渣滓", {"手雷补给。", "这有雷。", "拿炸药。"})
E:add_audio("broker", "Tokisaki_ja", "cover_me_", loc_Tokisaki, "ja_loc_broker_male_b__cover_me_", 2):add_subtext("巢都渣滓", {"掩护我！", "给我火力掩护！"})
E:add_audio("broker", "Tokisaki_ja", "away_from_squad_", loc_Tokisaki, "ja_loc_broker_male_b__away_from_squad_", 4):add_subtext("巢都渣滓", {"我走远了。", "该死，离太远了。", "得回队伍去。", "落单了。"})
E:add_audio("broker", "Tokisaki_ja", "come_back_to_squad_", loc_Tokisaki, "ja_loc_broker_male_b__come_back_to_squad_", 4):add_subtext("巢都渣滓", {"快归队！", "别乱跑！", "回来！", "你想找死吗？快回来！"})
E:add_audio("broker", "Tokisaki_ja", "broker_seen_killstreak_psyker_", loc_Tokisaki, "ja_loc_broker_male_b__broker_seen_killstreak_psyker_", 6, 4):add_subtext("巢都渣滓", {"杀得好！", "留几个给我！", "干得漂亮！", "底巢风格！", "真残忍，我喜欢。", "继续杀！"}):set_priority(2)
E:add_audio("broker", "Tokisaki_ja", "broker_seen_killstreak_zealot_", loc_Tokisaki, "ja_loc_broker_male_b__broker_seen_killstreak_zealot_", 6, 4):add_subtext("巢都渣滓", {"杀得好！", "留几个给我！", "干得漂亮！", "底巢风格！", "真残忍，我喜欢。", "继续杀！"}):set_priority(2)
E:add_audio("broker", "Tokisaki_ja", "broker_seen_killstreak_veteran_", loc_Tokisaki, "ja_loc_broker_male_b__broker_seen_killstreak_veteran_", 6, 4):add_subtext("巢都渣滓", {"杀得好！", "留几个给我！", "干得漂亮！", "底巢风格！", "真残忍，我喜欢。", "继续杀！"}):set_priority(2)
E:add_audio("broker", "Tokisaki_ja", "broker_seen_killstreak_ogryn_", loc_Tokisaki, "ja_loc_broker_male_b__broker_seen_killstreak_ogryn_", 6, 4):add_subtext("巢都渣滓", {"杀得好！", "留几个给我！", "干得漂亮！", "底巢风格！", "真残忍，我喜欢。", "继续杀！"}):set_priority(2)
E:add_audio("broker", "Tokisaki_ja", "response_for_zealot_seen_killstreak_broker_", loc_Tokisaki, "ja_loc_broker_male_b__response_for_zealot_seen_killstreak_broker_", 6, 4):add_subtext("巢都渣滓", {"小菜一碟。", "别大惊小怪的。", "这就是巢都人的活法。", "我还没出力呢。", "离我远点。", "省点力气干活。"}):set_priority(2)
E:add_audio("broker", "Tokisaki_ja", "response_for_veteran_seen_killstreak_broker_", loc_Tokisaki, "ja_loc_broker_male_b__response_for_veteran_seen_killstreak_broker_", 6, 4):add_subtext("巢都渣滓", {"小菜一碟。", "别大惊小怪的。", "这就是巢都人的活法。", "我还没出力呢。", "离我远点。", "省点力气干活。"}):set_priority(2)
E:add_audio("broker", "Tokisaki_ja", "response_for_psyker_seen_killstreak_broker_", loc_Tokisaki, "ja_loc_broker_male_b__response_for_psyker_seen_killstreak_broker_", 6, 4):add_subtext("巢都渣滓", {"小菜一碟。", "别大惊小怪的。", "这就是巢都人的活法。", "我还没出力呢。", "离我远点。", "省点力气干活。"}):set_priority(2)
E:add_audio("broker", "Tokisaki_ja", "response_for_ogryn_seen_killstreak_broker_", loc_Tokisaki, "ja_loc_broker_male_b__response_for_ogryn_seen_killstreak_broker_", 6, 4):add_subtext("巢都渣滓", {"小菜一碟。", "别大惊小怪的。", "这就是巢都人的活法。", "我还没出力呢。", "离我远点。", "省点力气干活。"}):set_priority(2)
E:add_audio("broker", "Tokisaki_ja", "response_for_friendly_fire_from_zealot_", loc_Tokisaki, "ja_loc_broker_male_b__response_for_friendly_fire_from_zealot_", 4):add_subtext("巢都渣滓", {"长不长眼！", "别朝我开火！", "你想打一架吗！", "你看准点！"})
E:add_audio("broker", "Tokisaki_ja", "response_for_friendly_fire_from_veteran_", loc_Tokisaki, "ja_loc_broker_male_b__response_for_friendly_fire_from_veteran_", 4):add_subtext("巢都渣滓", {"长不长眼！", "别朝我开火！", "你想打一架吗！", "你看准点！"})
E:add_audio("broker", "Tokisaki_ja", "response_for_friendly_fire_from_psyker_", loc_Tokisaki, "ja_loc_broker_male_b__response_for_friendly_fire_from_psyker_", 4):add_subtext("巢都渣滓", {"长不长眼！", "别朝我开火！", "你想打一架吗！", "你看准点！"})
E:add_audio("broker", "Tokisaki_ja", "response_for_friendly_fire_from_ogryn_", loc_Tokisaki, "ja_loc_broker_male_b__response_for_friendly_fire_from_ogryn_", 4):add_subtext("巢都渣滓", {"长不长眼！", "别朝我开火！", "你想打一架吗！", "你看准点！"})
E:add_audio("broker", "Tokisaki_ja", "friendly_fire_from_zealot_to_broker_", loc_Tokisaki, "ja_loc_broker_male_b__friendly_fire_from_zealot_to_broker_", 2):add_subtext("巢都渣滓", {"你看准点！", "别打自己人！"})
E:add_audio("broker", "Tokisaki_ja", "friendly_fire_from_veteran_to_broker_", loc_Tokisaki, "ja_loc_broker_male_b__friendly_fire_from_veteran_to_broker_", 2):add_subtext("巢都渣滓", {"你看准点！", "别打自己人！"})
E:add_audio("broker", "Tokisaki_ja", "friendly_fire_from_psyker_to_broker_", loc_Tokisaki, "ja_loc_broker_male_b__friendly_fire_from_psyker_to_broker_", 2):add_subtext("巢都渣滓", {"你看准点！", "别打自己人！"})
E:add_audio("broker", "Tokisaki_ja", "friendly_fire_from_ogryn_to_broker_", loc_Tokisaki, "ja_loc_broker_male_b__friendly_fire_from_ogryn_to_broker_", 2):add_subtext("巢都渣滓", {"你看准点！", "别打自己人！"})
E:add_audio("broker", "Tokisaki_ja", "head_shot_", loc_Tokisaki, "ja_loc_broker_male_b__head_shot_", 5):add_subtext("巢都渣滓", {"爆头！", "脑浆爆了！", "好枪法！", "一发入魂！", "打得好！"})
E:add_audio("broker", "Tokisaki_ja", "response_for_zealot_disabled_by_enemy_", loc_Tokisaki, "ja_loc_broker_male_b__response_for_zealot_disabled_by_enemy_", 4):add_subtext("巢都渣滓", {"有人倒了！", "去把他拉起来！", "有个白痴躺了！", "救人！"})
E:add_audio("broker", "Tokisaki_ja", "response_for_veteran_disabled_by_enemy_", loc_Tokisaki, "ja_loc_broker_male_b__response_for_veteran_disabled_by_enemy_", 4):add_subtext("巢都渣滓", {"有人倒了！", "去把他拉起来！", "有个白痴躺了！", "救人！"})
E:add_audio("broker", "Tokisaki_ja", "response_for_psyker_disabled_by_enemy_", loc_Tokisaki, "ja_loc_broker_male_b__response_for_psyker_disabled_by_enemy_", 4):add_subtext("巢都渣滓", {"有人倒了！", "去把他拉起来！", "有个白痴躺了！", "救人！"})
E:add_audio("broker", "Tokisaki_ja", "response_for_ogryn_disabled_by_enemy_", loc_Tokisaki, "ja_loc_broker_male_b__response_for_ogryn_disabled_by_enemy_", 4):add_subtext("巢都渣滓", {"有人倒了！", "去把他拉起来！", "有个白痴躺了！", "救人！"})
E:add_audio("broker", "Tokisaki_ja", "broker_start_revive_ogryn_", loc_Tokisaki, "ja_loc_broker_male_b__broker_start_revive_ogryn_", 3):add_subtext("巢都渣滓", {"站起来！", "别躺着装死！", "快点起来干活！"})
E:add_audio("broker", "Tokisaki_ja", "broker_start_revive_zealot_", loc_Tokisaki, "ja_loc_broker_male_b__broker_start_revive_zealot_", 3):add_subtext("巢都渣滓", {"站起来！", "别躺着装死！", "快点起来干活！"})
E:add_audio("broker", "Tokisaki_ja", "broker_start_revive_veteran_", loc_Tokisaki, "ja_loc_broker_male_b__broker_start_revive_veteran_", 3):add_subtext("巢都渣滓", {"站起来！", "别躺着装死！", "快点起来干活！"})
E:add_audio("broker", "Tokisaki_ja", "broker_start_revive_psyker_", loc_Tokisaki, "ja_loc_broker_male_b__broker_start_revive_psyker_", 3):add_subtext("巢都渣滓", {"站起来！", "别躺着装死！", "快点起来干活！"})
E:add_audio("broker", "Tokisaki_ja", "combat_pause_quirk_sing_a_", loc_Tokisaki, "ja_loc_broker_male_b__combat_pause_quirk_sing_a_", 1):add_subtext("巢都渣滓", {"终于安静了。"})
E:add_audio("broker", "Tokisaki_ja", "combat_pause_one_liner_", loc_Tokisaki, "ja_loc_broker_male_b__combat_pause_one_liner_", 1):add_subtext("巢都渣滓", {"喘口气。"})
E:add_audio("broker", "Tokisaki_ja", "surrounded_", loc_Tokisaki, "ja_loc_broker_male_b__surrounded_", 6):add_subtext("巢都渣滓", {"包围了！", "到处都是！", "杀出去！", "该死，太多了！", "火力全开！", "我们被围了！"}):set_priority(2)
E:add_audio("broker", "Tokisaki_ja", "surrounded_response_", loc_Tokisaki, "ja_loc_broker_male_b__surrounded_response_", 3):add_subtext("巢都渣滓", {"别慌，杀就是了！", "跟他们拼了！", "杀出一条血路！"}):set_priority(2)
E:add_audio("broker", "Tokisaki_ja", "heard_horde_vector_", loc_Tokisaki, "ja_loc_broker_male_b__heard_horde_vector_", 6):add_subtext("巢都渣滓", {"有大群过来了！", "尸潮来了！", "准备接敌！", "听到那动静了吗！", "他们来了！", "抄家伙！"}):set_priority(2)
E:add_audio("broker", "Tokisaki_ja", "heard_horde_ambush_", loc_Tokisaki, "ja_loc_broker_male_b__heard_horde_ambush_", 3):add_subtext("巢都渣滓", {"伏击！", "他们从后面来了！", "小心周围！"}):set_priority(2)
E:add_audio("broker", "Tokisaki_ja", "heard_enemy_beast_of_nurgle_", loc_Tokisaki, "ja_loc_broker_male_b__heard_enemy_beast_of_nurgle_", 3):add_subtext("巢都渣滓", {"听见那大怪物的声音没？", "有个大家伙在附近！", "有大麻烦了！"})
E:add_audio("broker", "Tokisaki_ja", "heard_enemy_chaos_spawn_", loc_Tokisaki, "ja_loc_broker_male_b__heard_enemy_chaos_spawn_", 3):add_subtext("巢都渣滓", {"听见那大怪物的声音没？", "有个大家伙在附近！", "有大麻烦了！"})
E:add_audio("broker", "Tokisaki_ja", "heard_enemy_plague_ogryn_", loc_Tokisaki, "ja_loc_broker_male_b__heard_enemy_plague_ogryn_", 3):add_subtext("巢都渣滓", {"听见那大怪物的声音没？", "有个大家伙在附近！", "有大麻烦了！"})
E:add_audio("broker", "Tokisaki_ja", "conversation_plague_ogryn_weakpoint_01_", loc_Tokisaki, "ja_loc_broker_male_b__conversation_plague_ogryn_weakpoint_01_", 4):add_subtext("巢都渣滓", {"打它的弱点！", "瞄准发光的地方！", "打脑袋！", "攻击弱点！"})
E:add_audio("broker", "Tokisaki_ja", "conversation_beast_of_nurgle_weakpoint_a_", loc_Tokisaki, "ja_loc_broker_male_b__conversation_beast_of_nurgle_weakpoint_a_", 4):add_subtext("巢都渣滓", {"打它的弱点！", "瞄准发光的地方！", "打脑袋！", "攻击弱点！"})
E:add_audio("broker", "Tokisaki_ja", "conversation_beast_of_nurgle_weakpoint_c_", loc_Tokisaki, "ja_loc_broker_male_b__conversation_beast_of_nurgle_weakpoint_c_", 4):add_subtext("巢都渣滓", {"打它的弱点！", "瞄准发光的地方！", "打脑袋！", "攻击弱点！"})
E:add_audio("broker", "Tokisaki_ja", "seen_enemy_plague_ogryn_", loc_Tokisaki, "ja_loc_broker_male_b__seen_enemy_plague_ogryn_", 5):add_subtext("巢都渣滓", {"大家伙来了！", "那是啥鬼东西！", "杀掉那头野兽！", "集火大怪物！", "别让它靠近！"})
E:add_audio("broker", "Tokisaki_ja", "seen_enemy_beast_of_nurgle_", loc_Tokisaki, "ja_loc_broker_male_b__seen_enemy_beast_of_nurgle_", 5):add_subtext("巢都渣滓", {"大家伙来了！", "那是啥鬼东西！", "杀掉那头野兽！", "集火大怪物！", "别让它靠近！"})
E:add_audio("broker", "Tokisaki_ja", "seen_enemy_chaos_spawn_", loc_Tokisaki, "ja_loc_broker_male_b__seen_enemy_chaos_spawn_", 5):add_subtext("巢都渣滓", {"大家伙来了！", "那是啥鬼东西！", "杀掉那头野兽！", "集火大怪物！", "别让它靠近！"})
E:add_audio("broker", "Tokisaki_ja", "smart_tag_vo_enemy_chaos_spawn_a_", loc_Tokisaki, "ja_loc_broker_male_b__smart_tag_vo_enemy_chaos_spawn_a_", 4):add_subtext("巢都渣滓", {"集火那怪物！", "打大个子！", "杀那头野兽！", "干掉它！"})
E:add_audio("broker", "Tokisaki_ja", "smart_tag_vo_enemy_chaos_spawn_b_", loc_Tokisaki, "ja_loc_broker_male_b__smart_tag_vo_enemy_chaos_spawn_b_", 4):add_subtext("巢都渣滓", {"集火那怪物！", "打大个子！", "杀那头野兽！", "干掉它！"})
E:add_audio("broker", "Tokisaki_ja", "smart_tag_vo_enemy_beast_of_nurgle_", loc_Tokisaki, "ja_loc_broker_male_b__smart_tag_vo_enemy_beast_of_nurgle_", 4):add_subtext("巢都渣滓", {"集火那怪物！", "打大个子！", "杀那头野兽！", "干掉它！"})
E:add_audio("broker", "Tokisaki_ja", "smart_tag_vo_enemy_plague_ogryn_", loc_Tokisaki, "ja_loc_broker_male_b__smart_tag_vo_enemy_plague_ogryn_", 4):add_subtext("巢都渣滓", {"集火那怪物！", "打大个子！", "杀那头野兽！", "干掉它！"})
E:add_audio("broker", "Tokisaki_ja", "heard_enemy_daemonhost_", loc_Tokisaki, "ja_loc_broker_male_b__heard_enemy_daemonhost_", 1):add_subtext("巢都渣滓", {"有恶魔宿主，都闭嘴！"})
E:add_audio("broker", "Tokisaki_ja", "seen_enemy_daemonhost_", loc_Tokisaki, "ja_loc_broker_male_b__seen_enemy_daemonhost_", 1):add_subtext("巢都渣滓", {"别惊动那恶魔！"})
E:add_audio("broker", "Tokisaki_ja", "alerted_ememy_daemonhost_", loc_Tokisaki, "ja_loc_broker_male_b__alerted_ememy_daemonhost_", 2):add_subtext("巢都渣滓", {"谁惊动了恶魔！", "完了，它醒了！"})
E:add_audio("broker", "Tokisaki_ja", "smart_tag_vo_enemy_daemonhost_", loc_Tokisaki, "ja_loc_broker_male_b__smart_tag_vo_enemy_daemonhost_", 2):add_subtext("巢都渣滓", {"集火恶魔！", "打恶魔宿主！"})
E:add_audio("broker", "Tokisaki_ja", "monster_fight_start_reaction_", loc_Tokisaki, "ja_loc_broker_male_b__monster_fight_start_reaction_", 4, 4):add_subtext("巢都渣滓", {"送它下地狱！", "火力全开！", "把它打成筛子！", "拼了！"}):set_priority(2)
E:add_audio("broker", "Tokisaki_ja", "enemy_near_death_monster_", loc_Tokisaki, "ja_loc_broker_male_b__enemy_near_death_monster_", 2, 4):add_subtext("巢都渣滓", {"它快死了！", "再给它两枪！"}):set_priority(2)
E:add_audio("broker", "Tokisaki_ja", "enemy_kill_monster_", loc_Tokisaki, "ja_loc_broker_male_b__enemy_kill_monster_", 2, 3):add_subtext("巢都渣滓", {"怪物死了！", "呸，一滩烂肉。"}):set_priority(2)
E:add_audio("broker", "Tokisaki_ja", "heard_enemy_chaos_hound_", loc_Tokisaki, "ja_loc_broker_male_b__heard_enemy_chaos_hound_", 5):add_subtext("巢都渣滓", {"有狗！", "听见狗叫了！", "猎犬在附近！", "注意疯狗！", "别被狗扑了！"})
E:add_audio("broker", "Tokisaki_ja", "seen_enemy_chaos_hound_", loc_Tokisaki, "ja_loc_broker_male_b__seen_enemy_chaos_hound_", 4):add_subtext("巢都渣滓", {"疯狗来了！", "打死那条狗！", "猎犬！", "射那条狗！"})
E:add_audio("broker", "Tokisaki_ja", "smart_tag_vo_enemy_chaos_hound_", loc_Tokisaki, "ja_loc_broker_male_b__smart_tag_vo_enemy_chaos_hound_", 4):add_subtext("巢都渣滓", {"猎犬！", "打狗！", "在这！", "看那条狗！"})
E:add_audio("broker", "Tokisaki_ja", "enemy_kill_chaos_hound_", loc_Tokisaki, "ja_loc_broker_male_b__enemy_kill_chaos_hound_", 5):add_subtext("巢都渣滓", {"狗死了！", "死狗一条。", "干掉猎犬了。", "好狗不挡道。", "解决了。"})
E:add_audio("broker", "Tokisaki_ja", "seen_netgunner_", loc_Tokisaki, "ja_loc_broker_male_b__seen_netgunner_", 4):add_subtext("巢都渣滓", {"发现陷阱捕手！", "陷阱捕手来袭！", "陷阱捕手现身！", "陷阱捕手出现了！"})
E:add_audio("broker", "Tokisaki_ja", "seen_netgunner_flee_", loc_Tokisaki, "ja_loc_broker_male_b__seen_netgunner_flee_", 2):add_subtext("巢都渣滓", {"别让它跑了！", "它想逃！"})
E:add_audio("broker", "Tokisaki_ja", "smart_tag_vo_enemy_netgunner_", loc_Tokisaki, "ja_loc_broker_male_b__smart_tag_vo_enemy_netgunner_", 3):add_subtext("巢都渣滓", {"陷阱捕手！", "打陷阱捕手！", "注意那家伙！"})
E:add_audio("broker", "Tokisaki_ja", "enemy_kill_netgunner_", loc_Tokisaki, "ja_loc_broker_male_b__enemy_kill_netgunner_", 6):add_subtext("巢都渣滓", {"干掉了！", "下地狱去吧！", "解决一个麻烦。", "变成烂肉吧！", "死不足惜！", "不堪一击！"})
E:add_audio("broker", "Tokisaki_ja", "seen_enemy_mutant_charger_", loc_Tokisaki, "ja_loc_broker_male_b__seen_enemy_mutant_charger_", 4):add_subtext("巢都渣滓", {"发现变种人！", "看到了，是变种人！", "那有变种人！", "变种人出现了！"})
E:add_audio("broker", "Tokisaki_ja", "smart_tag_vo_enemy_chaos_mutant_charger_", loc_Tokisaki, "ja_loc_broker_male_b__smart_tag_vo_enemy_chaos_mutant_charger_", 5):add_subtext("巢都渣滓", {"变种人！", "变种人来袭！", "变种人在那儿！", "凶猛的变种人来袭！", "打那个变种人！"})
E:add_audio("broker", "Tokisaki_ja", "enemy_kill_mutant_charger_", loc_Tokisaki, "ja_loc_broker_male_b__enemy_kill_mutant_charger_", 6):add_subtext("巢都渣滓", {"干掉了！", "下地狱去吧！", "解决一个麻烦。", "变成烂肉吧！", "死不足惜！", "不堪一击！"})
E:add_audio("broker", "Tokisaki_ja", "heard_enemy_poxwalker_bomber_", loc_Tokisaki, "ja_loc_broker_male_b__heard_enemy_poxwalker_bomber_", 4):add_subtext("巢都渣滓", {"炸弹人正在逼近。", "炸弹人在附近，小心。", "附近有炸弹人。", "我听到炸药引信的声音了。"})
E:add_audio("broker", "Tokisaki_ja", "seen_enemy_poxwalker_bomber_", loc_Tokisaki, "ja_loc_broker_male_b__seen_enemy_poxwalker_bomber_", 4):add_subtext("巢都渣滓", {"发现炸弹人！", "炸弹人来袭！", "看到了，是炸弹人！", "那儿有个炸弹人！"})
E:add_audio("broker", "Tokisaki_ja", "smart_tag_vo_enemy_chaos_poxwalker_bomber_", loc_Tokisaki, "ja_loc_broker_male_b__smart_tag_vo_enemy_chaos_poxwalker_bomber_", 5):add_subtext("巢都渣滓", {"炸弹人！", "疯狂的炸弹人！", "炸弹人逼近！", "离那家伙远点！", "是炸弹人，远离它！"})
E:add_audio("broker", "Tokisaki_ja", "enemy_kill_poxwalker_bomber_", loc_Tokisaki, "ja_loc_broker_male_b__enemy_kill_poxwalker_bomber_", 6):add_subtext("巢都渣滓", {"干掉了！", "下地狱去吧！", "解决一个麻烦。", "变成烂肉吧！", "死不足惜！", "不堪一击！"})
E:add_audio("broker", "Tokisaki_ja", "smart_tag_vo_enemy_scab_flamer_a_", loc_Tokisaki, "ja_loc_broker_male_b__smart_tag_vo_enemy_scab_flamer_a_", 3):add_subtext("巢都渣滓", {"火焰兵！", "火焰兵来袭！", "火焰兵来袭，小心！"})
E:add_audio("broker", "Tokisaki_ja", "smart_tag_vo_tox_flamer_", loc_Tokisaki, "ja_loc_broker_male_b__smart_tag_vo_tox_flamer_", 3):add_subtext("巢都渣滓", {"火焰兵！", "火焰兵来袭！", "火焰兵来袭，小心！"})
E:add_audio("broker", "Tokisaki_ja", "seen_enemy_tox_flamer_", loc_Tokisaki, "ja_loc_broker_male_b__seen_enemy_tox_flamer_", 2):add_subtext("巢都渣滓", {"发现火焰兵！", "火焰兵现身！"})
E:add_audio("broker", "Tokisaki_ja", "seen_enemy_scab_flamer_a_", loc_Tokisaki, "ja_loc_broker_male_b__seen_enemy_scab_flamer_a_", 2):add_subtext("巢都渣滓", {"发现火焰兵！", "火焰兵现身！"})
E:add_audio("broker", "Tokisaki_ja", "enemy_kill_tox_flamer_", loc_Tokisaki, "ja_loc_broker_male_b__enemy_kill_tox_flamer_", 6):add_subtext("巢都渣滓", {"干掉了！", "下地狱去吧！", "解决一个麻烦。", "变成烂肉吧！", "死不足惜！", "不堪一击！"})
E:add_audio("broker", "Tokisaki_ja", "enemy_kill_scab_flamer_a_", loc_Tokisaki, "ja_loc_broker_male_b__enemy_kill_scab_flamer_a_", 6):add_subtext("巢都渣滓", {"干掉了！", "下地狱去吧！", "解决一个麻烦。", "变成烂肉吧！", "死不足惜！", "不堪一击！"})
E:add_audio("broker", "Tokisaki_ja", "seen_enemy_traitor_grenadier_", loc_Tokisaki, "ja_loc_broker_male_b__seen_enemy_traitor_grenadier_", 4):add_subtext("巢都渣滓", {"掷弹兵现身！", "看到个掷弹兵！", "那有个掷弹兵！", "掷弹兵在那里！"})
E:add_audio("broker", "Tokisaki_ja", "smart_tag_vo_enemy_traitor_grenadier_", loc_Tokisaki, "ja_loc_broker_male_b__smart_tag_vo_enemy_traitor_grenadier_", 4):add_subtext("巢都渣滓", {"掷弹兵！", "标记到掷弹兵了！", "消灭那个掷弹兵！", "阻止那个家伙！"})
E:add_audio("broker", "Tokisaki_ja", "enemy_kill_traitor_grenadier_", loc_Tokisaki, "ja_loc_broker_male_b__enemy_kill_traitor_grenadier_", 6):add_subtext("巢都渣滓", {"干掉了！", "下地狱去吧！", "解决一个麻烦。", "变成烂肉吧！", "死不足惜！", "不堪一击！"})
E:add_audio("broker", "Tokisaki_ja", "seen_enemy_cultist_grenadier_", loc_Tokisaki, "ja_loc_broker_male_b__seen_enemy_cultist_grenadier_", 4):add_subtext("巢都渣滓", {"掷弹兵现身！", "看到个掷弹兵！", "那有个掷弹兵！", "掷弹兵在那里！"})
E:add_audio("broker", "Tokisaki_ja", "smart_tag_vo_enemy_cultist_grenadier_", loc_Tokisaki, "ja_loc_broker_male_b__smart_tag_vo_enemy_cultist_grenadier_", 4):add_subtext("巢都渣滓", {"掷弹兵！", "标记到掷弹兵了！", "消灭那个掷弹兵！", "阻止那个家伙！"})
E:add_audio("broker", "Tokisaki_ja", "enemy_kill_grenadier_", loc_Tokisaki, "ja_loc_broker_male_b__enemy_kill_grenadier_", 6):add_subtext("巢都渣滓", {"干掉了！", "下地狱去吧！", "解决一个麻烦。", "变成烂肉吧！", "死不足惜！", "不堪一击！"})
E:add_audio("broker", "Tokisaki_ja", "smart_tag_vo_enemy_traitor_sniper_", loc_Tokisaki, "ja_loc_broker_male_b__smart_tag_vo_enemy_traitor_sniper_", 3):add_subtext("巢都渣滓", {"狙击手！", "是狙击手，注意！", "标记到狙击手了！"})
E:add_audio("broker", "Tokisaki_ja", "seen_enemy_sniper_", loc_Tokisaki, "ja_loc_broker_male_b__seen_enemy_sniper_", 3):add_subtext("巢都渣滓", {"有狙击手，小心点！", "发现狙击手！", "有狙击手在瞄准！"})
E:add_audio("broker", "Tokisaki_ja", "enemy_kill_sniper_a_", loc_Tokisaki, "ja_loc_broker_male_b__enemy_kill_sniper_a_", 6):add_subtext("巢都渣滓", {"干掉了！", "下地狱去吧！", "解决一个麻烦。", "变成烂肉吧！", "死不足惜！", "不堪一击！"})
E:add_audio("broker", "Tokisaki_ja", "seen_enemy_traitor_gunner_", loc_Tokisaki, "ja_loc_broker_male_b__seen_enemy_traitor_gunner_", 4):add_subtext("巢都渣滓", {"发现机枪手！", "看到机枪手了！", "机枪手在那！", "机枪手出现了！"})
E:add_audio("broker", "Tokisaki_ja", "smart_tag_vo_enemy_traitor_gunner_", loc_Tokisaki, "ja_loc_broker_male_b__smart_tag_vo_enemy_traitor_gunner_", 4):add_subtext("巢都渣滓", {"机枪手！", "那有个机枪手！", "机枪手在那儿！", "干掉那机枪手！"})
E:add_audio("broker", "Tokisaki_ja", "seen_enemy_cultist_holy_stubber_gunner_", loc_Tokisaki, "ja_loc_broker_male_b__seen_enemy_cultist_holy_stubber_gunner_", 4):add_subtext("巢都渣滓", {"发现机枪手！", "看到机枪手了！", "机枪手在那！", "机枪手出现了！"})
E:add_audio("broker", "Tokisaki_ja", "smart_tag_vo_enemy_cultist_holy_stubber_gunner_", loc_Tokisaki, "ja_loc_broker_male_b__smart_tag_vo_enemy_cultist_holy_stubber_gunner_", 4):add_subtext("巢都渣滓", {"机枪手！", "那有个机枪手！", "机枪手在那儿！", "干掉那机枪手！"})
E:add_audio("broker", "Tokisaki_ja", "seen_enemy_heavy_gunner_", loc_Tokisaki, "ja_loc_broker_male_b__seen_enemy_heavy_gunner_", 4):add_subtext("巢都渣滓", {"发现机枪手！", "看到机枪手了！", "机枪手在那！", "机枪手出现了！"})
E:add_audio("broker", "Tokisaki_ja", "smart_tag_vo_enemy_heavy_gunner_", loc_Tokisaki, "ja_loc_broker_male_b__smart_tag_vo_enemy_heavy_gunner_", 4):add_subtext("巢都渣滓", {"机枪手！", "那有个机枪手！", "机枪手在那儿！", "干掉那机枪手！"})
E:add_audio("broker", "Tokisaki_ja", "seen_enemy_shocktrooper_", loc_Tokisaki, "ja_loc_broker_male_b__seen_enemy_shocktrooper_", 4):add_subtext("巢都渣滓", {"发现霰弹枪手！", "霰弹枪手出现了，小心点！", "霰弹枪手出现了！", "那有个霰弹枪手！"})
E:add_audio("broker", "Tokisaki_ja", "smart_tag_vo_enemy_traitor_scout_shocktrooper_", loc_Tokisaki, "ja_loc_broker_male_b__smart_tag_vo_enemy_traitor_scout_shocktrooper_", 4):add_subtext("巢都渣滓", {"霰弹枪手！", "霰弹枪手来袭！", "注意，是霰弹枪手！", "是霰弹枪手，小心点！"})
E:add_audio("broker", "Tokisaki_ja", "seen_enemy_cultist_shocktrooper_", loc_Tokisaki, "ja_loc_broker_male_b__seen_enemy_cultist_shocktrooper_", 4):add_subtext("巢都渣滓", {"发现霰弹枪手！", "霰弹枪手出现了，小心点！", "霰弹枪手出现了！", "那有个霰弹枪手！"})
E:add_audio("broker", "Tokisaki_ja", "smart_tag_vo_enemy_cultist_shocktrooper_", loc_Tokisaki, "ja_loc_broker_male_b__smart_tag_vo_enemy_cultist_shocktrooper_", 4):add_subtext("巢都渣滓", {"霰弹枪手！", "霰弹枪手来袭！", "注意，是霰弹枪手！", "是霰弹枪手，小心点！"})
E:add_audio("broker", "Tokisaki_ja", "seen_enemy_executor_", loc_Tokisaki, "ja_loc_broker_male_b__seen_enemy_executor_", 4):add_subtext("巢都渣滓", {"发现重锤兵！", "重锤兵出现了！", "重锤兵来袭！", "发现重锤兵了！"})
E:add_audio("broker", "Tokisaki_ja", "smart_tag_vo_enemy_traitor_executor_", loc_Tokisaki, "ja_loc_broker_male_b__smart_tag_vo_enemy_traitor_executor_", 4):add_subtext("巢都渣滓", {"重锤兵！", "小心那个重锤兵！", "重锤兵来了！", "重锤兵袭来！"})
E:add_audio("broker", "Tokisaki_ja", "smart_tag_vo_enemy_chaos_ogryn_bulwark_", loc_Tokisaki, "ja_loc_broker_male_b__smart_tag_vo_enemy_chaos_ogryn_bulwark_", 3):add_subtext("巢都渣滓", {"盾卫逼近！", "那有个盾卫！", "是盾卫，注意！"})
E:add_audio("broker", "Tokisaki_ja", "seen_enemy_bulwark_", loc_Tokisaki, "ja_loc_broker_male_b__seen_enemy_bulwark_", 3):add_subtext("巢都渣滓", {"发现盾卫！", "盾卫来袭！", "看到盾卫了！"})
E:add_audio("broker", "Tokisaki_ja", "seen_enemy_chaos_ogryn_armored_executor_", loc_Tokisaki, "ja_loc_broker_male_b__seen_enemy_chaos_ogryn_armored_executor_", 4):add_subtext("巢都渣滓", {"是粉碎者，注意！", "那有粉碎者！", "粉碎者出现了！", "警告，粉碎者出现了！"})
E:add_audio("broker", "Tokisaki_ja", "smart_tag_vo_enemy_chaos_ogryn_armored_executor_", loc_Tokisaki, "ja_loc_broker_male_b__smart_tag_vo_enemy_chaos_ogryn_armored_executor_", 4):add_subtext("巢都渣滓", {"粉碎者！", "标记到粉碎者！", "粉碎者来袭！", "粉碎者过来了！"})
E:add_audio("broker", "Tokisaki_ja", "seen_enemy_chaos_ogryn_heavy_gunner_", loc_Tokisaki, "ja_loc_broker_male_b__seen_enemy_chaos_ogryn_heavy_gunner_", 4):add_subtext("巢都渣滓", {"收割者现身！", "看到收割者了", "那有个收割者！", "看到了，是收割者！"})
E:add_audio("broker", "Tokisaki_ja", "smart_tag_vo_enemy_chaos_ogryn_heavy_gunner_", loc_Tokisaki, "ja_loc_broker_male_b__smart_tag_vo_enemy_chaos_ogryn_heavy_gunner_", 4):add_subtext("巢都渣滓", {"收割者！", "是收割者，注意！", "那有个收割者！", "标记到收割者！"})
E:add_audio("broker", "Tokisaki_ja", "seen_enemy_berserker_", loc_Tokisaki, "ja_loc_broker_male_b__seen_enemy_berserker_", 4):add_subtext("巢都渣滓", {"狂战士现身！", "发现狂战士！", "看到了，是狂战士！", "那有个狂战士！"})
E:add_audio("broker", "Tokisaki_ja", "smart_tag_vo_enemy_berserker_", loc_Tokisaki, "ja_loc_broker_male_b__smart_tag_vo_enemy_berserker_", 4):add_subtext("巢都渣滓", {"狂战士！", "是狂战士，小心点！", "凶猛的狂战士！", "狂战士来袭！"})
E:add_audio("broker", "Tokisaki_ja", "enemy_kill_berserker_", loc_Tokisaki, "ja_loc_broker_male_b__enemy_kill_berserker_", 6):add_subtext("巢都渣滓", {"干掉了！", "下地狱去吧！", "解决一个麻烦。", "变成烂肉吧！", "死不足惜！", "不堪一击！"})
E:add_audio("broker", "Tokisaki_ja", "enemy_kill_berserker_ext_03_c_", loc_Tokisaki, "ja_loc_broker_male_b__enemy_kill_berserker_ext_03_c_", 6):add_subtext("巢都渣滓", {"干掉了！", "下地狱去吧！", "解决一个麻烦。", "变成烂肉吧！", "死不足惜！", "不堪一击！"})
E:add_audio("broker", "Tokisaki_ja", "seen_enemy_group_far_range_shooting_behind_cover_", loc_Tokisaki, "ja_loc_broker_male_b__seen_enemy_group_far_range_shooting_behind_cover_", 1):add_subtext("巢都渣滓", {"他们在掩体后！把他们轰出来！"})
E:add_audio("broker", "Tokisaki_ja", "seen_enemy_group_assaulting_", loc_Tokisaki, "ja_loc_broker_male_b__seen_enemy_group_assaulting_", 1):add_subtext("巢都渣滓", {"他们冲过来了！开火！"})
E:add_audio("broker", "Tokisaki_ja", "quick_agnostic_enemy_kill_a_", loc_Tokisaki, "ja_loc_broker_male_b__quick_agnostic_enemy_kill_a_", 5, 4):add_subtext("巢都渣滓", {"去死！", "渣滓！", "干掉一个。", "别挡道！", "下地狱吧！"}):set_priority(2)
E:add_audio("broker", "Tokisaki_ja", "player_tip_armor_hit_generic_", loc_Tokisaki, "ja_loc_broker_male_b__player_tip_armor_hit_generic_", 4):add_subtext("巢都渣滓", {"打不穿，换弱点！", "护甲太厚了！", "别打硬壳！", "换个角度打！"})
E:add_audio("broker", "Tokisaki_ja", "event_kill_tareget_damaged_", loc_Tokisaki, "ja_loc_broker_male_b__event_kill_tareget_damaged_", 1):add_subtext("巢都渣滓", {"重创目标！"})
E:add_audio("broker", "Tokisaki_ja", "event_kill_target_heavy_damage_a_", loc_Tokisaki, "ja_loc_broker_male_b__event_kill_target_heavy_damage_a_", 1):add_subtext("巢都渣滓", {"重创目标，继续！"})
E:add_audio("broker", "Tokisaki_ja", "event_kill_target_destroyed_a_", loc_Tokisaki, "ja_loc_broker_male_b__event_kill_target_destroyed_a_", 1):add_subtext("巢都渣滓", {"目标碎了，完事。"})
E:add_audio("broker", "Tokisaki_ja", "guidance_switch_", loc_Tokisaki, "ja_loc_broker_male_b__guidance_switch_", 3):add_subtext("巢都渣滓", {"找到开关了。", "这里有门可以进去。", "开关在这儿。"})
E:add_audio("broker", "Tokisaki_ja", "luggable_mission_pick_up_", loc_Tokisaki, "ja_loc_broker_male_b__luggable_mission_pick_up_", 1):add_subtext("巢都渣滓", {"这破玩意真重。"})
E:add_audio("broker", "Tokisaki_ja", "critical_health_", loc_Tokisaki, "ja_loc_broker_male_b__critical_health_", 2, 6):add_subtext("巢都渣滓", {"我快不行了...", "该死，我要死了..."}):set_priority(1)
E:add_audio("broker", "Tokisaki_ja", "smart_tag_stimm_power_a_", loc_Tokisaki, "ja_loc_broker_male_b__smart_tag_stimm_power_a_", 4):add_subtext("巢都渣滓", {"力量药剂！", "红针！", "战斗药剂！", "好东西！"})
E:add_audio("broker", "Tokisaki_ja", "smart_tag_stimm_speed_a_", loc_Tokisaki, "ja_loc_broker_male_b__smart_tag_stimm_speed_a_", 4):add_subtext("巢都渣滓", {"速度药剂！", "蓝针！", "敏捷针剂！", "加速！"})
E:add_audio("broker", "Tokisaki_ja", "smart_tag_stimm_concentration_a_", loc_Tokisaki, "ja_loc_broker_male_b__smart_tag_stimm_concentration_a_", 4):add_subtext("巢都渣滓", {"专注药剂！", "黄针！", "技能药剂！", "好东西！"})
E:add_audio("broker", "Tokisaki_ja", "smart_tag_vo_small_grenade_", loc_Tokisaki, "ja_loc_broker_male_b__smart_tag_vo_small_grenade_", 3):add_subtext("巢都渣滓", {"这有颗手雷。", "这有手雷补给哟。", "这里有炸弹补给。"})
E:add_audio("broker", "Tokisaki_ja", "calling_for_help_", loc_Tokisaki, "ja_loc_broker_male_b__calling_for_help_", 3):add_subtext("巢都渣滓", {"拉我一把！", "救命！", "该死，快来帮忙！"})
E:add_audio("broker", "Tokisaki_ja", "response_for_calling_for_help_", loc_Tokisaki, "ja_loc_broker_male_b__response_for_calling_for_help_", 3):add_subtext("巢都渣滓", {"撑住！", "来了来了！", "别死了！"})
E:add_audio("broker", "Tokisaki_ja", "response_for_zealot_critical_health_", loc_Tokisaki, "ja_loc_broker_male_b__response_for_zealot_critical_health_", 1):add_subtext("巢都渣滓", {"你看上去快死了！"})
E:add_audio("broker", "Tokisaki_ja", "response_for_veteran_critical_health_", loc_Tokisaki, "ja_loc_broker_male_b__response_for_veteran_critical_health_", 1):add_subtext("巢都渣滓", {"你看上去快死了！"})
E:add_audio("broker", "Tokisaki_ja", "response_for_psyker_critical_health_", loc_Tokisaki, "ja_loc_broker_male_b__response_for_psyker_critical_health_", 1):add_subtext("巢都渣滓", {"你看上去快死了！"})
E:add_audio("broker", "Tokisaki_ja", "response_for_ogryn_critical_health_", loc_Tokisaki, "ja_loc_broker_male_b__response_for_ogryn_critical_health_", 1):add_subtext("巢都渣滓", {"你看上去快死了！"})
E:add_audio("broker", "Tokisaki_ja", "knocked_down_multiple_times_zealot_", loc_Tokisaki, "ja_loc_broker_male_b__knocked_down_multiple_times_zealot_", 4):add_subtext("巢都渣滓", {"有人被按在地上了！", "快去救他！", "有个白痴被抓了！", "去帮他！"})
E:add_audio("broker", "Tokisaki_ja", "knocked_down_multiple_times_veteran_", loc_Tokisaki, "ja_loc_broker_male_b__knocked_down_multiple_times_veteran_", 4):add_subtext("巢都渣滓", {"有人被按在地上了！", "快去救他！", "有个白痴被抓了！", "去帮他！"})
E:add_audio("broker", "Tokisaki_ja", "knocked_down_multiple_times_psyker_", loc_Tokisaki, "ja_loc_broker_male_b__knocked_down_multiple_times_psyker_", 4):add_subtext("巢都渣滓", {"有人被按在地上了！", "快去救他！", "有个白痴被抓了！", "去帮他！"})
E:add_audio("broker", "Tokisaki_ja", "knocked_down_multiple_times_ogryn_", loc_Tokisaki, "ja_loc_broker_male_b__knocked_down_multiple_times_ogryn_", 4):add_subtext("巢都渣滓", {"有人被按在地上了！", "快去救他！", "有个白痴被抓了！", "去帮他！"})
E:add_audio("broker", "Tokisaki_ja", "player_death_zealot_", loc_Tokisaki, "ja_loc_broker_male_b__player_death_zealot_", 2):add_subtext("巢都渣滓", {"有人挂了！", "减员了！"})
E:add_audio("broker", "Tokisaki_ja", "player_death_veteran_", loc_Tokisaki, "ja_loc_broker_male_b__player_death_veteran_", 2):add_subtext("巢都渣滓", {"有人挂了！", "减员了！"})
E:add_audio("broker", "Tokisaki_ja", "player_death_psyker_", loc_Tokisaki, "ja_loc_broker_male_b__player_death_psyker_", 2):add_subtext("巢都渣滓", {"有人挂了！", "减员了！"})
E:add_audio("broker", "Tokisaki_ja", "player_death_ogryn_", loc_Tokisaki, "ja_loc_broker_male_b__player_death_ogryn_", 2):add_subtext("巢都渣滓", {"有人挂了！", "减员了！"})
E:add_audio("broker", "Tokisaki_ja", "pinned_by_enemies_", loc_Tokisaki, "ja_loc_broker_male_b__pinned_by_enemies_", 4):add_subtext("巢都渣滓", {"火力太猛了！", "找掩护！", "躲起来！", "压制火力！"})
E:add_audio("broker", "Tokisaki_ja", "response_for_pinned_by_enemies_zealot_", loc_Tokisaki, "ja_loc_broker_male_b__response_for_pinned_by_enemies_zealot_", 4):add_subtext("巢都渣滓", {"躲好！", "别露头！", "进掩体！", "别犯傻！"})
E:add_audio("broker", "Tokisaki_ja", "response_for_pinned_by_enemies_veteran_", loc_Tokisaki, "ja_loc_broker_male_b__response_for_pinned_by_enemies_veteran_", 4):add_subtext("巢都渣滓", {"躲好！", "别露头！", "进掩体！", "别犯傻！"})
E:add_audio("broker", "Tokisaki_ja", "response_for_pinned_by_enemies_psyker_", loc_Tokisaki, "ja_loc_broker_male_b__response_for_pinned_by_enemies_psyker_", 4):add_subtext("巢都渣滓", {"躲好！", "别露头！", "进掩体！", "别犯傻！"})
E:add_audio("broker", "Tokisaki_ja", "response_for_pinned_by_enemies_ogryn_", loc_Tokisaki, "ja_loc_broker_male_b__response_for_pinned_by_enemies_ogryn_", 4):add_subtext("巢都渣滓", {"躲好！", "别露头！", "进掩体！", "别犯傻！"})
E:add_audio("broker", "Tokisaki_ja", "response_for_zealot_cover_me_", loc_Tokisaki, "ja_loc_broker_male_b__response_for_zealot_cover_me_", 4):add_subtext("巢都渣滓", {"掩护你！", "我看着呢！", "开火压制！", "上吧！"})
E:add_audio("broker", "Tokisaki_ja", "response_for_veteran_cover_me_", loc_Tokisaki, "ja_loc_broker_male_b__response_for_veteran_cover_me_", 4):add_subtext("巢都渣滓", {"掩护你！", "我看着呢！", "开火压制！", "上吧！"})
E:add_audio("broker", "Tokisaki_ja", "response_for_psyker_cover_me_", loc_Tokisaki, "ja_loc_broker_male_b__response_for_psyker_cover_me_", 4):add_subtext("巢都渣滓", {"掩护你！", "我看着呢！", "开火压制！", "上吧！"})
E:add_audio("broker", "Tokisaki_ja", "response_for_ogryn_cover_me_", loc_Tokisaki, "ja_loc_broker_male_b__response_for_ogryn_cover_me_", 4):add_subtext("巢都渣滓", {"掩护你！", "我看着呢！", "开火压制！", "上吧！"})
E:add_audio("broker", "Tokisaki_ja", "conversation_combat_chaos_spawn_chew_a_", loc_Tokisaki, "ja_loc_broker_male_b__conversation_combat_chaos_spawn_chew_a_", 4):add_subtext("巢都渣滓", {"把它打下来！", "救人！", "集火怪物！", "打断它！"})
E:add_audio("broker", "Tokisaki_ja", "conversation_combat_chaos_spawn_chew_b_", loc_Tokisaki, "ja_loc_broker_male_b__conversation_combat_chaos_spawn_chew_b_", 4):add_subtext("巢都渣滓", {"把它打下来！", "救人！", "集火怪物！", "打断它！"})
E:add_audio("broker", "Tokisaki_ja", "conversation_combat_chaos_spawn_chew_c_", loc_Tokisaki, "ja_loc_broker_male_b__conversation_combat_chaos_spawn_chew_c_", 4):add_subtext("巢都渣滓", {"把它打下来！", "救人！", "集火怪物！", "打断它！"})
E:add_audio("broker", "Tokisaki_ja", "vce_hurt_heavy", play_Tokisaki, "play_broker_male_b__vce_hurt_heavy", 2):set_priority(1)
E:add_audio("broker", "Tokisaki_ja", "vce_catapulted", play_Tokisaki, "play_broker_male_b__vce_catapulted", 1):set_priority(2)
E:add_audio("broker", "Tokisaki_ja", "vce_catapulted_land", play_Tokisaki, "play_broker_male_b__vce_catapulted_land", 1):set_priority(4)
E:add_audio("broker", "Tokisaki_ja", "vce_scream_long", play_Tokisaki, "play_broker_male_b__vce_scream_long", 1):set_priority(2)
E:add_audio("broker", "Tokisaki_ja", "vce_hurt_light", play_Tokisaki, "play_broker_male_b__vce_hurt_light", 3):set_priority(4)
E:add_audio("broker", "Tokisaki_ja", "vce_jump", play_Tokisaki, "play_broker_male_b__vce_jump", 1):set_priority(4)
E:add_audio("broker", "Tokisaki_ja", "vce_land_heavy", play_Tokisaki, "play_broker_male_b__vce_land_heavy", 1):set_priority(4)
E:add_audio("broker", "Tokisaki_ja", "vce_grunt_short", play_Tokisaki, "play_broker_male_b__vce_grunt_short", 1):set_priority(4)
E:add_audio("broker", "Tokisaki_ja", "vce_attack_short", play_Tokisaki, "play_broker_male_b__vce_attack_short", 1):set_priority(4)
E:add_audio("broker", "Tokisaki_ja", "vce_attack_long", play_Tokisaki, "play_broker_male_b__vce_attack_long", 5):set_priority(4)
E:add_audio("broker", "Tokisaki_ja", "vce_coughing", play_Tokisaki, "play_broker_male_b__vce_coughing", 1):set_priority(4)
E:add_audio("broker", "Tokisaki_ja", "vce_getting_up", play_Tokisaki, "play_broker_male_b__vce_getting_up", 1):set_priority(4)
E:add_audio("broker", "Tokisaki_ja", "vce_struggle_heavy", play_Tokisaki, "play_broker_male_b__vce_struggle_heavy", 1):set_priority(4)
E:add_audio("broker", "Tokisaki_ja", "play_hud_heal_2d", play_Tokisaki, "play_broker_male_b__vce_healing", 1, nil, "play_hud_heal_2d")
E:add_audio("broker", "Tokisaki_ja", "play_syringe_power_start", play_Tokisaki, "play_syringe_power_start", 1, nil, "play_syringe_power_start"):set_priority(4)
E:add_audio("broker", "Tokisaki_ja", "play_syringe_ability_start", play_Tokisaki, "play_syringe_ability_start", 1, nil, "play_syringe_ability_start"):set_priority(4)
E:add_audio("broker", "Tokisaki_ja", "play_syringe_speed_start", play_Tokisaki, "play_syringe_speed_start", 1, nil, "play_syringe_speed_start"):set_priority(4)