-- 【欧格林】【通用】
local loc_hanako = "loc_ogryn_a/hanako/"
local play_hanako = "wwise/events/player/play_ogryn_a/hanako"
E:set_class("ogryn", "hanako_ja", "欧格林"):old_version()
E:add_audio("ogryn", "hanako_ja", "guidance_correct_path_", loc_hanako, "ja_loc_ogryn_a__guidance_correct_path_", 5):add_subtext("欧格林", {"这边走。", "跟着俺！", "长官说走这边。", "路是对的！", "俺走前面。"})
E:add_audio("ogryn", "hanako_ja", "guidance_correct_path_up_", loc_hanako, "ja_loc_ogryn_a__guidance_correct_path_up_", 5):add_subtext("欧格林", {"上去！", "爬高高！", "上面有坏家伙！", "跟着俺上去！", "往上走！"})
E:add_audio("ogryn", "hanako_ja", "guidance_correct_path_drop_", loc_hanako, "ja_loc_ogryn_a__guidance_correct_path_drop_", 6):add_subtext("欧格林", {"跳下去！", "啊啊啊，跳！", "下面有路！", "当心摔断腿！", "跟着俺跳！", "下去打架！"})
E:add_audio("ogryn", "hanako_ja", "stairs_sighted_", loc_hanako, "ja_loc_ogryn_a__stairs_sighted_", 4):add_subtext("欧格林", {"有楼梯！", "踩台阶！", "这里能上去。", "长官，有楼梯。"})
E:add_audio("ogryn", "hanako_ja", "guidance_starting_area_", loc_hanako, "ja_loc_ogryn_a__guidance_starting_area_", 3):add_subtext("欧格林", {"俺准备好了！", "出发，打烂他们！", "为了神皇！"})
E:add_audio("ogryn", "hanako_ja", "region_carnival_a_", loc_hanako, "ja_loc_ogryn_a__region_carnival_a_", 4):add_subtext("欧格林", {"这地方真臭。", "俺饿了。", "坏家伙的基地。", "砸烂这里！"})
E:add_audio("ogryn", "hanako_ja", "info_event_det_pack_a_", loc_hanako, "ja_loc_ogryn_a__info_event_det_pack_a_", 5):add_subtext("欧格林", {"炸弹放好了！", "轰隆隆时间到了！", "快跑，要炸了！", "准备大爆炸！", "俺喜欢爆炸！"})
E:add_audio("ogryn", "hanako_ja", "event_survive_keep_coming_a_", loc_hanako, "ja_loc_ogryn_a__event_survive_keep_coming_a_", 5):add_subtext("欧格林", {"来啊！", "俺站这儿不走！", "打烂你们！", "他们好多人！", "挡住他们！"})
E:add_audio("ogryn", "hanako_ja", "event_demolition_first_corruptor_destroyed_a_", loc_hanako, "ja_loc_ogryn_a__event_demolition_first_corruptor_destroyed_a_", 4):add_subtext("欧格林", {"砸烂一个！", "坏东西没了！", "大功告成！", "继续砸！"})
E:add_audio("ogryn", "hanako_ja", "event_survive_almost_done_", loc_hanako, "ja_loc_ogryn_a__event_survive_almost_done_", 4):add_subtext("欧格林", {"快完了！", "他们怕了！", "俺还没打够！", "继续打！"})
E:add_audio("ogryn", "hanako_ja", "info_event_one_down_", loc_hanako, "ja_loc_ogryn_a__info_event_one_down_", 4):add_subtext("欧格林", {"解决一个！", "死啦！", "下一个是谁！", "太弱了！"})
E:add_audio("ogryn", "hanako_ja", "response_to_hacking_fix_decode_", loc_hanako, "ja_loc_ogryn_a__response_to_hacking_fix_decode_", 4):add_subtext("欧格林", {"机器坏了！", "俺不会修这个！", "小个子，快来修！", "谁来拍拍它？"})
E:add_audio("ogryn", "hanako_ja", "info_event_almost_done_", loc_hanako, "ja_loc_ogryn_a__info_event_almost_done_", 4):add_subtext("欧格林", {"快赢了！", "他们不行了！", "快点，俺饿了。", "快搞定了！"})
E:add_audio("ogryn", "hanako_ja", "warning_exploding_barrel_", loc_hanako, "ja_loc_ogryn_a__warning_exploding_barrel_", 4):add_subtext("欧格林", {"小心桶子！", "那玩意会爆炸！", "离远点，会炸！", "别打那个红桶！"})
E:add_audio("ogryn", "hanako_ja", "response_rechargable_for_look_at_healthstation_", loc_hanako, "ja_loc_ogryn_a__response_rechargable_for_look_at_healthstation_", 4):add_subtext("欧格林", {"治伤的机器！", "机器没电了！", "谁去修修它！", "俺需要治疗机器。"})
E:add_audio("ogryn", "hanako_ja", "smart_tag_vo_station_health_", loc_hanako, "ja_loc_ogryn_a__smart_tag_vo_station_health_", 4):add_subtext("欧格林", {"医疗机器！", "能治伤的！", "在这儿补血！", "长官，医疗站！"})
E:add_audio("ogryn", "hanako_ja", "ability_bonebreaker_", loc_hanako, "ja_loc_ogryn_a__ability_bonebreaker_", 3, 3):add_subtext("欧格林", {"俺冲啦！", "撞碎你们！", "吃俺一撞！"}):set_priority(2)
E:add_audio("ogryn", "hanako_ja", "ability_bullgryn_", loc_hanako, "ja_loc_ogryn_a__ability_bullgryn_", 4, 4):add_subtext("欧格林", {"砸扁你们！", "俺天下无敌！", "都给俺死！", "吃俺一拳！"}):set_priority(2)
E:add_audio("ogryn", "hanako_ja", "ability_gun_lugger_", loc_hanako, "ja_loc_ogryn_a__ability_gun_lugger_", 4, 3):add_subtext("欧格林", {"枪管要热啦！", "吃子弹吧！", "打成马蜂窝！", "哒哒哒哒！"}):set_priority(2)
E:add_audio("ogryn", "hanako_ja", "blitz_rock_a_", loc_hanako, "ja_loc_ogryn_a__blitz_rock_a_", 2):add_subtext("欧格林", {"吃俺一石头！", "砸死你！"})
E:add_audio("ogryn", "hanako_ja", "blitz_grenade_box_a_", loc_hanako, "ja_loc_ogryn_a__blitz_grenade_box_a_", 2):add_subtext("欧格林", {"接住这个盒子！", "送你个大礼！"})
E:add_audio("ogryn", "hanako_ja", "throwing_grenade_", loc_hanako, "ja_loc_ogryn_a__throwing_grenade_", 2):add_subtext("欧格林", {"扔炸弹啦！", "小心爆炸！"})
E:add_audio("ogryn", "hanako_ja", "com_wheel_vo_location_ping_", loc_hanako, "ja_loc_ogryn_a__com_wheel_vo_location_ping_", 4):add_subtext("欧格林", {"去那里！", "看那边！", "长官说去这！", "走这边！"})
E:add_audio("ogryn", "hanako_ja", "com_wheel_vo_location_attention_", loc_hanako, "ja_loc_ogryn_a__com_wheel_vo_location_attention_", 3):add_subtext("欧格林", {"看那！", "那是什么！", "注意那边！"})
E:add_audio("ogryn", "hanako_ja", "com_wheel_vo_yes_", loc_hanako, "ja_loc_ogryn_a__com_wheel_vo_yes_", 5):add_subtext("欧格林", {"好！", "明白！", "俺去做！", "没问题长官！", "包在俺身上！"})
E:add_audio("ogryn", "hanako_ja", "com_wheel_vo_no_", loc_hanako, "ja_loc_ogryn_a__com_wheel_vo_no_", 3):add_subtext("欧格林", {"不行！", "俺不干！", "做不到！"})
E:add_audio("ogryn", "hanako_ja", "com_wheel_vo_enemy_over_here_", loc_hanako, "ja_loc_ogryn_a__com_wheel_vo_enemy_over_here_", 3):add_subtext("欧格林", {"有坏人！", "敌人在那！", "准备打架！"})
E:add_audio("ogryn", "hanako_ja", "com_wheel_vo_thank_you_", loc_hanako, "ja_loc_ogryn_a__com_wheel_vo_thank_you_", 4):add_subtext("欧格林", {"谢谢你！", "你是个好人！", "俺记住了！", "谢谢小个子！"})
E:add_audio("ogryn", "hanako_ja", "com_wheel_vo_need_ammo_", loc_hanako, "ja_loc_ogryn_a__com_wheel_vo_need_ammo_", 4):add_subtext("欧格林", {"俺没子弹了！", "枪空了！", "给俺点子弹！", "子弹盒子在哪！"})
E:add_audio("ogryn", "hanako_ja", "com_wheel_vo_need_health_", loc_hanako, "ja_loc_ogryn_a__com_wheel_vo_need_health_", 4):add_subtext("欧格林", {"俺流血了！", "俺好痛！", "需要治伤！", "救命啊！"})
E:add_audio("ogryn", "hanako_ja", "com_wheel_vo_for_the_emperor_", loc_hanako, "ja_loc_ogryn_a__com_wheel_vo_for_the_emperor_", 3, 5):add_subtext("欧格林", {"为了神皇！", "神皇万岁！", "为了黄金王座！"}):set_priority(2)
E:add_audio("ogryn", "hanako_ja", "com_wheel_vo_follow_you_", loc_hanako, "ja_loc_ogryn_a__com_wheel_vo_follow_you_", 3):add_subtext("欧格林", {"俺跟着你！", "保护小个子！", "你带路！"})
E:add_audio("ogryn", "hanako_ja", "reloading_", loc_hanako, "ja_loc_ogryn_a__reloading_", 3):add_subtext("欧格林", {"换子弹！", "等会儿，换弹匣！", "枪没子弹了！"})
E:add_audio("ogryn", "hanako_ja", "look_at_grenade_", loc_hanako, "ja_loc_ogryn_a__look_at_grenade_", 3):add_subtext("欧格林", {"有炸药！", "炸弹盒子！", "拿炸弹！"})
E:add_audio("ogryn", "hanako_ja", "look_at_healthstation_", loc_hanako, "ja_loc_ogryn_a__look_at_healthstation_", 3):add_subtext("欧格林", {"医疗站！", "来这治伤！", "补血机器！"})
E:add_audio("ogryn", "hanako_ja", "smart_tag_vo_pickup_deployed_medical_crate_", loc_hanako, "ja_loc_ogryn_a__smart_tag_vo_pickup_deployed_medical_crate_", 3):add_subtext("欧格林", {"有药箱！", "医疗包在这！", "拿这个治伤！"})
E:add_audio("ogryn", "hanako_ja", "smart_tag_vo_pickup_deployed_ammo_crate_", loc_hanako, "ja_loc_ogryn_a__smart_tag_vo_pickup_deployed_ammo_crate_", 3):add_subtext("欧格林", {"弹药箱！", "来拿子弹！", "补给在这！"})
E:add_audio("ogryn", "hanako_ja", "smart_tag_vo_pickup_ammo_", loc_hanako, "ja_loc_ogryn_a__smart_tag_vo_pickup_ammo_", 4):add_subtext("欧格林", {"子弹！", "俺的子弹！", "有弹药！", "好多子弹！"})
E:add_audio("ogryn", "hanako_ja", "smart_tag_vo_pickup_health_booster_", loc_hanako, "ja_loc_ogryn_a__smart_tag_vo_pickup_health_booster_", 3):add_subtext("欧格林", {"医疗针！", "打针就不痛了！", "扎一针！"})
E:add_audio("ogryn", "hanako_ja", "smart_tag_vo_pickup_forge_metal_", loc_hanako, "ja_loc_ogryn_a__smart_tag_vo_pickup_forge_metal_", 2):add_subtext("欧格林", {"这是废铁。", "塑钢，能换配给。"})
E:add_audio("ogryn", "hanako_ja", "smart_tag_vo_pickup_platinum_", loc_hanako, "ja_loc_ogryn_a__smart_tag_vo_pickup_platinum_", 2):add_subtext("欧格林", {"亮晶晶的！", "钻石金，长官会喜欢的。"})
E:add_audio("ogryn", "hanako_ja", "smart_tag_vo_pickup_small_grenade_", loc_hanako, "ja_loc_ogryn_a__smart_tag_vo_pickup_small_grenade_", 2):add_subtext("欧格林", {"小炸弹！", "手雷补给！"})
E:add_audio("ogryn", "hanako_ja", "cover_me_", loc_hanako, "ja_loc_ogryn_a__cover_me_", 3):add_subtext("欧格林", {"掩护俺！", "帮俺打他们！", "保护俺！"})
E:add_audio("ogryn", "hanako_ja", "away_from_squad_", loc_hanako, "ja_loc_ogryn_a__away_from_squad_", 4):add_subtext("欧格林", {"俺迷路了！", "俺走太远了！", "等等俺！", "队伍在哪！"})
E:add_audio("ogryn", "hanako_ja", "come_back_to_squad_", loc_hanako, "ja_loc_ogryn_a__come_back_to_squad_", 4):add_subtext("欧格林", {"回来，小个子！", "别跑远了！", "靠拢，快点！", "别乱跑！"})
E:add_audio("ogryn", "hanako_ja", "ogryn_seen_killstreak_psyker_", loc_hanako, "ja_loc_ogryn_a__ogryn_seen_killstreak_psyker_", 3, 5):add_subtext("欧格林", {"怪人好厉害！", "火花四溅！", "打得好！"}):set_priority(2)
E:add_audio("ogryn", "hanako_ja", "ogryn_seen_killstreak_zealot_", loc_hanako, "ja_loc_ogryn_a__ogryn_seen_killstreak_zealot_", 3, 5):add_subtext("欧格林", {"叫花子真凶！", "砍得好！", "打得好！"}):set_priority(2)
E:add_audio("ogryn", "hanako_ja", "ogryn_seen_killstreak_veteran_", loc_hanako, "ja_loc_ogryn_a__ogryn_seen_killstreak_veteran_", 3, 5):add_subtext("欧格林", {"小个子枪法准！", "好枪法！", "打得好！"}):set_priority(2)
E:add_audio("ogryn", "hanako_ja", "ogryn_seen_killstreak_ogryn_", loc_hanako, "ja_loc_ogryn_a__ogryn_seen_killstreak_ogryn_", 3, 5):add_subtext("欧格林", {"大块头真棒！", "砸得好！", "跟俺一样猛！"}):set_priority(2)
E:add_audio("ogryn", "hanako_ja", "ogryn_seen_killstreak_adamant_", loc_hanako, "ja_loc_ogryn_a__ogryn_seen_killstreak_adamant_", 3, 5):add_subtext("欧格林", {"法务官好厉害！", "打得好，长官！", "真能打！"}):set_priority(2)
E:add_audio("ogryn", "hanako_ja", "response_for_zealot_seen_killstreak_ogryn_", loc_hanako, "ja_loc_ogryn_a__response_for_zealot_seen_killstreak_ogryn_", 5, 5):add_subtext("欧格林", {"俺很强壮！", "神皇保佑俺！", "俺喜欢打架！", "再来啊！", "砸扁他们！"}):set_priority(2)
E:add_audio("ogryn", "hanako_ja", "response_for_veteran_seen_killstreak_ogryn_", loc_hanako, "ja_loc_ogryn_a__response_for_veteran_seen_killstreak_ogryn_", 5, 5):add_subtext("欧格林", {"俺很强壮！", "神皇保佑俺！", "俺喜欢打架！", "再来啊！", "砸扁他们！"}):set_priority(2)
E:add_audio("ogryn", "hanako_ja", "response_for_psyker_seen_killstreak_ogryn_", loc_hanako, "ja_loc_ogryn_a__response_for_psyker_seen_killstreak_ogryn_", 5, 5):add_subtext("欧格林", {"俺很强壮！", "神皇保佑俺！", "俺喜欢打架！", "再来啊！", "砸扁他们！"}):set_priority(2)
E:add_audio("ogryn", "hanako_ja", "response_for_ogryn_seen_killstreak_ogryn_", loc_hanako, "ja_loc_ogryn_a__response_for_ogryn_seen_killstreak_ogryn_", 5, 5):add_subtext("欧格林", {"俺很强壮！", "神皇保佑俺！", "俺喜欢打架！", "再来啊！", "砸扁他们！"}):set_priority(2)
E:add_audio("ogryn", "hanako_ja", "response_for_adamant_seen_killstreak_ogryn_", loc_hanako, "ja_loc_ogryn_a__response_for_adamant_seen_killstreak_ogryn_", 5, 5):add_subtext("欧格林", {"俺很强壮！", "神皇保佑俺！", "俺喜欢打架！", "再来啊！", "砸扁他们！"}):set_priority(2)
E:add_audio("ogryn", "hanako_ja", "response_for_friendly_fire_from_zealot_", loc_hanako, "ja_loc_ogryn_a__response_for_friendly_fire_from_zealot_", 2):add_subtext("欧格林", {"哎哟！你打俺了！", "看着点，小个子！"})
E:add_audio("ogryn", "hanako_ja", "response_for_friendly_fire_from_veteran_", loc_hanako, "ja_loc_ogryn_a__response_for_friendly_fire_from_veteran_", 2):add_subtext("欧格林", {"哎哟！你打俺了！", "看着点，小个子！"})
E:add_audio("ogryn", "hanako_ja", "response_for_friendly_fire_from_psyker_", loc_hanako, "ja_loc_ogryn_a__response_for_friendly_fire_from_psyker_", 2):add_subtext("欧格林", {"哎哟！你打俺了！", "看着点，小个子！"})
E:add_audio("ogryn", "hanako_ja", "response_for_friendly_fire_from_ogryn_", loc_hanako, "ja_loc_ogryn_a__response_for_friendly_fire_from_ogryn_", 2):add_subtext("欧格林", {"哎哟！你打俺了！", "看着点，大块头！"})
E:add_audio("ogryn", "hanako_ja", "response_for_friendly_fire_from_adamant_", loc_hanako, "ja_loc_ogryn_a__response_for_friendly_fire_from_adamant_", 2):add_subtext("欧格林", {"哎哟！你打俺了！", "看着点，长官！"})
E:add_audio("ogryn", "hanako_ja", "friendly_fire_from_zealot_to_ogryn_", loc_hanako, "ja_loc_ogryn_a__friendly_fire_from_zealot_to_ogryn_", 2):add_subtext("欧格林", {"别打俺！", "俺是自己人！"})
E:add_audio("ogryn", "hanako_ja", "friendly_fire_from_veteran_to_ogryn_", loc_hanako, "ja_loc_ogryn_a__friendly_fire_from_veteran_to_ogryn_", 2):add_subtext("欧格林", {"别打俺！", "俺是自己人！"})
E:add_audio("ogryn", "hanako_ja", "friendly_fire_from_psyker_to_ogryn_", loc_hanako, "ja_loc_ogryn_a__friendly_fire_from_psyker_to_ogryn_", 2):add_subtext("欧格林", {"别打俺！", "俺是自己人！"})
E:add_audio("ogryn", "hanako_ja", "friendly_fire_from_ogryn_to_ogryn_", loc_hanako, "ja_loc_ogryn_a__friendly_fire_from_ogryn_to_ogryn_", 2):add_subtext("欧格林", {"别打俺！", "俺是自己人！"})
E:add_audio("ogryn", "hanako_ja", "friendly_fire_from_adamant_to_ogryn_", loc_hanako, "ja_loc_ogryn_a__friendly_fire_from_adamant_to_ogryn_", 2):add_subtext("欧格林", {"别打俺！", "俺是自己人！"})
E:add_audio("ogryn", "hanako_ja", "head_shot_", loc_hanako, "ja_loc_ogryn_a__head_shot_", 4):add_subtext("欧格林", {"脑袋开花！", "爆头！", "砸碎西瓜！", "好枪法！"})
E:add_audio("ogryn", "hanako_ja", "response_for_zealot_disabled_by_enemy_", loc_hanako, "ja_loc_ogryn_a__response_for_zealot_disabled_by_enemy_", 3):add_subtext("欧格林", {"小个子倒了！", "去救他！", "别死啊！"})
E:add_audio("ogryn", "hanako_ja", "response_for_veteran_disabled_by_enemy_", loc_hanako, "ja_loc_ogryn_a__response_for_veteran_disabled_by_enemy_", 3):add_subtext("欧格林", {"小个子倒了！", "去救他！", "别死啊！"})
E:add_audio("ogryn", "hanako_ja", "response_for_psyker_disabled_by_enemy_", loc_hanako, "ja_loc_ogryn_a__response_for_psyker_disabled_by_enemy_", 3):add_subtext("欧格林", {"怪人倒了！", "去救他！", "别死啊！"})
E:add_audio("ogryn", "hanako_ja", "response_for_ogryn_disabled_by_enemy_", loc_hanako, "ja_loc_ogryn_a__response_for_ogryn_disabled_by_enemy_", 3):add_subtext("欧格林", {"大块头倒了！", "去拉他起来！", "别死啊！"})
E:add_audio("ogryn", "hanako_ja", "response_for_adamant_disabled_by_enemy_", loc_hanako, "ja_loc_ogryn_a__response_for_adamant_disabled_by_enemy_", 3):add_subtext("欧格林", {"长官倒了！", "快去救长官！", "别死啊！"})
E:add_audio("ogryn", "hanako_ja", "ogryn_start_revive_ogryn_", loc_hanako, "ja_loc_ogryn_a__ogryn_start_revive_ogryn_", 3):add_subtext("欧格林", {"起来，大块头！", "俺拉你！", "还能打！"})
E:add_audio("ogryn", "hanako_ja", "ogryn_start_revive_zealot_", loc_hanako, "ja_loc_ogryn_a__ogryn_start_revive_zealot_", 3):add_subtext("欧格林", {"起来，小个子！", "俺拉你！", "还能打！"})
E:add_audio("ogryn", "hanako_ja", "ogryn_start_revive_veteran_", loc_hanako, "ja_loc_ogryn_a__ogryn_start_revive_veteran_", 3):add_subtext("欧格林", {"起来，小个子！", "俺拉你！", "还能打！"})
E:add_audio("ogryn", "hanako_ja", "ogryn_start_revive_psyker_", loc_hanako, "ja_loc_ogryn_a__ogryn_start_revive_psyker_", 3):add_subtext("欧格林", {"起来，小个子！", "俺拉你！", "还能打！"})
E:add_audio("ogryn", "hanako_ja", "ogryn_start_revive_adamant_", loc_hanako, "ja_loc_ogryn_a__ogryn_start_revive_adamant_", 3):add_subtext("欧格林", {"起来，长官！", "俺拉你！", "还能打！"})
E:add_audio("ogryn", "hanako_ja", "combat_pause_one_liner_", loc_hanako, "ja_loc_ogryn_a__combat_pause_one_liner_", 1):add_subtext("欧格林", {"俺饿了，想吃配给。"})
E:add_audio("ogryn", "hanako_ja", "surrounded_", loc_hanako, "ja_loc_ogryn_a__surrounded_", 4):add_subtext("欧格林", {"到处都是坏人！", "俺们被包围了！", "好多人，俺要砸扁他们！", "来啊！"})
E:add_audio("ogryn", "hanako_ja", "surrounded_response_", loc_hanako, "ja_loc_ogryn_a__surrounded_response_", 2):add_subtext("欧格林", {"别怕，俺在！", "俺保护你们！"})
E:add_audio("ogryn", "hanako_ja", "heard_horde_vector_", loc_hanako, "ja_loc_ogryn_a__heard_horde_vector_", 4):add_subtext("欧格林", {"好多脚步声！", "他们来啦！", "准备打架！", "好大一群！"})
E:add_audio("ogryn", "hanako_ja", "heard_horde_ambush_", loc_hanako, "ja_loc_ogryn_a__heard_horde_ambush_", 2):add_subtext("欧格林", {"他们从后面来了！", "小心偷袭！"})
E:add_audio("ogryn", "hanako_ja", "heard_enemy_beast_of_nurgle_", loc_hanako, "ja_loc_ogryn_a__heard_enemy_beast_of_nurgle_", 4):add_subtext("欧格林", {"好大一只！", "听起来像大怪物！", "俺闻到臭味了！", "有个大个子！"})
E:add_audio("ogryn", "hanako_ja", "heard_enemy_chaos_spawn_", loc_hanako, "ja_loc_ogryn_a__heard_enemy_chaos_spawn_", 4):add_subtext("欧格林", {"怪物来了！", "好恶心的声音！", "有大怪物！", "俺听到大块头了！"})
E:add_audio("ogryn", "hanako_ja", "heard_enemy_plague_ogryn_", loc_hanako, "ja_loc_ogryn_a__heard_enemy_plague_ogryn_", 4):add_subtext("欧格林", {"俺听到大块头了！", "有坏欧格林！", "有个大块头坏蛋！", "它听起来很生气！"})
E:add_audio("ogryn", "hanako_ja", "conversation_plague_ogryn_weakpoint_01_", loc_hanako, "ja_loc_ogryn_a__conversation_plague_ogryn_weakpoint_01_", 3):add_subtext("欧格林", {"打他的头！", "砸他脑袋！", "头是弱点！"})
E:add_audio("ogryn", "hanako_ja", "conversation_beast_of_nurgle_weakpoint_a_", loc_hanako, "ja_loc_ogryn_a__conversation_beast_of_nurgle_weakpoint_a_", 3):add_subtext("欧格林", {"打他背上发光的！", "砸背后的包！", "打背后！"})
E:add_audio("ogryn", "hanako_ja", "conversation_beast_of_nurgle_weakpoint_c_", loc_hanako, "ja_loc_ogryn_a__conversation_beast_of_nurgle_weakpoint_c_", 3):add_subtext("欧格林", {"打他背上！", "打后背！", "砸背后的包！"})
E:add_audio("ogryn", "hanako_ja", "seen_enemy_plague_ogryn_", loc_hanako, "ja_loc_ogryn_a__seen_enemy_plague_ogryn_", 4):add_subtext("欧格林", {"瘟疫欧格林！", "坏大个子来了！", "俺比他强！", "砸烂他！"})
E:add_audio("ogryn", "hanako_ja", "seen_enemy_beast_of_nurgle_", loc_hanako, "ja_loc_ogryn_a__seen_enemy_beast_of_nurgle_", 4):add_subtext("欧格林", {"大鼻涕虫！", "好恶心！", "纳垢兽来了！", "杀掉大怪物！"})
E:add_audio("ogryn", "hanako_ja", "seen_enemy_chaos_spawn_", loc_hanako, "ja_loc_ogryn_a__seen_enemy_chaos_spawn_", 4):add_subtext("欧格林", {"混沌触手怪！", "好丑的怪物！", "打烂它！", "大怪兽！"})
E:add_audio("ogryn", "hanako_ja", "smart_tag_vo_enemy_chaos_spawn_a_", loc_hanako, "ja_loc_ogryn_a__smart_tag_vo_enemy_chaos_spawn_a_", 3):add_subtext("欧格林", {"看那个大怪物！", "集火那个丑东西！", "打它！"})
E:add_audio("ogryn", "hanako_ja", "smart_tag_vo_enemy_chaos_spawn_b_", loc_hanako, "ja_loc_ogryn_a__smart_tag_vo_enemy_chaos_spawn_b_", 3):add_subtext("欧格林", {"看那个大怪物！", "集火那个丑东西！", "打它！"})
E:add_audio("ogryn", "hanako_ja", "smart_tag_vo_enemy_beast_of_nurgle_", loc_hanako, "ja_loc_ogryn_a__smart_tag_vo_enemy_beast_of_nurgle_", 3):add_subtext("欧格林", {"打大鼻涕虫！", "恶心怪在这！", "杀纳垢兽！"})
E:add_audio("ogryn", "hanako_ja", "smart_tag_vo_enemy_plague_ogryn_", loc_hanako, "ja_loc_ogryn_a__smart_tag_vo_enemy_plague_ogryn_", 3):add_subtext("欧格林", {"坏欧格林在这！", "打那个大块头！", "集火坏欧格林！"})
E:add_audio("ogryn", "hanako_ja", "heard_enemy_daemonhost_", loc_hanako, "ja_loc_ogryn_a__heard_enemy_daemonhost_", 3):add_subtext("欧格林", {"嘘，有个睡觉的怪东西。", "有女巫在哭。", "俺听到怪声了。"})
E:add_audio("ogryn", "hanako_ja", "seen_enemy_daemonhost_", loc_hanako, "ja_loc_ogryn_a__seen_enemy_daemonhost_", 3):add_subtext("欧格林", {"别碰那个浮空女巫！", "恶魔宿主，别开火！", "绕过去！"})
E:add_audio("ogryn", "hanako_ja", "alerted_ememy_daemonhost_", loc_hanako, "ja_loc_ogryn_a__alerted_ememy_daemonhost_", 3):add_subtext("欧格林", {"谁把它吵醒了！", "女巫生气了！", "糟了，恶魔来了！"})
E:add_audio("ogryn", "hanako_ja", "smart_tag_vo_enemy_daemonhost_", loc_hanako, "ja_loc_ogryn_a__smart_tag_vo_enemy_daemonhost_", 3):add_subtext("欧格林", {"恶魔宿主！", "离它远点！", "别打它！"})
E:add_audio("ogryn", "hanako_ja", "monster_fight_start_reaction_", loc_hanako, "ja_loc_ogryn_a__monster_fight_start_reaction_", 5, 5):add_subtext("欧格林", {"来打一架吧！", "俺要砸烂你！", "大块头对决！", "受死吧大怪物！", "为了神皇！"}):set_priority(2)
E:add_audio("ogryn", "hanako_ja", "enemy_near_death_monster_", loc_hanako, "ja_loc_ogryn_a__enemy_near_death_monster_", 4, 5):add_subtext("欧格林", {"它快死了！", "继续打！", "马上砸扁！", "它不行了！"}):set_priority(2)
E:add_audio("ogryn", "hanako_ja", "enemy_kill_monster_", loc_hanako, "ja_loc_ogryn_a__enemy_kill_monster_", 5, 6):add_subtext("欧格林", {"大怪物死了！", "俺赢了！", "一滩烂肉！", "俺最强壮！", "哈哈！"}):set_priority(2)
E:add_audio("ogryn", "hanako_ja", "mission_cargo_something_big_", loc_hanako, "ja_loc_ogryn_a__mission_cargo_something_big_", 2):add_subtext("欧格林", {"有大家伙来了。", "俺感觉地在震。"})
E:add_audio("ogryn", "hanako_ja", "heard_enemy_chaos_hound_", loc_hanako, "ja_loc_ogryn_a__heard_enemy_chaos_hound_", 4):add_subtext("欧格林", {"听见狗叫了！", "有疯狗！", "瘟疫猎犬！", "狗狗来了！"})
E:add_audio("ogryn", "hanako_ja", "seen_enemy_chaos_hound_", loc_hanako, "ja_loc_ogryn_a__seen_enemy_chaos_hound_", 4):add_subtext("欧格林", {"疯狗在这！", "打狗！", "在那边！", "别被狗咬！"})
E:add_audio("ogryn", "hanako_ja", "smart_tag_vo_enemy_chaos_hound_", loc_hanako, "ja_loc_ogryn_a__smart_tag_vo_enemy_chaos_hound_", 3):add_subtext("欧格林", {"看那条狗！", "猎犬！", "打疯狗！"})
E:add_audio("ogryn", "hanako_ja", "enemy_kill_chaos_hound_", loc_hanako, "ja_loc_ogryn_a__enemy_kill_chaos_hound_", 4):add_subtext("欧格林", {"死狗！", "狗死了！", "一拳打死狗！", "没事了！"})
E:add_audio("ogryn", "hanako_ja", "seen_netgunner_", loc_hanako, "ja_loc_ogryn_a__seen_netgunner_", 4):add_subtext("欧格林", {"抓人的家伙！", "陷阱手来了！", "带网的坏蛋！", "小心网子！"})
E:add_audio("ogryn", "hanako_ja", "seen_netgunner_flee_", loc_hanako, "ja_loc_ogryn_a__seen_netgunner_flee_", 3):add_subtext("欧格林", {"他跑了！", "别跑，胆小鬼！", "他溜了！"})
E:add_audio("ogryn", "hanako_ja", "smart_tag_vo_enemy_netgunner_", loc_hanako, "ja_loc_ogryn_a__smart_tag_vo_enemy_netgunner_", 3):add_subtext("欧格林", {"陷阱手！", "打带网的家伙！", "他在那！"})
E:add_audio("ogryn", "hanako_ja", "enemy_kill_netgunner_", loc_hanako, "ja_loc_ogryn_a__enemy_kill_netgunner_", 4):add_subtext("欧格林", {"网子男死了！", "砸烂了！", "你抓不到俺！", "干掉陷阱手！"})
E:add_audio("ogryn", "hanako_ja", "seen_enemy_mutant_charger_", loc_hanako, "ja_loc_ogryn_a__seen_enemy_mutant_charger_", 4):add_subtext("欧格林", {"大嗓门来了！", "变种人！", "他冲过来了！", "小心撞击！"})
E:add_audio("ogryn", "hanako_ja", "smart_tag_vo_enemy_chaos_mutant_charger_", loc_hanako, "ja_loc_ogryn_a__smart_tag_vo_enemy_chaos_mutant_charger_", 4):add_subtext("欧格林", {"变种人在这！", "打大嗓门！", "看那个冲锋的家伙！", "打断他的腿！"})
E:add_audio("ogryn", "hanako_ja", "enemy_kill_mutant_charger_", loc_hanako, "ja_loc_ogryn_a__enemy_kill_mutant_charger_", 5):add_subtext("欧格林", {"大嗓门闭嘴了！", "变种人死了！", "撞不过俺！", "砸烂了！", "哈哈，死了！"})
E:add_audio("ogryn", "hanako_ja", "heard_enemy_poxwalker_bomber_", loc_hanako, "ja_loc_ogryn_a__heard_enemy_poxwalker_bomber_", 4):add_subtext("欧格林", {"滴滴滴的声音！", "炸弹人来了！", "有个疯子带炸弹！", "小心爆炸！"})
E:add_audio("ogryn", "hanako_ja", "seen_enemy_poxwalker_bomber_", loc_hanako, "ja_loc_ogryn_a__seen_enemy_poxwalker_bomber_", 4):add_subtext("欧格林", {"炸弹人！", "别让他靠近！", "打带炸弹的家伙！", "在那！"})
E:add_audio("ogryn", "hanako_ja", "smart_tag_vo_enemy_chaos_poxwalker_bomber_", loc_hanako, "ja_loc_ogryn_a__smart_tag_vo_enemy_chaos_poxwalker_bomber_", 4):add_subtext("欧格林", {"看那个炸弹人！", "打他！", "别让他炸俺们！", "炸弹人在这！"})
E:add_audio("ogryn", "hanako_ja", "enemy_kill_poxwalker_bomber_", loc_hanako, "ja_loc_ogryn_a__enemy_kill_poxwalker_bomber_", 5):add_subtext("欧格林", {"炸了！", "像放烟花一样！", "炸弹人死了！", "哈哈！", "烂肉横飞！"})
E:add_audio("ogryn", "hanako_ja", "smart_tag_vo_enemy_scab_flamer_a_", loc_hanako, "ja_loc_ogryn_a__smart_tag_vo_enemy_scab_flamer_a_", 4):add_subtext("欧格林", {"喷火的家伙！", "火焰兵！", "小心被烧！", "打他！"})
E:add_audio("ogryn", "hanako_ja", "smart_tag_vo_tox_flamer_", loc_hanako, "ja_loc_ogryn_a__smart_tag_vo_tox_flamer_", 4):add_subtext("欧格林", {"喷绿火的家伙！", "毒火兵！", "好臭的火！", "打死他！"})
E:add_audio("ogryn", "hanako_ja", "seen_enemy_tox_flamer_", loc_hanako, "ja_loc_ogryn_a__seen_enemy_tox_flamer_", 3):add_subtext("欧格林", {"毒火兵来了！", "小心绿火！", "他在那！"})
E:add_audio("ogryn", "hanako_ja", "seen_enemy_scab_flamer_a_", loc_hanako, "ja_loc_ogryn_a__seen_enemy_scab_flamer_a_", 3):add_subtext("欧格林", {"火焰兵来了！", "小心火！", "他在那！"})
E:add_audio("ogryn", "hanako_ja", "enemy_kill_tox_flamer_", loc_hanako, "ja_loc_ogryn_a__enemy_kill_tox_flamer_", 4):add_subtext("欧格林", {"他不喷火了！", "毒火兵死了！", "罐子炸了！", "砸烂了！"})
E:add_audio("ogryn", "hanako_ja", "enemy_kill_scab_flamer_a_", loc_hanako, "ja_loc_ogryn_a__enemy_kill_scab_flamer_a_", 4):add_subtext("欧格林", {"他不喷火了！", "火焰兵死了！", "罐子炸了！", "砸烂了！"})
E:add_audio("ogryn", "hanako_ja", "seen_enemy_traitor_grenadier_", loc_hanako, "ja_loc_ogryn_a__seen_enemy_traitor_grenadier_", 4):add_subtext("欧格林", {"扔雷的家伙！", "掷弹兵！", "他在那！", "小心炸弹！"})
E:add_audio("ogryn", "hanako_ja", "smart_tag_vo_enemy_traitor_grenadier_", loc_hanako, "ja_loc_ogryn_a__smart_tag_vo_enemy_traitor_grenadier_", 3):add_subtext("欧格林", {"看那个掷弹兵！", "打扔雷的家伙！", "掷弹兵在这！"})
E:add_audio("ogryn", "hanako_ja", "enemy_kill_traitor_grenadier_", loc_hanako, "ja_loc_ogryn_a__enemy_kill_traitor_grenadier_", 4):add_subtext("欧格林", {"他不扔了！", "掷弹兵死了！", "砸烂了！", "干得好！"})
E:add_audio("ogryn", "hanako_ja", "seen_enemy_cultist_grenadier_", loc_hanako, "ja_loc_ogryn_a__seen_enemy_cultist_grenadier_", 4):add_subtext("欧格林", {"扔雷的家伙！", "掷弹兵！", "他在那！", "小心炸弹！"})
E:add_audio("ogryn", "hanako_ja", "smart_tag_vo_enemy_cultist_grenadier_", loc_hanako, "ja_loc_ogryn_a__smart_tag_vo_enemy_cultist_grenadier_", 3):add_subtext("欧格林", {"看那个掷弹兵！", "打扔雷的家伙！", "掷弹兵在这！"})
E:add_audio("ogryn", "hanako_ja", "enemy_kill_grenadier_", loc_hanako, "ja_loc_ogryn_a__enemy_kill_grenadier_", 4):add_subtext("欧格林", {"他不扔了！", "掷弹兵死了！", "砸烂了！", "干得好！"})
E:add_audio("ogryn", "hanako_ja", "smart_tag_vo_enemy_traitor_sniper_", loc_hanako, "ja_loc_ogryn_a__smart_tag_vo_enemy_traitor_sniper_", 4):add_subtext("欧格林", {"藏起来的开枪的！", "狙击手！", "找掩体！", "打狙击手！"})
E:add_audio("ogryn", "hanako_ja", "seen_enemy_sniper_", loc_hanako, "ja_loc_ogryn_a__seen_enemy_sniper_", 4):add_subtext("欧格林", {"有狙击手！", "被瞄准了！", "亮光在那！", "小心远处！"})
E:add_audio("ogryn", "hanako_ja", "enemy_kill_sniper_a_", loc_hanako, "ja_loc_ogryn_a__enemy_kill_sniper_a_", 4):add_subtext("欧格林", {"狙击手死了！", "他不烦人了！", "砸碎了胆小鬼！", "干掉狙击手！"})
E:add_audio("ogryn", "hanako_ja", "seen_enemy_traitor_gunner_", loc_hanako, "ja_loc_ogryn_a__seen_enemy_traitor_gunner_", 4):add_subtext("欧格林", {"大枪坏人！", "机枪手来了！", "好多子弹！", "找掩护！"})
E:add_audio("ogryn", "hanako_ja", "smart_tag_vo_enemy_traitor_gunner_", loc_hanako, "ja_loc_ogryn_a__smart_tag_vo_enemy_traitor_gunner_", 3):add_subtext("欧格林", {"机枪手！", "打那个拿大枪的！", "在这！"})
E:add_audio("ogryn", "hanako_ja", "seen_enemy_cultist_holy_stubber_gunner_", loc_hanako, "ja_loc_ogryn_a__seen_enemy_cultist_holy_stubber_gunner_", 4):add_subtext("欧格林", {"大枪坏人！", "机枪手来了！", "好多子弹！", "找掩护！"})
E:add_audio("ogryn", "hanako_ja", "smart_tag_vo_enemy_cultist_holy_stubber_gunner_", loc_hanako, "ja_loc_ogryn_a__smart_tag_vo_enemy_cultist_holy_stubber_gunner_", 3):add_subtext("欧格林", {"机枪手！", "打那个拿大枪的！", "在这！"})
E:add_audio("ogryn", "hanako_ja", "seen_enemy_heavy_gunner_", loc_hanako, "ja_loc_ogryn_a__seen_enemy_heavy_gunner_", 4):add_subtext("欧格林", {"大枪坏人！", "重机枪手！", "好多子弹！", "找掩护！"})
E:add_audio("ogryn", "hanako_ja", "smart_tag_vo_enemy_heavy_gunner_", loc_hanako, "ja_loc_ogryn_a__smart_tag_vo_enemy_heavy_gunner_", 3):add_subtext("欧格林", {"重机枪手！", "打那个拿大枪的！", "在这！"})
E:add_audio("ogryn", "hanako_ja", "seen_enemy_shocktrooper_", loc_hanako, "ja_loc_ogryn_a__seen_enemy_shocktrooper_", 4):add_subtext("欧格林", {"拿喷子的坏人！", "霰弹枪手！", "别让他靠近！", "近战兵来了！"})
E:add_audio("ogryn", "hanako_ja", "smart_tag_vo_enemy_traitor_scout_shocktrooper_", loc_hanako, "ja_loc_ogryn_a__smart_tag_vo_enemy_traitor_scout_shocktrooper_", 3):add_subtext("欧格林", {"霰弹枪手！", "打喷子兵！", "在这！"})
E:add_audio("ogryn", "hanako_ja", "seen_enemy_cultist_shocktrooper_", loc_hanako, "ja_loc_ogryn_a__seen_enemy_cultist_shocktrooper_", 4):add_subtext("欧格林", {"拿喷子的坏人！", "霰弹枪手！", "别让他靠近！", "近战兵来了！"})
E:add_audio("ogryn", "hanako_ja", "smart_tag_vo_enemy_cultist_shocktrooper_", loc_hanako, "ja_loc_ogryn_a__smart_tag_vo_enemy_cultist_shocktrooper_", 3):add_subtext("欧格林", {"霰弹枪手！", "打喷子兵！", "在这！"})
E:add_audio("ogryn", "hanako_ja", "seen_enemy_executor_", loc_hanako, "ja_loc_ogryn_a__seen_enemy_executor_", 4):add_subtext("欧格林", {"拿大斧头的！", "重锤兵！", "他想砍俺！", "近战坏人！"})
E:add_audio("ogryn", "hanako_ja", "smart_tag_vo_enemy_traitor_executor_", loc_hanako, "ja_loc_ogryn_a__smart_tag_vo_enemy_traitor_executor_", 3):add_subtext("欧格林", {"重锤兵！", "打那个拿大斧头的！", "在这！"})
E:add_audio("ogryn", "hanako_ja", "smart_tag_vo_enemy_chaos_ogryn_bulwark_", loc_hanako, "ja_loc_ogryn_a__smart_tag_vo_enemy_chaos_ogryn_bulwark_", 4):add_subtext("欧格林", {"拿铁板的欧格林！", "盾卫大块头！", "打他背后！", "盾卫！"})
E:add_audio("ogryn", "hanako_ja", "seen_enemy_bulwark_", loc_hanako, "ja_loc_ogryn_a__seen_enemy_bulwark_", 4):add_subtext("欧格林", {"盾卫来了！", "拿盾的欧格林！", "俺来砸碎他的盾！", "绕过去打！"})
E:add_audio("ogryn", "hanako_ja", "seen_enemy_chaos_ogryn_armored_executor_", loc_hanako, "ja_loc_ogryn_a__seen_enemy_chaos_ogryn_armored_executor_", 4):add_subtext("欧格林", {"穿铁罐头的欧格林！", "粉碎者！", "铁甲大块头来了！", "他拿大锤子！"})
E:add_audio("ogryn", "hanako_ja", "smart_tag_vo_enemy_chaos_ogryn_armored_executor_", loc_hanako, "ja_loc_ogryn_a__smart_tag_vo_enemy_chaos_ogryn_armored_executor_", 3):add_subtext("欧格林", {"粉碎者！", "打铁罐头！", "穿盔甲的欧格林在这！"})
E:add_audio("ogryn", "hanako_ja", "seen_enemy_chaos_ogryn_heavy_gunner_", loc_hanako, "ja_loc_ogryn_a__seen_enemy_chaos_ogryn_heavy_gunner_", 4):add_subtext("欧格林", {"拿大枪的欧格林！", "收割者来了！", "他拿好大的枪！", "找掩护！"})
E:add_audio("ogryn", "hanako_ja", "smart_tag_vo_enemy_chaos_ogryn_heavy_gunner_", loc_hanako, "ja_loc_ogryn_a__smart_tag_vo_enemy_chaos_ogryn_heavy_gunner_", 3):add_subtext("欧格林", {"收割者！", "打拿大枪的欧格林！", "在这！"})
E:add_audio("ogryn", "hanako_ja", "seen_enemy_berserker_", loc_hanako, "ja_loc_ogryn_a__seen_enemy_berserker_", 4):add_subtext("欧格林", {"疯子来了！", "狂战士！", "他们不要命了！", "好吵的家伙！"})
E:add_audio("ogryn", "hanako_ja", "smart_tag_vo_enemy_berserker_", loc_hanako, "ja_loc_ogryn_a__smart_tag_vo_enemy_berserker_", 3):add_subtext("欧格林", {"狂战士！", "打疯子！", "在这！"})
E:add_audio("ogryn", "hanako_ja", "enemy_kill_berserker_", loc_hanako, "ja_loc_ogryn_a__enemy_kill_berserker_", 4):add_subtext("欧格林", {"疯子死了！", "闭嘴吧！", "砸烂了！", "真弱！"})
E:add_audio("ogryn", "hanako_ja", "enemy_kill_berserker_ext_03_c_", loc_hanako, "ja_loc_ogryn_a__enemy_kill_berserker_ext_03_c_", 4):add_subtext("欧格林", {"疯子死了！", "闭嘴吧！", "砸烂了！", "真弱！"})
E:add_audio("ogryn", "hanako_ja", "seen_enemy_group_far_range_shooting_behind_cover_", loc_hanako, "ja_loc_ogryn_a__seen_enemy_group_far_range_shooting_behind_cover_", 3):add_subtext("欧格林", {"躲在后面的小鸡！", "胆小鬼躲起来了！", "冲过去砸扁他们！"})
E:add_audio("ogryn", "hanako_ja", "seen_enemy_group_assaulting_", loc_hanako, "ja_loc_ogryn_a__seen_enemy_group_assaulting_", 3):add_subtext("欧格林", {"他们冲过来了！", "正好，省得俺去找！", "准备打架！"})
E:add_audio("ogryn", "hanako_ja", "quick_agnostic_enemy_kill_a_", loc_hanako, "ja_loc_ogryn_a__quick_agnostic_enemy_kill_a_", 6, 4):add_subtext("欧格林", {"死吧！", "砸扁！", "碾碎你们！", "哈哈，一拳！", "像踩虫子一样！", "太弱了！"}):set_priority(2)
E:add_audio("ogryn", "hanako_ja", "player_tip_armor_hit_generic_", loc_hanako, "ja_loc_ogryn_a__player_tip_armor_hit_generic_", 4):add_subtext("欧格林", {"打不穿壳子！", "砸不坏盔甲！", "换个地方打！", "太硬了！"})
E:add_audio("ogryn", "hanako_ja", "event_kill_tareget_damaged_", loc_hanako, "ja_loc_ogryn_a__event_kill_tareget_damaged_", 3):add_subtext("欧格林", {"把它砸烂一半了！", "继续打！", "它不行了！"})
E:add_audio("ogryn", "hanako_ja", "event_kill_target_heavy_damage_a_", loc_hanako, "ja_loc_ogryn_a__event_kill_target_heavy_damage_a_", 3):add_subtext("欧格林", {"马上就碎了！", "最后一下！", "他要死啦！"})
E:add_audio("ogryn", "hanako_ja", "event_kill_target_destroyed_a_", loc_hanako, "ja_loc_ogryn_a__event_kill_target_destroyed_a_", 3):add_subtext("欧格林", {"彻底砸烂了！", "搞定！", "全砸碎了！"})
E:add_audio("ogryn", "hanako_ja", "guidance_switch_", loc_hanako, "ja_loc_ogryn_a__guidance_switch_", 3):add_subtext("欧格林", {"按钮在这！", "俺按了！", "这里有个开关。"})
E:add_audio("ogryn", "hanako_ja", "luggable_mission_pick_up_", loc_hanako, "ja_loc_ogryn_a__luggable_mission_pick_up_", 3):add_subtext("欧格林", {"这个俺来拿！", "对俺来说不重。", "俺力气大！"})
E:add_audio("ogryn", "hanako_ja", "critical_health_", loc_hanako, "ja_loc_ogryn_a__critical_health_", 4, 6):add_subtext("欧格林", {"俺要死啦...", "救命，好痛...", "俺看不清了...", "小个子，帮帮俺..."}):set_priority(1)
E:add_audio("ogryn", "hanako_ja", "smart_tag_stimm_power_a_", loc_hanako, "ja_loc_ogryn_a__smart_tag_stimm_power_a_", 4):add_subtext("欧格林", {"红针！", "红色的水！", "喝了变强！", "力量针！"})
E:add_audio("ogryn", "hanako_ja", "smart_tag_stimm_speed_a_", loc_hanako, "ja_loc_ogryn_a__smart_tag_stimm_speed_a_", 4):add_subtext("欧格林", {"蓝针！", "跑得快的针！", "蓝色水水！", "加速针！"})
E:add_audio("ogryn", "hanako_ja", "smart_tag_stimm_concentration_a_", loc_hanako, "ja_loc_ogryn_a__smart_tag_stimm_concentration_a_", 4):add_subtext("欧格林", {"黄针！", "聪明的针！", "黄色水水！", "专注针！"})
E:add_audio("ogryn", "hanako_ja", "smart_tag_vo_small_grenade_", loc_hanako, "ja_loc_ogryn_a__smart_tag_vo_small_grenade_", 3):add_subtext("欧格林", {"小石头炸弹！", "拿手雷！", "炸弹盒子！"})
E:add_audio("ogryn", "hanako_ja", "calling_for_help_", loc_hanako, "ja_loc_ogryn_a__calling_for_help_", 3):add_subtext("欧格林", {"快来帮帮俺！", "俺遇到麻烦了！", "救命！"})
E:add_audio("ogryn", "hanako_ja", "response_for_calling_for_help_", loc_hanako, "ja_loc_ogryn_a__response_for_calling_for_help_", 3):add_subtext("欧格林", {"俺来了！", "别怕，大个子来了！", "撑住！"})
E:add_audio("ogryn", "hanako_ja", "response_for_zealot_critical_health_", loc_hanako, "ja_loc_ogryn_a__response_for_zealot_critical_health_", 3):add_subtext("欧格林", {"叫花子快死了！", "去吃药！", "别死啊小个子！"})
E:add_audio("ogryn", "hanako_ja", "response_for_veteran_critical_health_", loc_hanako, "ja_loc_ogryn_a__response_for_veteran_critical_health_", 3):add_subtext("欧格林", {"老兵快死了！", "去吃药！", "别死啊小个子！"})
E:add_audio("ogryn", "hanako_ja", "response_for_psyker_critical_health_", loc_hanako, "ja_loc_ogryn_a__response_for_psyker_critical_health_", 3):add_subtext("欧格林", {"怪人快死了！", "去吃药！", "别死啊小个子！"})
E:add_audio("ogryn", "hanako_ja", "response_for_ogryn_critical_health_", loc_hanako, "ja_loc_ogryn_a__response_for_ogryn_critical_health_", 3):add_subtext("欧格林", {"大块头快死了！", "去吃药！", "挺住啊兄弟！"})
E:add_audio("ogryn", "hanako_ja", "response_for_adamant_critical_health_", loc_hanako, "ja_loc_ogryn_a__response_for_adamant_critical_health_", 3):add_subtext("欧格林", {"长官快死了！", "长官需要治伤！", "保护长官！"})
E:add_audio("ogryn", "hanako_ja", "knocked_down_multiple_times_zealot_", loc_hanako, "ja_loc_ogryn_a__knocked_down_multiple_times_zealot_", 3):add_subtext("欧格林", {"叫花子又躺了！", "快起来！", "俺去拉你！"})
E:add_audio("ogryn", "hanako_ja", "knocked_down_multiple_times_veteran_", loc_hanako, "ja_loc_ogryn_a__knocked_down_multiple_times_veteran_", 3):add_subtext("欧格林", {"老兵又躺了！", "快起来！", "俺去拉你！"})
E:add_audio("ogryn", "hanako_ja", "knocked_down_multiple_times_psyker_", loc_hanako, "ja_loc_ogryn_a__knocked_down_multiple_times_psyker_", 3):add_subtext("欧格林", {"怪人又躺了！", "快起来！", "俺去拉你！"})
E:add_audio("ogryn", "hanako_ja", "knocked_down_multiple_times_ogryn_", loc_hanako, "ja_loc_ogryn_a__knocked_down_multiple_times_ogryn_", 3):add_subtext("欧格林", {"大块头又躺了！", "快起来！", "俺去拉你！"})
E:add_audio("ogryn", "hanako_ja", "knocked_down_multiple_times_adamant_", loc_hanako, "ja_loc_ogryn_a__knocked_down_multiple_times_adamant_", 3):add_subtext("欧格林", {"长官又躺了！", "长官快起来！", "俺去拉长官！"})
E:add_audio("ogryn", "hanako_ja", "player_death_zealot_", loc_hanako, "ja_loc_ogryn_a__player_death_zealot_", 2):add_subtext("欧格林", {"小个子死了！", "叫花子没了！"})
E:add_audio("ogryn", "hanako_ja", "player_death_veteran_", loc_hanako, "ja_loc_ogryn_a__player_death_veteran_", 2):add_subtext("欧格林", {"小个子死了！", "老兵没了！"})
E:add_audio("ogryn", "hanako_ja", "player_death_psyker_", loc_hanako, "ja_loc_ogryn_a__player_death_psyker_", 2):add_subtext("欧格林", {"小个子死了！", "怪人没了！"})
E:add_audio("ogryn", "hanako_ja", "player_death_ogryn_", loc_hanako, "ja_loc_ogryn_a__player_death_ogryn_", 2):add_subtext("欧格林", {"大块头死了！", "兄弟没了！"})
E:add_audio("ogryn", "hanako_ja", "player_death_adamant_", loc_hanako, "ja_loc_ogryn_a__player_death_adamant_", 2):add_subtext("欧格林", {"长官死了！", "不！长官没了！"})
E:add_audio("ogryn", "hanako_ja", "pinned_by_enemies_", loc_hanako, "ja_loc_ogryn_a__pinned_by_enemies_", 4):add_subtext("欧格林", {"打得俺抬不起头！", "子弹太多了！", "快躲起来！", "俺被打中了！"})
E:add_audio("ogryn", "hanako_ja", "response_for_pinned_by_enemies_zealot_", loc_hanako, "ja_loc_ogryn_a__response_for_pinned_by_enemies_zealot_", 3):add_subtext("欧格林", {"躲起来，小个子！", "找掩体！", "别被打成筛子！"})
E:add_audio("ogryn", "hanako_ja", "response_for_pinned_by_enemies_veteran_", loc_hanako, "ja_loc_ogryn_a__response_for_pinned_by_enemies_veteran_", 3):add_subtext("欧格林", {"躲起来，小个子！", "找掩体！", "别被打成筛子！"})
E:add_audio("ogryn", "hanako_ja", "response_for_pinned_by_enemies_psyker_", loc_hanako, "ja_loc_ogryn_a__response_for_pinned_by_enemies_psyker_", 3):add_subtext("欧格林", {"躲起来，小个子！", "找掩体！", "别被打成筛子！"})
E:add_audio("ogryn", "hanako_ja", "response_for_pinned_by_enemies_ogryn_", loc_hanako, "ja_loc_ogryn_a__response_for_pinned_by_enemies_ogryn_", 3):add_subtext("欧格林", {"躲起来，大块头！", "找掩体！", "找块大石头躲！"})
E:add_audio("ogryn", "hanako_ja", "response_for_zealot_cover_me_", loc_hanako, "ja_loc_ogryn_a__response_for_zealot_cover_me_", 3):add_subtext("欧格林", {"俺来挡着！", "站俺后面！", "掩护你！"})
E:add_audio("ogryn", "hanako_ja", "response_for_veteran_cover_me_", loc_hanako, "ja_loc_ogryn_a__response_for_veteran_cover_me_", 3):add_subtext("欧格林", {"俺来挡着！", "站俺后面！", "掩护你！"})
E:add_audio("ogryn", "hanako_ja", "response_for_psyker_cover_me_", loc_hanako, "ja_loc_ogryn_a__response_for_psyker_cover_me_", 3):add_subtext("欧格林", {"俺来挡着！", "站俺后面！", "掩护你！"})
E:add_audio("ogryn", "hanako_ja", "response_for_ogryn_cover_me_", loc_hanako, "ja_loc_ogryn_a__response_for_ogryn_cover_me_", 3):add_subtext("欧格林", {"俺来挡着！", "兄弟掩护你！", "交给俺！"})
E:add_audio("ogryn", "hanako_ja", "conversation_combat_chaos_spawn_chew_a_", loc_hanako, "ja_loc_ogryn_a__conversation_combat_chaos_spawn_chew_a_", 3):add_subtext("欧格林", {"把它打下来！", "放开他！", "打大怪兽！"})
E:add_audio("ogryn", "hanako_ja", "conversation_combat_chaos_spawn_chew_b_", loc_hanako, "ja_loc_ogryn_a__conversation_combat_chaos_spawn_chew_b_", 3):add_subtext("欧格林", {"把它打下来！", "放开他！", "打大怪兽！"})
E:add_audio("ogryn", "hanako_ja", "conversation_combat_chaos_spawn_chew_c_", loc_hanako, "ja_loc_ogryn_a__conversation_combat_chaos_spawn_chew_c_", 3):add_subtext("欧格林", {"把它打下来！", "放开他！", "打大怪兽！"})
E:add_audio("ogryn", "hanako_ja", "vce_hurt_heavy", play_hanako, "play_ogryn_a__vce_hurt_heavy", 3):set_priority(1)
E:add_audio("ogryn", "hanako_ja", "vce_catapulted", play_hanako, "play_ogryn_a__vce_catapulted", 3):set_priority(2)
E:add_audio("ogryn", "hanako_ja", "vce_catapulted_land", play_hanako, "play_ogryn_a__vce_catapulted_land", 1):set_priority(4)
E:add_audio("ogryn", "hanako_ja", "vce_scream_long", play_hanako, "play_ogryn_a__vce_scream_long", 3):set_priority(2)
E:add_audio("ogryn", "hanako_ja", "vce_hurt_light", play_hanako, "play_ogryn_a__vce_hurt_light", 3):set_priority(4)
E:add_audio("ogryn", "hanako_ja", "vce_jump", play_hanako, "play_ogryn_a__vce_jump", 1):set_priority(4)
E:add_audio("ogryn", "hanako_ja", "vce_land_heavy", play_hanako, "play_ogryn_a__vce_land_heavy", 1):set_priority(4)
E:add_audio("ogryn", "hanako_ja", "vce_grunt_short", play_hanako, "play_ogryn_a__vce_grunt_short", 15):set_priority(4)
E:add_audio("ogryn", "hanako_ja", "vce_attack_short", play_hanako, "play_ogryn_a__vce_attack_short", 15):set_priority(4)
E:add_audio("ogryn", "hanako_ja", "vce_attack_long", play_hanako, "play_ogryn_a__vce_attack_long", 16):set_priority(4)
E:add_audio("ogryn", "hanako_ja", "vce_coughing", play_hanako, "play_ogryn_a__vce_coughing", 1):set_priority(4)
E:add_audio("ogryn", "hanako_ja", "vce_getting_up", play_hanako, "play_ogryn_a__vce_getting_up", 1):set_priority(4)
E:add_audio("ogryn", "hanako_ja", "vce_struggle_heavy", play_hanako, "play_ogryn_a__vce_struggle_heavy", 1):set_priority(4)
E:add_audio("ogryn", "hanako_ja", "play_hud_heal_2d", play_hanako, "play_ogryn_a__vce_healing", 4, nil, "play_hud_heal_2d")
E:add_audio("ogryn", "hanako_ja", "play_syringe_power_start", play_hanako, "play_syringe_power_start", 1, nil, "play_syringe_power_start"):set_priority(0)
E:add_audio("ogryn", "hanako_ja", "play_syringe_ability_start", play_hanako, "play_syringe_ability_start", 1, nil, "play_syringe_ability_start"):set_priority(0)
E:add_audio("ogryn", "hanako_ja", "play_syringe_speed_start", play_hanako, "play_syringe_speed_start", 1, nil, "play_syringe_speed_start"):set_priority(0)