-- 【灵能者】【通用版】
local loc_EmaPsyker = "loc_psyker_male_c/EmaPsyker/"
local play_EmaPsyker = "wwise/events/player/play_psyker_male_c/EmaPsyker"
E:set_class("psyker", "EmaPsyker_ja", "通用灵能者(日语)"):old_version()

E:add_audio("psyker", "EmaPsyker_ja", "guidance_correct_path_", loc_EmaPsyker, "ja_loc_psyker_male_c__guidance_correct_path_", 4):add_subtext("灵能者", {"走这边，路是对的。", "跟我来。", "这是正确的路线。", "走这条路。"})
E:add_audio("psyker", "EmaPsyker_ja", "guidance_correct_path_up_", loc_EmaPsyker, "ja_loc_psyker_male_c__guidance_correct_path_up_", 3):add_subtext("灵能者", {"我们要往上走。", "从这里上去。", "上面是正确的路。"})
E:add_audio("psyker", "EmaPsyker_ja", "guidance_correct_path_drop_", loc_EmaPsyker, "ja_loc_psyker_male_c__guidance_correct_path_drop_", 3):add_subtext("灵能者", {"准备跳下去。", "注意安全，我们要下去了。", "下去之后就没有回头路了。"})
E:add_audio("psyker", "EmaPsyker_ja", "stairs_sighted_", loc_EmaPsyker, "ja_loc_psyker_male_c__stairs_sighted_", 2):add_subtext("灵能者", {"这里有楼梯。", "从楼梯走。"})
E:add_audio("psyker", "EmaPsyker_ja", "guidance_starting_area_", loc_EmaPsyker, "ja_loc_psyker_male_c__guidance_starting_area_", 3):add_subtext("灵能者", {"任务开始，保持警惕。", "检查装备，我们出发。", "愿帝皇指引我们。"})
E:add_audio("psyker", "EmaPsyker_ja", "region_carnival_a_", loc_EmaPsyker, "ja_loc_psyker_male_c__region_carnival_a_", 2):add_subtext("灵能者", {"这里的环境充斥着腐败的气息。", "保持警惕，这里不安全。"})
E:add_audio("psyker", "EmaPsyker_ja", "info_event_det_pack_a_", loc_EmaPsyker, "ja_loc_psyker_male_c__info_event_det_pack_a_", 3):add_subtext("灵能者", {"准备好炸药了。", "开始爆破作业。", "准备起爆。"})
E:add_audio("psyker", "EmaPsyker_ja", "event_survive_keep_coming_a_", loc_EmaPsyker, "ja_loc_psyker_male_c__event_survive_keep_coming_a_", 3):add_subtext("灵能者", {"异端越来越多了！", "坚守阵地！", "不要退缩，迎击敌人！"})
E:add_audio("psyker", "EmaPsyker_ja", "event_demolition_first_corruptor_destroyed_a_", loc_EmaPsyker, "ja_loc_psyker_male_c__event_demolition_first_corruptor_destroyed_a_", 3):add_subtext("灵能者", {"腐化之源已被清除。", "干得好，继续推进。", "污秽已消灭。"})
E:add_audio("psyker", "EmaPsyker_ja", "event_survive_almost_done_", loc_EmaPsyker, "ja_loc_psyker_male_c__event_survive_almost_done_", 3):add_subtext("灵能者", {"快结束了，坚持住！", "敌人溃退了！", "胜利就在眼前！"})
E:add_audio("psyker", "EmaPsyker_ja", "info_event_one_down_", loc_EmaPsyker, "ja_loc_psyker_male_c__info_event_one_down_", 3):add_subtext("灵能者", {"目标达成一个。", "继续保持，完成了一个。", "干得漂亮。"})
E:add_audio("psyker", "EmaPsyker_ja", "response_to_hacking_fix_decode_", loc_EmaPsyker, "ja_loc_psyker_male_c__response_to_hacking_fix_decode_", 3):add_subtext("灵能者", {"解码器出故障了，快修理！", "需要重新接线！", "谁来修一下这个机器！"})
E:add_audio("psyker", "EmaPsyker_ja", "info_event_almost_done_", loc_EmaPsyker, "ja_loc_psyker_male_c__info_event_almost_done_", 3):add_subtext("灵能者", {"快结束了，坚持住！", "敌人溃散了！", "挺住，我们快成功了！"})
E:add_audio("psyker", "EmaPsyker_ja", "warning_exploding_barrel_", loc_EmaPsyker, "ja_loc_psyker_male_c__warning_exploding_barrel_", 3):add_subtext("灵能者", {"小心爆炸物！", "远离那个炸药桶！", "注意油桶！"})
E:add_audio("psyker", "EmaPsyker_ja", "response_rechargable_for_look_at_healthstation_", loc_EmaPsyker, "ja_loc_psyker_male_c__response_rechargable_for_look_at_healthstation_", 2):add_subtext("灵能者", {"医疗站没电了。", "需要电源才能使用医疗站。"})
E:add_audio("psyker", "EmaPsyker_ja", "smart_tag_vo_station_health_", loc_EmaPsyker, "ja_loc_psyker_male_c__smart_tag_vo_station_health_", 3):add_subtext("灵能者", {"这里有医疗站。", "需要治疗的过来。", "发现医疗站。"})

E:add_audio("psyker", "EmaPsyker_ja", "ability_protectorate_start_", loc_EmaPsyker, "ja_loc_psyker_male_c__ability_protectorate_start_", 5, 4):add_subtext("灵能者", {"灵能护盾展开！", "退后！", "休想靠近！", "保护阵型！", "感受亚空间的力量！"}):set_priority(2)
E:add_audio("psyker", "EmaPsyker_ja", "ability_buff_stance_a_", loc_EmaPsyker, "ja_loc_psyker_male_c__ability_buff_stance_a_", 5, 4):add_subtext("灵能者", {"力量涌现！", "消灭异端！", "为了帝皇！", "绝不退缩！", "迎接你们的毁灭！"}):set_priority(2)
E:add_audio("psyker", "EmaPsyker_ja", "ability_biomancer_low_", loc_EmaPsyker, "ja_loc_psyker_male_c__ability_biomancer_low_", 5, 4):add_subtext("灵能者", {"受死吧！", "滚开！", "异端！", "燃烧吧！", "去死！"}):set_priority(2)
E:add_audio("psyker", "EmaPsyker_ja", "ability_biomancer_high_", loc_EmaPsyker, "ja_loc_psyker_male_c__ability_biomancer_high_", 5, 4):add_subtext("灵能者", {"在亚空间的怒火中灰飞烟灭！", "化为灰烬！", "直视深渊吧！", "接受制裁！", "毁灭！"}):set_priority(2)
E:add_audio("psyker", "EmaPsyker_ja", "ability_venting_", loc_EmaPsyker, "ja_loc_psyker_male_c__ability_venting_", 5, 5):add_subtext("灵能者", {"亚空间在躁动！", "需要释放压力！", "我的头要裂开了！", "控制不住了！", "必须冷静！"})

E:add_audio("psyker", "EmaPsyker_ja", "com_wheel_vo_location_ping_", loc_EmaPsyker, "ja_loc_psyker_male_c__com_wheel_vo_location_ping_", 4):add_subtext("灵能者", {"来这里！", "在这个位置。", "往这边走。", "快跟上！"}):set_priority(1)
E:add_audio("psyker", "EmaPsyker_ja", "com_wheel_vo_location_attention_", loc_EmaPsyker, "ja_loc_psyker_male_c__com_wheel_vo_location_attention_", 4):add_subtext("灵能者", {"看那边！", "注意那里。", "发现目标。", "当心那个位置。"})
E:add_audio("psyker", "EmaPsyker_ja", "com_wheel_vo_yes_", loc_EmaPsyker, "ja_loc_psyker_male_c__com_wheel_vo_yes_", 5):add_subtext("灵能者", {"收到。", "明白。", "确认。", "好的。", "没问题。"})
E:add_audio("psyker", "EmaPsyker_ja", "com_wheel_vo_no_", loc_EmaPsyker, "ja_loc_psyker_male_c__com_wheel_vo_no_", 4):add_subtext("灵能者", {"不行。", "拒绝。", "做不到。", "否定。"})
E:add_audio("psyker", "EmaPsyker_ja", "com_wheel_vo_enemy_over_here_", loc_EmaPsyker, "ja_loc_psyker_male_c__com_wheel_vo_enemy_over_here_", 3):add_subtext("灵能者", {"这里有敌人。", "注意，前方有敌情。", "准备接敌！"})
E:add_audio("psyker", "EmaPsyker_ja", "com_wheel_vo_thank_you_", loc_EmaPsyker, "ja_loc_psyker_male_c__com_wheel_vo_thank_you_", 3):add_subtext("灵能者", {"谢谢。", "感谢支援。", "多谢。"})
E:add_audio("psyker", "EmaPsyker_ja", "com_wheel_vo_need_ammo_", loc_EmaPsyker, "ja_loc_psyker_male_c__com_wheel_vo_need_ammo_", 3):add_subtext("灵能者", {"我需要弹药！", "弹药耗尽，请求补给。", "谁有备用弹药？"})
E:add_audio("psyker", "EmaPsyker_ja", "com_wheel_vo_need_health_", loc_EmaPsyker, "ja_loc_psyker_male_c__com_wheel_vo_need_health_", 3):add_subtext("灵能者", {"我需要医疗支援！", "状态不佳，需要治疗！", "请求医疗包！"})
E:add_audio("psyker", "EmaPsyker_ja", "com_wheel_vo_for_the_emperor_", loc_EmaPsyker, "ja_loc_psyker_male_c__com_wheel_vo_for_the_emperor_", 5, 8):add_subtext("灵能者", {"为了帝皇！", "帝皇庇护着我们！", "以黄金王座之名！", "消灭异端，为了帝皇！", "帝皇之光指引我们！"}):set_priority(2)
E:add_audio("psyker", "EmaPsyker_ja", "com_wheel_vo_follow_you_", loc_EmaPsyker, "ja_loc_psyker_male_c__com_wheel_vo_follow_you_", 4):add_subtext("灵能者", {"我跟着你。", "带路吧。", "掩护你前进。", "跟在你后面。"})

E:add_audio("psyker", "EmaPsyker_ja", "reloading_", loc_EmaPsyker, "ja_loc_psyker_male_c__reloading_", 3):add_subtext("灵能者", {"正在冷却！", "掩护我，需要调整！", "武器冷却中！"})
E:add_audio("psyker", "EmaPsyker_ja", "look_at_grenade_", loc_EmaPsyker, "ja_loc_psyker_male_c__look_at_grenade_", 2):add_subtext("灵能者", {"发现手雷。", "这里有爆炸物补给。"})
E:add_audio("psyker", "EmaPsyker_ja", "look_at_healthstation_", loc_EmaPsyker, "ja_loc_psyker_male_c__look_at_healthstation_", 2):add_subtext("灵能者", {"发现医疗站。", "前面可以治疗。"})
E:add_audio("psyker", "EmaPsyker_ja", "smart_tag_vo_pickup_deployed_medical_crate_", loc_EmaPsyker, "ja_loc_psyker_male_c__smart_tag_vo_pickup_deployed_medical_crate_", 2):add_subtext("灵能者", {"这里部署了医疗箱。", "过来治疗！"})
E:add_audio("psyker", "EmaPsyker_ja", "smart_tag_vo_pickup_deployed_ammo_crate_", loc_EmaPsyker, "ja_loc_psyker_male_c__smart_tag_vo_pickup_deployed_ammo_crate_", 2):add_subtext("灵能者", {"弹药箱已部署。", "补充弹药！"})
E:add_audio("psyker", "EmaPsyker_ja", "smart_tag_vo_pickup_ammo_", loc_EmaPsyker, "ja_loc_psyker_male_c__smart_tag_vo_pickup_ammo_", 2):add_subtext("灵能者", {"这里有弹药。", "发现弹药补给。"})
E:add_audio("psyker", "EmaPsyker_ja", "smart_tag_vo_pickup_health_booster_", loc_EmaPsyker, "ja_loc_psyker_male_c__smart_tag_vo_pickup_health_booster_", 2):add_subtext("灵能者", {"发现医疗针。", "这里有急救针。"})
E:add_audio("psyker", "EmaPsyker_ja", "smart_tag_vo_pickup_forge_metal_", loc_EmaPsyker, "ja_loc_psyker_male_c__smart_tag_vo_pickup_forge_metal_", 2):add_subtext("灵能者", {"发现塑钢。", "有制作材料。"})
E:add_audio("psyker", "EmaPsyker_ja", "smart_tag_vo_pickup_platinum_", loc_EmaPsyker, "ja_loc_psyker_male_c__smart_tag_vo_pickup_platinum_", 2):add_subtext("灵能者", {"发现塑钢。", "有制作材料。"})
E:add_audio("psyker", "EmaPsyker_ja", "smart_tag_vo_pickup_small_grenade_", loc_EmaPsyker, "ja_loc_psyker_male_c__smart_tag_vo_pickup_small_grenade_", 1):add_subtext("灵能者", {"发现手雷补给。"})

E:add_audio("psyker", "EmaPsyker_ja", "cover_me_", loc_EmaPsyker, "ja_loc_psyker_male_c__cover_me_", 3):add_subtext("灵能者", {"掩护我！", "请求火力掩护！", "保护我的侧翼！"})
E:add_audio("psyker", "EmaPsyker_ja", "away_from_squad_", loc_EmaPsyker, "ja_loc_psyker_male_c__away_from_squad_", 3):add_subtext("灵能者", {"我脱离队伍了。", "我需要归队。", "不要单独行动。"})
E:add_audio("psyker", "EmaPsyker_ja", "come_back_to_squad_", loc_EmaPsyker, "ja_loc_psyker_male_c__come_back_to_squad_", 3):add_subtext("灵能者", {"回到队伍中来！", "不要掉队！", "保持阵型！"})

E:add_audio("psyker", "EmaPsyker_ja", "psyker_seen_killstreak_psyker_", loc_EmaPsyker, "ja_loc_psyker_male_c__psyker_seen_killstreak_psyker_", 5, 5):add_subtext("灵能者", {"干得好！", "完美的击杀！", "异端就该被这样消灭！", "帝皇会为你骄傲的。", "完美的连击！"}):set_priority(2)
E:add_audio("psyker", "EmaPsyker_ja", "psyker_seen_killstreak_zealot_", loc_EmaPsyker, "ja_loc_psyker_male_c__psyker_seen_killstreak_zealot_", 5, 5):add_subtext("灵能者", {"干得好！", "完美的击杀！", "异端就该被这样消灭！", "帝皇会为你骄傲的。", "完美的连击！"}):set_priority(2)
E:add_audio("psyker", "EmaPsyker_ja", "psyker_seen_killstreak_veteran_", loc_EmaPsyker, "ja_loc_psyker_male_c__psyker_seen_killstreak_veteran_", 5, 5):add_subtext("灵能者", {"干得好！", "完美的击杀！", "异端就该被这样消灭！", "帝皇会为你骄傲的。", "完美的连击！"}):set_priority(2)
E:add_audio("psyker", "EmaPsyker_ja", "psyker_seen_killstreak_ogryn_", loc_EmaPsyker, "ja_loc_psyker_male_c__psyker_seen_killstreak_ogryn_", 5, 5):add_subtext("灵能者", {"干得好！", "完美的击杀！", "异端就该被这样消灭！", "帝皇会为你骄傲的。", "完美的连击！"}):set_priority(2)
E:add_audio("psyker", "EmaPsyker_ja", "psyker_seen_killstreak_adamant_", loc_EmaPsyker, "ja_loc_psyker_male_c__psyker_seen_killstreak_adamant_", 5, 5):add_subtext("灵能者", {"干得好！", "完美的击杀！", "异端就该被这样消灭！", "帝皇会为你骄傲的。", "完美的连击！"}):set_priority(2)

E:add_audio("psyker", "EmaPsyker_ja", "response_for_zealot_seen_killstreak_psyker_", loc_EmaPsyker, "ja_loc_psyker_male_c__response_for_zealot_seen_killstreak_psyker_", 5, 5):add_subtext("灵能者", {"这是亚空间的怒火。", "理所应当的结果。", "感谢夸奖。", "这不过是小试牛刀。", "灵能的伟力不容质疑。"}):set_priority(2)
E:add_audio("psyker", "EmaPsyker_ja", "response_for_veteran_seen_killstreak_psyker_", loc_EmaPsyker, "ja_loc_psyker_male_c__response_for_veteran_seen_killstreak_psyker_", 5, 5):add_subtext("灵能者", {"这是亚空间的怒火。", "理所应当的结果。", "感谢夸奖。", "这不过是小试牛刀。", "灵能的伟力不容质疑。"}):set_priority(2)
E:add_audio("psyker", "EmaPsyker_ja", "response_for_psyker_seen_killstreak_psyker_", loc_EmaPsyker, "ja_loc_psyker_male_c__response_for_psyker_seen_killstreak_psyker_", 5, 5):add_subtext("灵能者", {"这是亚空间的怒火。", "理所应当的结果。", "感谢夸奖。", "这不过是小试牛刀。", "灵能的伟力不容质疑。"}):set_priority(2)
E:add_audio("psyker", "EmaPsyker_ja", "response_for_ogryn_seen_killstreak_psyker_", loc_EmaPsyker, "ja_loc_psyker_male_c__response_for_ogryn_seen_killstreak_psyker_", 5, 5):add_subtext("灵能者", {"这是亚空间的怒火。", "理所应当的结果。", "感谢夸奖。", "这不过是小试牛刀。", "灵能的伟力不容质疑。"}):set_priority(2)
E:add_audio("psyker", "EmaPsyker_ja", "response_for_adamant_seen_killstreak_psyker_", loc_EmaPsyker, "ja_loc_psyker_male_c__response_for_adamant_seen_killstreak_psyker_", 5, 5):add_subtext("灵能者", {"这是亚空间的怒火。", "理所应当的结果。", "感谢夸奖。", "这不过是小试牛刀。", "灵能的伟力不容质疑。"}):set_priority(2)

E:add_audio("psyker", "EmaPsyker_ja", "response_for_friendly_fire_from_zealot_", loc_EmaPsyker, "ja_loc_psyker_male_c__response_for_friendly_fire_from_zealot_", 5):add_subtext("灵能者", {"注意你的射击线！", "你打到我了！", "小心点，开火前看清楚！", "友军火力！", "停火，我是友军！"})
E:add_audio("psyker", "EmaPsyker_ja", "response_for_friendly_fire_from_veteran_", loc_EmaPsyker, "ja_loc_psyker_male_c__response_for_friendly_fire_from_veteran_", 5):add_subtext("灵能者", {"注意你的射击线！", "你打到我了！", "小心点，开火前看清楚！", "友军火力！", "停火，我是友军！"})
E:add_audio("psyker", "EmaPsyker_ja", "response_for_friendly_fire_from_psyker_", loc_EmaPsyker, "ja_loc_psyker_male_c__response_for_friendly_fire_from_psyker_", 5):add_subtext("灵能者", {"注意你的射击线！", "你打到我了！", "小心点，开火前看清楚！", "友军火力！", "停火，我是友军！"})
E:add_audio("psyker", "EmaPsyker_ja", "response_for_friendly_fire_from_ogryn_", loc_EmaPsyker, "ja_loc_psyker_male_c__response_for_friendly_fire_from_ogryn_", 5):add_subtext("灵能者", {"注意你的射击线！", "你打到我了！", "小心点，开火前看清楚！", "友军火力！", "停火，我是友军！"})
E:add_audio("psyker", "EmaPsyker_ja", "response_for_friendly_fire_from_adamant_", loc_EmaPsyker, "ja_loc_psyker_male_c__response_for_friendly_fire_from_adamant_", 5):add_subtext("灵能者", {"注意你的射击线！", "你打到我了！", "小心点，开火前看清楚！", "友军火力！", "停火，我是友军！"})

E:add_audio("psyker", "EmaPsyker_ja", "friendly_fire_from_zealot_to_psyker_", loc_EmaPsyker, "ja_loc_psyker_male_c__friendly_fire_from_zealot_to_psyker_", 5):add_subtext("灵能者", {"注意你的火力！", "别朝我开枪！", "看着点打！", "小心误伤！", "停火！"})
E:add_audio("psyker", "EmaPsyker_ja", "friendly_fire_from_veteran_to_psyker_", loc_EmaPsyker, "ja_loc_psyker_male_c__friendly_fire_from_veteran_to_psyker_", 5):add_subtext("灵能者", {"注意你的火力！", "别朝我开枪！", "看着点打！", "小心误伤！", "停火！"})
E:add_audio("psyker", "EmaPsyker_ja", "friendly_fire_from_psyker_to_psyker_", loc_EmaPsyker, "ja_loc_psyker_male_c__friendly_fire_from_psyker_to_psyker_", 5):add_subtext("灵能者", {"注意你的火力！", "别朝我开枪！", "看着点打！", "小心误伤！", "停火！"})
E:add_audio("psyker", "EmaPsyker_ja", "friendly_fire_from_ogryn_to_psyker_", loc_EmaPsyker, "ja_loc_psyker_male_c__friendly_fire_from_ogryn_to_psyker_", 5):add_subtext("灵能者", {"注意你的火力！", "别朝我开枪！", "看着点打！", "小心误伤！", "停火！"})
E:add_audio("psyker", "EmaPsyker_ja", "friendly_fire_from_adamant_to_psyker_", loc_EmaPsyker, "ja_loc_psyker_male_c__friendly_fire_from_adamant_to_psyker_", 5):add_subtext("灵能者", {"注意你的火力！", "别朝我开枪！", "看着点打！", "小心误伤！", "停火！"})

E:add_audio("psyker", "EmaPsyker_ja", "head_shot_", loc_EmaPsyker, "ja_loc_psyker_male_c__head_shot_", 3):add_subtext("灵能者", {"精准的爆头。", "一击致命。", "完美的准星。"})

E:add_audio("psyker", "EmaPsyker_ja", "response_for_zealot_disabled_by_enemy_", loc_EmaPsyker, "ja_loc_psyker_male_c__response_for_zealot_disabled_by_enemy_", 3):add_subtext("灵能者", {"有队友被控制了！", "去救人！", "队友需要帮助！"})
E:add_audio("psyker", "EmaPsyker_ja", "response_for_veteran_disabled_by_enemy_", loc_EmaPsyker, "ja_loc_psyker_male_c__response_for_veteran_disabled_by_enemy_", 3):add_subtext("灵能者", {"有队友被控制了！", "去救人！", "队友需要帮助！"})
E:add_audio("psyker", "EmaPsyker_ja", "response_for_psyker_disabled_by_enemy_", loc_EmaPsyker, "ja_loc_psyker_male_c__response_for_psyker_disabled_by_enemy_", 3):add_subtext("灵能者", {"有队友被控制了！", "去救人！", "队友需要帮助！"})
E:add_audio("psyker", "EmaPsyker_ja", "response_for_ogryn_disabled_by_enemy_", loc_EmaPsyker, "ja_loc_psyker_male_c__response_for_ogryn_disabled_by_enemy_", 3):add_subtext("灵能者", {"有队友被控制了！", "去救人！", "队友需要帮助！"})

E:add_audio("psyker", "EmaPsyker_ja", "psyker_start_revive_zealot_", loc_EmaPsyker, "ja_loc_psyker_male_c__psyker_start_revive_zealot_", 3):add_subtext("灵能者", {"坚持住，我来救你。", "站起来，战斗还没结束。", "帝皇不允许你倒下。"})
E:add_audio("psyker", "EmaPsyker_ja", "psyker_start_revive_veteran_", loc_EmaPsyker, "ja_loc_psyker_male_c__psyker_start_revive_veteran_", 3):add_subtext("灵能者", {"坚持住，我来救你。", "站起来，战斗还没结束。", "帝皇不允许你倒下。"})
E:add_audio("psyker", "EmaPsyker_ja", "psyker_start_revive_psyker_", loc_EmaPsyker, "ja_loc_psyker_male_c__psyker_start_revive_psyker_", 3):add_subtext("灵能者", {"坚持住，我来救你。", "站起来，战斗还没结束。", "帝皇不允许你倒下。"})
E:add_audio("psyker", "EmaPsyker_ja", "psyker_start_revive_ogryn_", loc_EmaPsyker, "ja_loc_psyker_male_c__psyker_start_revive_ogryn_", 3):add_subtext("灵能者", {"坚持住，我来救你。", "站起来，战斗还没结束。", "帝皇不允许你倒下。"})
E:add_audio("psyker", "EmaPsyker_ja", "psyker_start_revive_adamant_", loc_EmaPsyker, "ja_loc_psyker_male_c__psyker_start_revive_adamant_", 3):add_subtext("灵能者", {"坚持住，我来救你。", "站起来，战斗还没结束。", "帝皇不允许你倒下。"})

E:add_audio("psyker", "EmaPsyker_ja", "combat_pause_one_liner_", loc_EmaPsyker, "ja_loc_psyker_male_c__combat_pause_one_liner_", 4):add_subtext("灵能者", {"保持警惕，这里可能有埋伏。", "稍作休息，检查装备。", "亚空间的低语从未停止。", "不要放松警惕。"})

E:add_audio("psyker", "EmaPsyker_ja", "surrounded_", loc_EmaPsyker, "ja_loc_psyker_male_c__surrounded_", 3):add_subtext("灵能者", {"我被包围了！", "敌人太多了！", "需要支援，我被困住了！"})
E:add_audio("psyker", "EmaPsyker_ja", "surrounded_response_", loc_EmaPsyker, "ja_loc_psyker_male_c__surrounded_response_", 3):add_subtext("灵能者", {"撑住，我们来了！", "坚持住！", "向我们靠拢！"})
E:add_audio("psyker", "EmaPsyker_ja", "heard_horde_vector_", loc_EmaPsyker, "ja_loc_psyker_male_c__heard_horde_vector_", 4):add_subtext("灵能者", {"尸潮来了！", "准备迎接冲击！", "大量敌人正在靠近！", "结成防御阵型！"})
E:add_audio("psyker", "EmaPsyker_ja", "heard_horde_ambush_", loc_EmaPsyker, "ja_loc_psyker_male_c__heard_horde_ambush_", 4):add_subtext("灵能者", {"有埋伏！", "敌人突袭！", "准备迎击！", "保护侧翼！"})

E:add_audio("psyker", "EmaPsyker_ja", "heard_enemy_beast_of_nurgle_", loc_EmaPsyker, "ja_loc_psyker_male_c__heard_enemy_beast_of_nurgle_", 4):add_subtext("灵能者", {"听到怪兽的声音了！", "有巨型异端在附近！", "保持警惕，有大家伙要来了！", "这股震动...是怪物！"})
E:add_audio("psyker", "EmaPsyker_ja", "heard_enemy_chaos_spawn_", loc_EmaPsyker, "ja_loc_psyker_male_c__heard_enemy_chaos_spawn_", 4):add_subtext("灵能者", {"听到怪兽的声音了！", "有巨型异端在附近！", "保持警惕，有大家伙要来了！", "这股震动...是怪物！"})
E:add_audio("psyker", "EmaPsyker_ja", "heard_enemy_plague_ogryn_", loc_EmaPsyker, "ja_loc_psyker_male_c__heard_enemy_plague_ogryn_", 4):add_subtext("灵能者", {"听到怪兽的声音了！", "有巨型异端在附近！", "保持警惕，有大家伙要来了！", "这股震动...是怪物！"})

E:add_audio("psyker", "EmaPsyker_ja", "conversation_plague_ogryn_weakpoint_01_", loc_EmaPsyker, "ja_loc_psyker_male_c__conversation_plague_ogryn_weakpoint_01_", 3):add_subtext("灵能者", {"攻击它的弱点！", "打它的头部！", "集中火力攻击弱点！"})
E:add_audio("psyker", "EmaPsyker_ja", "conversation_beast_of_nurgle_weakpoint_a_", loc_EmaPsyker, "ja_loc_psyker_male_c__conversation_beast_of_nurgle_weakpoint_a_", 3):add_subtext("灵能者", {"攻击它的背部！", "打它的发光处！", "瞄准弱点开火！"})
E:add_audio("psyker", "EmaPsyker_ja", "conversation_beast_of_nurgle_weakpoint_c_", loc_EmaPsyker, "ja_loc_psyker_male_c__conversation_beast_of_nurgle_weakpoint_c_", 3):add_subtext("灵能者", {"攻击它的背部！", "打它的发光处！", "瞄准弱点开火！"})

E:add_audio("psyker", "EmaPsyker_ja", "seen_enemy_plague_ogryn_", loc_EmaPsyker, "ja_loc_psyker_male_c__seen_enemy_plague_ogryn_", 3):add_subtext("灵能者", {"怪兽出现了！", "可怕的巨物来了！", "集火那个畸变体！"})
E:add_audio("psyker", "EmaPsyker_ja", "seen_enemy_beast_of_nurgle_", loc_EmaPsyker, "ja_loc_psyker_male_c__seen_enemy_beast_of_nurgle_", 3):add_subtext("灵能者", {"怪兽出现了！", "可怕的巨物来了！", "集火那个畸变体！"})
E:add_audio("psyker", "EmaPsyker_ja", "seen_enemy_chaos_spawn_", loc_EmaPsyker, "ja_loc_psyker_male_c__seen_enemy_chaos_spawn_", 3):add_subtext("灵能者", {"怪兽出现了！", "可怕的巨物来了！", "集火那个畸变体！"})

E:add_audio("psyker", "EmaPsyker_ja", "smart_tag_vo_enemy_chaos_spawn_a_", loc_EmaPsyker, "ja_loc_psyker_male_c__smart_tag_vo_enemy_chaos_spawn_a_", 3):add_subtext("灵能者", {"混沌卵！", "消灭这个畸变体！", "危险的突变怪物！"})
E:add_audio("psyker", "EmaPsyker_ja", "smart_tag_vo_enemy_chaos_spawn_b_", loc_EmaPsyker, "ja_loc_psyker_male_c__smart_tag_vo_enemy_chaos_spawn_b_", 3):add_subtext("灵能者", {"混沌卵！", "消灭这个畸变体！", "危险的突变怪物！"})
E:add_audio("psyker", "EmaPsyker_ja", "smart_tag_vo_enemy_beast_of_nurgle_", loc_EmaPsyker, "ja_loc_psyker_male_c__smart_tag_vo_enemy_beast_of_nurgle_", 3):add_subtext("灵能者", {"纳垢野兽！", "庞大的腐化怪物！", "恶心的巨物！"})
E:add_audio("psyker", "EmaPsyker_ja", "smart_tag_vo_enemy_plague_ogryn_", loc_EmaPsyker, "ja_loc_psyker_male_c__smart_tag_vo_enemy_plague_ogryn_", 3):add_subtext("灵能者", {"瘟疫欧格林！", "被腐化的欧格林！", "当心它的冲撞！"})

E:add_audio("psyker", "EmaPsyker_ja", "heard_enemy_daemonhost_", loc_EmaPsyker, "ja_loc_psyker_male_c__heard_enemy_daemonhost_", 3):add_subtext("灵能者", {"有恶魔宿主在附近...", "听到那低语了吗？小心。", "关掉手电，附近有恶魔宿主。"})
E:add_audio("psyker", "EmaPsyker_ja", "seen_enemy_daemonhost_", loc_EmaPsyker, "ja_loc_psyker_male_c__seen_enemy_daemonhost_", 3):add_subtext("灵能者", {"发现恶魔宿主，绕开她。", "不要惊动那个恶魔宿主。", "恶魔宿主在前面睡觉。"})
E:add_audio("psyker", "EmaPsyker_ja", "alerted_ememy_daemonhost_", loc_EmaPsyker, "ja_loc_psyker_male_c__alerted_ememy_daemonhost_", 2):add_subtext("灵能者", {"该死，恶魔宿主被惊醒了！", "准备迎战恶魔！"})
E:add_audio("psyker", "EmaPsyker_ja", "smart_tag_vo_enemy_daemonhost_", loc_EmaPsyker, "ja_loc_psyker_male_c__smart_tag_vo_enemy_daemonhost_", 2):add_subtext("灵能者", {"恶魔宿主！", "恶魔化身！"})

E:add_audio("psyker", "EmaPsyker_ja", "monster_fight_start_reaction_", loc_EmaPsyker, "ja_loc_psyker_male_c__monster_fight_start_reaction_", 4, 5):add_subtext("灵能者", {"准备迎战巨兽！", "消灭这个庞然大物！", "集中火力！", "不要退缩！"}):set_priority(2)
E:add_audio("psyker", "EmaPsyker_ja", "enemy_near_death_monster_", loc_EmaPsyker, "ja_loc_psyker_male_c__enemy_near_death_monster_", 3, 4):add_subtext("灵能者", {"怪物快不行了，继续开火！", "它撑不了多久了！", "给它最后一击！"}):set_priority(2)
E:add_audio("psyker", "EmaPsyker_ja", "enemy_kill_monster_", loc_EmaPsyker, "ja_loc_psyker_male_c__enemy_kill_monster_", 4, 5):add_subtext("灵能者", {"怪物倒下了。", "巨兽被消灭了。", "干得好，大家。", "威胁解除。"}):set_priority(2)

E:add_audio("psyker", "EmaPsyker_ja", "heard_enemy_chaos_hound_", loc_EmaPsyker, "ja_loc_psyker_male_c__heard_enemy_chaos_hound_", 3):add_subtext("灵能者", {"听到猎犬的嚎叫了。", "有瘟疫猎犬！小心突袭！", "注意躲避猎犬！"})
E:add_audio("psyker", "EmaPsyker_ja", "seen_enemy_chaos_hound_", loc_EmaPsyker, "ja_loc_psyker_male_c__seen_enemy_chaos_hound_", 3):add_subtext("灵能者", {"猎犬出现了！", "打死那只狗！", "瘟疫猎犬冲过来了！"})
E:add_audio("psyker", "EmaPsyker_ja", "smart_tag_vo_enemy_chaos_hound_", loc_EmaPsyker, "ja_loc_psyker_male_c__smart_tag_vo_enemy_chaos_hound_", 2):add_subtext("灵能者", {"瘟疫猎犬！", "异端猎犬！"})
E:add_audio("psyker", "EmaPsyker_ja", "enemy_kill_chaos_hound_", loc_EmaPsyker, "ja_loc_psyker_male_c__enemy_kill_chaos_hound_", 4):add_subtext("灵能者", {"猎犬被干掉了。", "死狗。", "威胁消灭。", "猎犬已死。"})

E:add_audio("psyker", "EmaPsyker_ja", "seen_netgunner_", loc_EmaPsyker, "ja_loc_psyker_male_c__seen_netgunner_", 3):add_subtext("灵能者", {"发现陷阱手！", "当心捕网！", "干掉那个陷阱兵！"})
E:add_audio("psyker", "EmaPsyker_ja", "seen_netgunner_flee_", loc_EmaPsyker, "ja_loc_psyker_male_c__seen_netgunner_flee_", 2):add_subtext("灵能者", {"陷阱手跑了！", "别让它跑了！"})
E:add_audio("psyker", "EmaPsyker_ja", "smart_tag_vo_enemy_netgunner_", loc_EmaPsyker, "ja_loc_psyker_male_c__smart_tag_vo_enemy_netgunner_", 3):add_subtext("灵能者", {"陷阱手！", "网兵！", "阴险的捕网兵！"})
E:add_audio("psyker", "EmaPsyker_ja", "enemy_kill_netgunner_", loc_EmaPsyker, "ja_loc_psyker_male_c__enemy_kill_netgunner_", 3):add_subtext("灵能者", {"陷阱手已死。", "网兵被解决了。", "再也没有捕网了。"})

E:add_audio("psyker", "EmaPsyker_ja", "seen_enemy_mutant_charger_", loc_EmaPsyker, "ja_loc_psyker_male_c__seen_enemy_mutant_charger_", 2):add_subtext("灵能者", {"变种人冲撞！", "变种人冲锋者来了！"})
E:add_audio("psyker", "EmaPsyker_ja", "smart_tag_vo_enemy_chaos_mutant_charger_", loc_EmaPsyker, "ja_loc_psyker_male_c__smart_tag_vo_enemy_chaos_mutant_charger_", 3):add_subtext("灵能者", {"变种人！", "当心变种人冲撞！", "躲开变种人！"})
E:add_audio("psyker", "EmaPsyker_ja", "enemy_kill_mutant_charger_", loc_EmaPsyker, "ja_loc_psyker_male_c__enemy_kill_mutant_charger_", 3):add_subtext("灵能者", {"变种人死了。", "冲锋者倒下了。", "干掉变种人了。"})

E:add_audio("psyker", "EmaPsyker_ja", "heard_enemy_poxwalker_bomber_", loc_EmaPsyker, "ja_loc_psyker_male_c__heard_enemy_poxwalker_bomber_", 2):add_subtext("灵能者", {"听到炸弹人的引信了！", "小心自爆兵！"})
E:add_audio("psyker", "EmaPsyker_ja", "seen_enemy_poxwalker_bomber_", loc_EmaPsyker, "ja_loc_psyker_male_c__seen_enemy_poxwalker_bomber_", 2):add_subtext("灵能者", {"炸弹人出现了！", "远离那个自爆兵！"})
E:add_audio("psyker", "EmaPsyker_ja", "smart_tag_vo_enemy_chaos_poxwalker_bomber_", loc_EmaPsyker, "ja_loc_psyker_male_c__smart_tag_vo_enemy_chaos_poxwalker_bomber_", 3):add_subtext("灵能者", {"炸弹人！", "自爆兵！", "别让他靠近！"})
E:add_audio("psyker", "EmaPsyker_ja", "enemy_kill_poxwalker_bomber_", loc_EmaPsyker, "ja_loc_psyker_male_c__enemy_kill_poxwalker_bomber_", 3):add_subtext("灵能者", {"炸弹人死了。", "自爆兵被解决。", "安全了，炸弹人死了。"})

E:add_audio("psyker", "EmaPsyker_ja", "smart_tag_vo_enemy_scab_flamer_a_", loc_EmaPsyker, "ja_loc_psyker_male_c__smart_tag_vo_enemy_scab_flamer_a_", 3):add_subtext("灵能者", {"喷火兵！", "当心火焰！", "纵火犯！"})
E:add_audio("psyker", "EmaPsyker_ja", "smart_tag_vo_tox_flamer_", loc_EmaPsyker, "ja_loc_psyker_male_c__smart_tag_vo_tox_flamer_", 3):add_subtext("灵能者", {"毒火兵！", "当心剧毒火焰！", "干掉那个玩火的！"})
E:add_audio("psyker", "EmaPsyker_ja", "seen_enemy_tox_flamer_", loc_EmaPsyker, "ja_loc_psyker_male_c__seen_enemy_tox_flamer_", 2):add_subtext("灵能者", {"发现毒火兵！", "躲开毒焰！"})
E:add_audio("psyker", "EmaPsyker_ja", "seen_enemy_scab_flamer_a_", loc_EmaPsyker, "ja_loc_psyker_male_c__seen_enemy_scab_flamer_a_", 2):add_subtext("灵能者", {"发现喷火兵！", "躲开火焰！"})
E:add_audio("psyker", "EmaPsyker_ja", "enemy_kill_tox_flamer_", loc_EmaPsyker, "ja_loc_psyker_male_c__enemy_kill_tox_flamer_", 3):add_subtext("灵能者", {"毒火兵已死。", "毒焰熄灭了。", "纵火犯被干掉了。"})
E:add_audio("psyker", "EmaPsyker_ja", "enemy_kill_scab_flamer_a_", loc_EmaPsyker, "ja_loc_psyker_male_c__enemy_kill_scab_flamer_a_", 3):add_subtext("灵能者", {"喷火兵已死。", "火焰熄灭了。", "纵火犯被干掉了。"})

E:add_audio("psyker", "EmaPsyker_ja", "seen_enemy_traitor_grenadier_", loc_EmaPsyker, "ja_loc_psyker_male_c__seen_enemy_traitor_grenadier_", 2):add_subtext("灵能者", {"掷弹兵！", "当心手雷！"})
E:add_audio("psyker", "EmaPsyker_ja", "smart_tag_vo_enemy_traitor_grenadier_", loc_EmaPsyker, "ja_loc_psyker_male_c__smart_tag_vo_enemy_traitor_grenadier_", 2):add_subtext("灵能者", {"掷弹兵！", "先干掉丢雷的！"})
E:add_audio("psyker", "EmaPsyker_ja", "enemy_kill_traitor_grenadier_", loc_EmaPsyker, "ja_loc_psyker_male_c__enemy_kill_traitor_grenadier_", 3):add_subtext("灵能者", {"掷弹兵死了。", "投掷手已死。", "手雷威胁解除。"})
E:add_audio("psyker", "EmaPsyker_ja", "seen_enemy_cultist_grenadier_", loc_EmaPsyker, "ja_loc_psyker_male_c__seen_enemy_cultist_grenadier_", 2):add_subtext("灵能者", {"毒气兵！", "当心毒气弹！"})
E:add_audio("psyker", "EmaPsyker_ja", "smart_tag_vo_enemy_cultist_grenadier_", loc_EmaPsyker, "ja_loc_psyker_male_c__smart_tag_vo_enemy_cultist_grenadier_", 2):add_subtext("灵能者", {"毒气掷弹兵！", "不要吸入毒气！"})
E:add_audio("psyker", "EmaPsyker_ja", "enemy_kill_grenadier_", loc_EmaPsyker, "ja_loc_psyker_male_c__enemy_kill_grenadier_", 3):add_subtext("灵能者", {"毒气兵被解决。", "投掷手死了。", "不用担心毒气了。"})

E:add_audio("psyker", "EmaPsyker_ja", "smart_tag_vo_enemy_traitor_sniper_", loc_EmaPsyker, "ja_loc_psyker_male_c__smart_tag_vo_enemy_traitor_sniper_", 3):add_subtext("灵能者", {"狙击手！", "注意躲避狙击线！", "找掩体，有狙击手！"})
E:add_audio("psyker", "EmaPsyker_ja", "seen_enemy_sniper_", loc_EmaPsyker, "ja_loc_psyker_male_c__seen_enemy_sniper_", 3):add_subtext("灵能者", {"发现狙击手！", "当心激光瞄准线！", "狙击手在附近！"})
E:add_audio("psyker", "EmaPsyker_ja", "enemy_kill_sniper_a_", loc_EmaPsyker, "ja_loc_psyker_male_c__enemy_kill_sniper_a_", 3):add_subtext("灵能者", {"狙击手已死。", "暗处的虫子被踩死了。", "狙击手被干掉。"})

E:add_audio("psyker", "EmaPsyker_ja", "seen_enemy_traitor_gunner_", loc_EmaPsyker, "ja_loc_psyker_male_c__seen_enemy_traitor_gunner_", 3):add_subtext("灵能者", {"机枪手！", "敌方正在压制火力！", "干掉那个机枪手！"})
E:add_audio("psyker", "EmaPsyker_ja", "smart_tag_vo_enemy_traitor_gunner_", loc_EmaPsyker, "ja_loc_psyker_male_c__smart_tag_vo_enemy_traitor_gunner_", 3):add_subtext("灵能者", {"机枪手！", "火力点！", "重火力兵！"})
E:add_audio("psyker", "EmaPsyker_ja", "seen_enemy_cultist_holy_stubber_gunner_", loc_EmaPsyker, "ja_loc_psyker_male_c__seen_enemy_cultist_holy_stubber_gunner_", 3):add_subtext("灵能者", {"机枪手！", "敌方正在压制火力！", "干掉那个机枪手！"})
E:add_audio("psyker", "EmaPsyker_ja", "smart_tag_vo_enemy_cultist_holy_stubber_gunner_", loc_EmaPsyker, "ja_loc_psyker_male_c__smart_tag_vo_enemy_cultist_holy_stubber_gunner_", 3):add_subtext("灵能者", {"机枪手！", "火力点！", "重火力兵！"})
E:add_audio("psyker", "EmaPsyker_ja", "seen_enemy_heavy_gunner_", loc_EmaPsyker, "ja_loc_psyker_male_c__seen_enemy_heavy_gunner_", 3):add_subtext("灵能者", {"重机枪手！", "躲避重机枪火力！", "压制火力过来了！"})
E:add_audio("psyker", "EmaPsyker_ja", "smart_tag_vo_enemy_heavy_gunner_", loc_EmaPsyker, "ja_loc_psyker_male_c__smart_tag_vo_enemy_heavy_gunner_", 3):add_subtext("灵能者", {"重机枪手！", "重装炮手！", "干掉重机枪！"})

E:add_audio("psyker", "EmaPsyker_ja", "seen_enemy_shocktrooper_", loc_EmaPsyker, "ja_loc_psyker_male_c__seen_enemy_shocktrooper_", 2):add_subtext("灵能者", {"霰弹枪手！", "当心近距离火力！"})
E:add_audio("psyker", "EmaPsyker_ja", "smart_tag_vo_enemy_traitor_scout_shocktrooper_", loc_EmaPsyker, "ja_loc_psyker_male_c__smart_tag_vo_enemy_traitor_scout_shocktrooper_", 2):add_subtext("灵能者", {"霰弹枪手！", "散弹兵靠近了！"})
E:add_audio("psyker", "EmaPsyker_ja", "seen_enemy_cultist_shocktrooper_", loc_EmaPsyker, "ja_loc_psyker_male_c__seen_enemy_cultist_shocktrooper_", 2):add_subtext("灵能者", {"霰弹枪手！", "当心近距离火力！"})
E:add_audio("psyker", "EmaPsyker_ja", "smart_tag_vo_enemy_cultist_shocktrooper_", loc_EmaPsyker, "ja_loc_psyker_male_c__smart_tag_vo_enemy_cultist_shocktrooper_", 2):add_subtext("灵能者", {"霰弹枪手！", "散弹兵靠近了！"})

E:add_audio("psyker", "EmaPsyker_ja", "seen_enemy_executor_", loc_EmaPsyker, "ja_loc_psyker_male_c__seen_enemy_executor_", 2):add_subtext("灵能者", {"重锤兵！", "当心近战重装！"})
E:add_audio("psyker", "EmaPsyker_ja", "smart_tag_vo_enemy_traitor_executor_", loc_EmaPsyker, "ja_loc_psyker_male_c__smart_tag_vo_enemy_traitor_executor_", 2):add_subtext("灵能者", {"链锯兵！", "躲开链锯武器！"})
E:add_audio("psyker", "EmaPsyker_ja", "smart_tag_vo_enemy_chaos_ogryn_bulwark_", loc_EmaPsyker, "ja_loc_psyker_male_c__smart_tag_vo_enemy_chaos_ogryn_bulwark_", 2):add_subtext("灵能者", {"盾卫欧格林！", "打他的侧翼，他有盾牌！"})
E:add_audio("psyker", "EmaPsyker_ja", "seen_enemy_bulwark_", loc_EmaPsyker, "ja_loc_psyker_male_c__seen_enemy_bulwark_", 2):add_subtext("灵能者", {"盾卫来了！", "重甲盾兵！"})
E:add_audio("psyker", "EmaPsyker_ja", "seen_enemy_chaos_ogryn_armored_executor_", loc_EmaPsyker, "ja_loc_psyker_male_c__seen_enemy_chaos_ogryn_armored_executor_", 2):add_subtext("灵能者", {"粉碎者欧格林！", "重装欧格林来了！"})
E:add_audio("psyker", "EmaPsyker_ja", "smart_tag_vo_enemy_chaos_ogryn_armored_executor_", loc_EmaPsyker, "ja_loc_psyker_male_c__smart_tag_vo_enemy_chaos_ogryn_armored_executor_", 2):add_subtext("灵能者", {"粉碎者！", "重甲粉碎兵！"})
E:add_audio("psyker", "EmaPsyker_ja", "seen_enemy_chaos_ogryn_heavy_gunner_", loc_EmaPsyker, "ja_loc_psyker_male_c__seen_enemy_chaos_ogryn_heavy_gunner_", 2):add_subtext("灵能者", {"收割者欧格林！", "当心重机枪！"})
E:add_audio("psyker", "EmaPsyker_ja", "smart_tag_vo_enemy_chaos_ogryn_heavy_gunner_", loc_EmaPsyker, "ja_loc_psyker_male_c__smart_tag_vo_enemy_chaos_ogryn_heavy_gunner_", 2):add_subtext("灵能者", {"收割者！", "欧格林重机枪！"})

E:add_audio("psyker", "EmaPsyker_ja", "seen_enemy_berserker_", loc_EmaPsyker, "ja_loc_psyker_male_c__seen_enemy_berserker_", 2):add_subtext("灵能者", {"狂战士！", "狂暴者冲过来了！"})
E:add_audio("psyker", "EmaPsyker_ja", "smart_tag_vo_enemy_berserker_", loc_EmaPsyker, "ja_loc_psyker_male_c__smart_tag_vo_enemy_berserker_", 3):add_subtext("灵能者", {"狂战士！", "集中火力对付狂战士！", "狂暴的家伙过来了！"})
E:add_audio("psyker", "EmaPsyker_ja", "enemy_kill_berserker_", loc_EmaPsyker, "ja_loc_psyker_male_c__enemy_kill_berserker_", 3):add_subtext("灵能者", {"狂战士死了。", "狂暴者被干掉。", "失去理智的下场。"})
E:add_audio("psyker", "EmaPsyker_ja", "enemy_kill_berserker_ext_03_c_", loc_EmaPsyker, "ja_loc_psyker_male_c__enemy_kill_berserker_ext_03_c_", 3):add_subtext("灵能者", {"狂战士死了。", "狂暴者被干掉。", "失去理智的下场。"})

E:add_audio("psyker", "EmaPsyker_ja", "seen_enemy_group_far_range_shooting_behind_cover_", loc_EmaPsyker, "ja_loc_psyker_male_c__seen_enemy_group_far_range_shooting_behind_cover_", 3):add_subtext("灵能者", {"敌人在掩体后射击。", "提供火力压制！", "把他们从掩体里逼出来！"})
E:add_audio("psyker", "EmaPsyker_ja", "seen_enemy_group_assaulting_", loc_EmaPsyker, "ja_loc_psyker_male_c__seen_enemy_group_assaulting_", 3):add_subtext("灵能者", {"敌人突击了！", "准备近战！", "坚守阵地！"})

E:add_audio("psyker", "EmaPsyker_ja", "quick_agnostic_enemy_kill_a_", loc_EmaPsyker, "ja_loc_psyker_male_c__quick_agnostic_enemy_kill_a_", 5, 4):add_subtext("灵能者", {"异端当诛。", "为了帝皇。", "化为尘埃。", "就这点本事。", "亚空间不需要你。"}):set_priority(2)

E:add_audio("psyker", "EmaPsyker_ja", "player_tip_armor_hit_generic_", loc_EmaPsyker, "ja_loc_psyker_male_c__player_tip_armor_hit_generic_", 4):add_subtext("灵能者", {"护甲太厚了！", "攻击无效！", "打不穿护甲！", "需要穿甲武器！"})

E:add_audio("psyker", "EmaPsyker_ja", "event_kill_tareget_damaged_", loc_EmaPsyker, "ja_loc_psyker_male_c__event_kill_tareget_damaged_", 2):add_subtext("灵能者", {"目标受损！", "攻击有效！"})
E:add_audio("psyker", "EmaPsyker_ja", "event_kill_target_heavy_damage_a_", loc_EmaPsyker, "ja_loc_psyker_male_c__event_kill_target_heavy_damage_a_", 2):add_subtext("灵能者", {"目标受到重创！", "它快撑不住了！"})
E:add_audio("psyker", "EmaPsyker_ja", "event_kill_target_destroyed_a_", loc_EmaPsyker, "ja_loc_psyker_male_c__event_kill_target_destroyed_a_", 3):add_subtext("灵能者", {"目标已被摧毁。", "任务目标完成。", "干得漂亮，继续前进。"})

E:add_audio("psyker", "EmaPsyker_ja", "guidance_switch_", loc_EmaPsyker, "ja_loc_psyker_male_c__guidance_switch_", 2):add_subtext("灵能者", {"这里有开关。", "拉下那个开关。"})
E:add_audio("psyker", "EmaPsyker_ja", "luggable_mission_pick_up_", loc_EmaPsyker, "ja_loc_psyker_male_c__luggable_mission_pick_up_", 3):add_subtext("灵能者", {"我拿到了任务物品。", "搬运中，掩护我。", "货物已回收。"})

E:add_audio("psyker", "EmaPsyker_ja", "critical_health_", loc_EmaPsyker, "ja_loc_psyker_male_c__critical_health_", 5, 7):add_subtext("灵能者", {"我撑不住了...", "受了重伤...", "急需治疗...", "啊！...好痛...", "生命体征下降..."}):set_priority(1)

E:add_audio("psyker", "EmaPsyker_ja", "smart_tag_stimm_power_a_", loc_EmaPsyker, "ja_loc_psyker_male_c__smart_tag_stimm_power_a_", 2):add_subtext("灵能者", {"力量兴奋剂。", "红色兴奋剂。"})
E:add_audio("psyker", "EmaPsyker_ja", "smart_tag_stimm_speed_a_", loc_EmaPsyker, "ja_loc_psyker_male_c__smart_tag_stimm_speed_a_", 2):add_subtext("灵能者", {"敏捷兴奋剂。", "蓝色兴奋剂。"})
E:add_audio("psyker", "EmaPsyker_ja", "smart_tag_stimm_concentration_a_", loc_EmaPsyker, "ja_loc_psyker_male_c__smart_tag_stimm_concentration_a_", 2):add_subtext("灵能者", {"专注兴奋剂。", "黄色兴奋剂。"})
E:add_audio("psyker", "EmaPsyker_ja", "smart_tag_vo_small_grenade_", loc_EmaPsyker, "ja_loc_psyker_male_c__smart_tag_vo_small_grenade_", 1):add_subtext("灵能者", {"发现手雷补给。"})

E:add_audio("psyker", "EmaPsyker_ja", "calling_for_help_", loc_EmaPsyker, "ja_loc_psyker_male_c__calling_for_help_", 3):add_subtext("灵能者", {"我需要帮助！", "谁来拉我一把！", "帮帮我！"})
E:add_audio("psyker", "EmaPsyker_ja", "response_for_calling_for_help_", loc_EmaPsyker, "ja_loc_psyker_male_c__response_for_calling_for_help_", 3):add_subtext("灵能者", {"我来了！", "坚持住，马上到！", "我来帮你！"})

E:add_audio("psyker", "EmaPsyker_ja", "response_for_zealot_critical_health_", loc_EmaPsyker, "ja_loc_psyker_male_c__response_for_zealot_critical_health_", 3):add_subtext("灵能者", {"你需要治疗！", "快用医疗包！", "你的状态很糟！"})
E:add_audio("psyker", "EmaPsyker_ja", "response_for_veteran_critical_health_", loc_EmaPsyker, "ja_loc_psyker_male_c__response_for_veteran_critical_health_", 3):add_subtext("灵能者", {"你需要治疗！", "快用医疗包！", "你的状态很糟！"})
E:add_audio("psyker", "EmaPsyker_ja", "response_for_psyker_critical_health_", loc_EmaPsyker, "ja_loc_psyker_male_c__response_for_psyker_critical_health_", 3):add_subtext("灵能者", {"你需要治疗！", "快用医疗包！", "你的状态很糟！"})
E:add_audio("psyker", "EmaPsyker_ja", "response_for_ogryn_critical_health_", loc_EmaPsyker, "ja_loc_psyker_male_c__response_for_ogryn_critical_health_", 3):add_subtext("灵能者", {"你需要治疗！", "快用医疗包！", "你的状态很糟！"})
E:add_audio("psyker", "EmaPsyker_ja", "response_for_adamant_critical_health_", loc_EmaPsyker, "ja_loc_psyker_male_c__response_for_adamant_critical_health_", 3):add_subtext("灵能者", {"你需要治疗！", "快用医疗包！", "你的状态很糟！"})

E:add_audio("psyker", "EmaPsyker_ja", "knocked_down_multiple_times_zealot_", loc_EmaPsyker, "ja_loc_psyker_male_c__knocked_down_multiple_times_zealot_", 3):add_subtext("灵能者", {"你倒下太多次了！", "小心点，别再倒了！", "别再送命了！"})
E:add_audio("psyker", "EmaPsyker_ja", "knocked_down_multiple_times_veteran_", loc_EmaPsyker, "ja_loc_psyker_male_c__knocked_down_multiple_times_veteran_", 3):add_subtext("灵能者", {"你倒下太多次了！", "小心点，别再倒了！", "别再送命了！"})
E:add_audio("psyker", "EmaPsyker_ja", "knocked_down_multiple_times_psyker_", loc_EmaPsyker, "ja_loc_psyker_male_c__knocked_down_multiple_times_psyker_", 3):add_subtext("灵能者", {"你倒下太多次了！", "小心点，别再倒了！", "别再送命了！"})
E:add_audio("psyker", "EmaPsyker_ja", "knocked_down_multiple_times_ogryn_", loc_EmaPsyker, "ja_loc_psyker_male_c__knocked_down_multiple_times_ogryn_", 3):add_subtext("灵能者", {"你倒下太多次了！", "小心点，别再倒了！", "别再送命了！"})
E:add_audio("psyker", "EmaPsyker_ja", "knocked_down_multiple_times_adamant_", loc_EmaPsyker, "ja_loc_psyker_male_c__knocked_down_multiple_times_adamant_", 3):add_subtext("灵能者", {"你倒下太多次了！", "小心点，别再倒了！", "别再送命了！"})

E:add_audio("psyker", "EmaPsyker_ja", "player_death_zealot_", loc_EmaPsyker, "ja_loc_psyker_male_c__player_death_zealot_", 1):add_subtext("灵能者", {"有一名特工阵亡！"})
E:add_audio("psyker", "EmaPsyker_ja", "player_death_veteran_", loc_EmaPsyker, "ja_loc_psyker_male_c__player_death_veteran_", 1):add_subtext("灵能者", {"有一名特工阵亡！"})
E:add_audio("psyker", "EmaPsyker_ja", "player_death_psyker_", loc_EmaPsyker, "ja_loc_psyker_male_c__player_death_psyker_", 1):add_subtext("灵能者", {"有一名特工阵亡！"})
E:add_audio("psyker", "EmaPsyker_ja", "player_death_ogryn_", loc_EmaPsyker, "ja_loc_psyker_male_c__player_death_ogryn_", 1):add_subtext("灵能者", {"有一名特工阵亡！"})
E:add_audio("psyker", "EmaPsyker_ja", "player_death_adamant_", loc_EmaPsyker, "ja_loc_psyker_male_c__player_death_adamant_", 1):add_subtext("灵能者", {"有一名特工阵亡！"})

E:add_audio("psyker", "EmaPsyker_ja", "pinned_by_enemies_", loc_EmaPsyker, "ja_loc_psyker_male_c__pinned_by_enemies_", 3):add_subtext("灵能者", {"被火力压制了！", "找掩体，火力太猛了！", "我们被钉死在这里了！"})

E:add_audio("psyker", "EmaPsyker_ja", "response_for_pinned_by_enemies_zealot_", loc_EmaPsyker, "ja_loc_psyker_male_c__response_for_pinned_by_enemies_zealot_", 3):add_subtext("灵能者", {"进行火力反击！", "掩护射击！", "扔手雷清场！"})
E:add_audio("psyker", "EmaPsyker_ja", "response_for_pinned_by_enemies_veteran_", loc_EmaPsyker, "ja_loc_psyker_male_c__response_for_pinned_by_enemies_veteran_", 3):add_subtext("灵能者", {"进行火力反击！", "掩护射击！", "扔手雷清场！"})
E:add_audio("psyker", "EmaPsyker_ja", "response_for_pinned_by_enemies_psyker_", loc_EmaPsyker, "ja_loc_psyker_male_c__response_for_pinned_by_enemies_psyker_", 3):add_subtext("灵能者", {"进行火力反击！", "掩护射击！", "扔手雷清场！"})
E:add_audio("psyker", "EmaPsyker_ja", "response_for_pinned_by_enemies_ogryn_", loc_EmaPsyker, "ja_loc_psyker_male_c__response_for_pinned_by_enemies_ogryn_", 3):add_subtext("灵能者", {"进行火力反击！", "掩护射击！", "扔手雷清场！"})

E:add_audio("psyker", "EmaPsyker_ja", "response_for_zealot_cover_me_", loc_EmaPsyker, "ja_loc_psyker_male_c__response_for_zealot_cover_me_", 3):add_subtext("灵能者", {"我来掩护你！", "放心，你的侧翼交给我！", "正在提供掩护！"})
E:add_audio("psyker", "EmaPsyker_ja", "response_for_veteran_cover_me_", loc_EmaPsyker, "ja_loc_psyker_male_c__response_for_veteran_cover_me_", 3):add_subtext("灵能者", {"我来掩护你！", "放心，你的侧翼交给我！", "正在提供掩护！"})
E:add_audio("psyker", "EmaPsyker_ja", "response_for_psyker_cover_me_", loc_EmaPsyker, "ja_loc_psyker_male_c__response_for_psyker_cover_me_", 3):add_subtext("灵能者", {"我来掩护你！", "放心，你的侧翼交给我！", "正在提供掩护！"})
E:add_audio("psyker", "EmaPsyker_ja", "response_for_ogryn_cover_me_", loc_EmaPsyker, "ja_loc_psyker_male_c__response_for_ogryn_cover_me_", 3):add_subtext("灵能者", {"我来掩护你！", "放心，你的侧翼交给我！", "正在提供掩护！"})

E:add_audio("psyker", "EmaPsyker_ja", "conversation_combat_chaos_spawn_chew_a_", loc_EmaPsyker, "ja_loc_psyker_male_c__conversation_combat_chaos_spawn_chew_a_", 3):add_subtext("灵能者", {"它在啃咬队友！", "快救人！", "集火那个怪物！"})
E:add_audio("psyker", "EmaPsyker_ja", "conversation_combat_chaos_spawn_chew_b_", loc_EmaPsyker, "ja_loc_psyker_male_c__conversation_combat_chaos_spawn_chew_b_", 3):add_subtext("灵能者", {"它在啃咬队友！", "快救人！", "集火那个怪物！"})
E:add_audio("psyker", "EmaPsyker_ja", "conversation_combat_chaos_spawn_chew_c_", loc_EmaPsyker, "ja_loc_psyker_male_c__conversation_combat_chaos_spawn_chew_c_", 3):add_subtext("灵能者", {"它在啃咬队友！", "快救人！", "集火那个怪物！"})

E:add_audio("psyker", "EmaPsyker_ja", "vce_hurt_heavy", play_EmaPsyker, "play_psyker_male_c__vce_hurt_heavy", 19):set_priority(1)
E:add_audio("psyker", "EmaPsyker_ja", "vce_catapulted", play_EmaPsyker, "play_psyker_male_c__vce_catapulted", 59):set_priority(2)
E:add_audio("psyker", "EmaPsyker_ja", "vce_catapulted_land", play_EmaPsyker, "play_psyker_male_c__vce_catapulted_land", 12):set_priority(4)
E:add_audio("psyker", "EmaPsyker_ja", "vce_scream_long", play_EmaPsyker, "play_psyker_male_c__vce_scream_long", 34):set_priority(2)
E:add_audio("psyker", "EmaPsyker_ja", "vce_hurt_light", play_EmaPsyker, "play_psyker_male_c__vce_hurt_light", 58):set_priority(4)
E:add_audio("psyker", "EmaPsyker_ja", "vce_jump", play_EmaPsyker, "play_psyker_male_c__vce_jump", 29):set_priority(4)
E:add_audio("psyker", "EmaPsyker_ja", "vce_land_heavy", play_EmaPsyker, "play_psyker_male_c__vce_land_heavy", 16):set_priority(4)
E:add_audio("psyker", "EmaPsyker_ja", "vce_grunt_short", play_EmaPsyker, "play_psyker_male_c__vce_grunt_short", 12):set_priority(4)
E:add_audio("psyker", "EmaPsyker_ja", "vce_attack_short", play_EmaPsyker, "play_psyker_male_c__vce_attack_short", 39):set_priority(4)
E:add_audio("psyker", "EmaPsyker_ja", "vce_attack_long", play_EmaPsyker, "play_psyker_male_c__vce_attack_long", 28):set_priority(4)
E:add_audio("psyker", "EmaPsyker_ja", "vce_coughing", play_EmaPsyker, "play_psyker_male_c__vce_coughing", 6):set_priority(4)
E:add_audio("psyker", "EmaPsyker_ja", "vce_getting_up", play_EmaPsyker, "play_psyker_male_c__vce_getting_up", 2):set_priority(4)
E:add_audio("psyker", "EmaPsyker_ja", "vce_struggle_heavy", play_EmaPsyker, "play_psyker_male_c__vce_struggle_heavy", 2):set_priority(4)
E:add_audio("psyker", "EmaPsyker_ja", "play_hud_heal_2d", play_EmaPsyker, "play_psyker_male_c__vce_healing", 40, nil, "play_hud_heal_2d")
E:add_audio("psyker", "EmaPsyker_ja", "play_syringe_power_start", play_EmaPsyker, "play_syringe_power_start", 4, nil, "play_syringe_power_start"):set_priority(0)
E:add_audio("psyker", "EmaPsyker_ja", "play_syringe_ability_start", play_EmaPsyker, "play_syringe_ability_start", 4, nil, "play_syringe_ability_start"):set_priority(0)
E:add_audio("psyker", "EmaPsyker_ja", "play_syringe_speed_start", play_EmaPsyker, "play_syringe_speed_start", 4, nil, "play_syringe_speed_start"):set_priority(0)
