-- 【老  兵】【通用版】
local loc_AlicVeteran = "loc_veteran_male_b/AlicVeteran/"
local play_AlicVeteran = "wwise/events/player/play_veteran_male_b/AlicVeteran"
E:set_class("veteran", "AlicVeteran_ja", "通用老兵(日语)"):old_version()

E:add_audio("veteran", "AlicVeteran_ja", "guidance_correct_path_", loc_AlicVeteran, "ja_loc_veteran_male_b__guidance_correct_path_", 4):add_subtext("老兵", {"路是对的，继续前进。", "走这边，跟上。", "这是正确的路线。", "方向确认无误。"})
E:add_audio("veteran", "AlicVeteran_ja", "guidance_correct_path_up_", loc_AlicVeteran, "ja_loc_veteran_male_b__guidance_correct_path_up_", 3):add_subtext("老兵", {"往上走。", "找楼梯上去。", "高处有利，走上面。"})
E:add_audio("veteran", "AlicVeteran_ja", "guidance_correct_path_drop_", loc_AlicVeteran, "ja_loc_veteran_male_b__guidance_correct_path_drop_", 3):add_subtext("老兵", {"准备速降。", "注意脚下，跳下去。", "无路可退，跳！"})
E:add_audio("veteran", "AlicVeteran_ja", "stairs_sighted_", loc_AlicVeteran, "ja_loc_veteran_male_b__stairs_sighted_", 2):add_subtext("老兵", {"发现楼梯。", "走楼梯。"})
E:add_audio("veteran", "AlicVeteran_ja", "guidance_starting_area_", loc_AlicVeteran, "ja_loc_veteran_male_b__guidance_starting_area_", 3):add_subtext("老兵", {"检查武器，准备作战。", "为了黄金王座，消灭他们。", "保持阵型，特工们。"})
E:add_audio("veteran", "AlicVeteran_ja", "region_carnival_a_", loc_AlicVeteran, "ja_loc_veteran_male_b__region_carnival_a_", 2):add_subtext("老兵", {"这鬼地方全是异端的气味。", "保持警惕，这里不安全。"})
E:add_audio("veteran", "AlicVeteran_ja", "info_event_det_pack_a_", loc_AlicVeteran, "ja_loc_veteran_male_b__info_event_det_pack_a_", 3):add_subtext("老兵", {"炸药准备就绪。", "准备爆破。", "退后，我要起爆了。"})
E:add_audio("veteran", "AlicVeteran_ja", "event_survive_keep_coming_a_", loc_AlicVeteran, "ja_loc_veteran_male_b__event_survive_keep_coming_a_", 3):add_subtext("老兵", {"顶住！他们还在来！", "稳住阵型，开火！", "不要退缩，坚守阵地！"})
E:add_audio("veteran", "AlicVeteran_ja", "event_demolition_first_corruptor_destroyed_a_", loc_AlicVeteran, "ja_loc_veteran_male_b__event_demolition_first_corruptor_destroyed_a_", 3):add_subtext("老兵", {"腐化之源已摧毁。", "干掉一个，继续推进！", "异端设施已清除。"})
E:add_audio("veteran", "AlicVeteran_ja", "event_survive_almost_done_", loc_AlicVeteran, "ja_loc_veteran_male_b__event_survive_almost_done_", 3):add_subtext("老兵", {"他们快撑不住了，继续开火！", "撑住，马上就结束了！", "坚持住，胜利就在眼前！"})
E:add_audio("veteran", "AlicVeteran_ja", "info_event_one_down_", loc_AlicVeteran, "ja_loc_veteran_male_b__info_event_one_down_", 3):add_subtext("老兵", {"目标确认摧毁。", "干得好，寻找下一个。", "任务进度更新。"})
E:add_audio("veteran", "AlicVeteran_ja", "response_to_hacking_fix_decode_", loc_AlicVeteran, "ja_loc_veteran_male_b__response_to_hacking_fix_decode_", 3):add_subtext("老兵", {"伺服头骨卡住了，去修好它！", "谁去管管那个机器！", "解码器需要重新接线！"})
E:add_audio("veteran", "AlicVeteran_ja", "info_event_almost_done_", loc_AlicVeteran, "ja_loc_veteran_male_b__info_event_almost_done_", 3):add_subtext("老兵", {"快完成了，坚持住！", "防线稳住，马上就好！", "就差最后一点了！"})
E:add_audio("veteran", "AlicVeteran_ja", "warning_exploding_barrel_", loc_AlicVeteran, "ja_loc_veteran_male_b__warning_exploding_barrel_", 3):add_subtext("老兵", {"当心爆炸物！", "远离那个炸药桶！", "注意油桶！"})
E:add_audio("veteran", "AlicVeteran_ja", "response_rechargable_for_look_at_healthstation_", loc_AlicVeteran, "ja_loc_veteran_male_b__response_rechargable_for_look_at_healthstation_", 2):add_subtext("老兵", {"医疗站没电了。", "需要电池才能运行。"})
E:add_audio("veteran", "AlicVeteran_ja", "smart_tag_vo_station_health_", loc_AlicVeteran, "ja_loc_veteran_male_b__smart_tag_vo_station_health_", 3):add_subtext("老兵", {"发现医疗站。", "这里可以治疗。", "医疗站在我标记的位置。"})

E:add_audio("veteran", "AlicVeteran_ja", "ability_ranger_", loc_AlicVeteran, "ja_loc_veteran_male_b__ability_ranger_", 4, 4):add_subtext("老兵", {"精准打击！", "锁定目标！", "一个也别想跑！", "火力全开！"}):set_priority(2)
E:add_audio("veteran", "AlicVeteran_ja", "ability_squad_leader_", loc_AlicVeteran, "ja_loc_veteran_male_b__ability_squad_leader_", 5, 4):add_subtext("老兵", {"给我站起来继续打！", "以帝皇之名，坚守阵地！", "不要退缩，特工们！", "重整阵型！", "拼死一战！"}):set_priority(2)
E:add_audio("veteran", "AlicVeteran_ja", "ability_shock_trooper_", loc_AlicVeteran, "ja_loc_veteran_male_b__ability_shock_trooper_", 4, 4):add_subtext("老兵", {"隐蔽行踪。", "潜行突击。", "我绕到侧翼了。", "消失在暗处。"}):set_priority(2)
E:add_audio("veteran", "AlicVeteran_ja", "throwing_grenade_", loc_AlicVeteran, "ja_loc_veteran_male_b__throwing_grenade_", 3):add_subtext("老兵", {"碎片手雷，扔出！", "吃我一发破片！", "手雷！卧倒！"})
E:add_audio("veteran", "AlicVeteran_ja", "blitz_smoke_grenade_a_", loc_AlicVeteran, "ja_loc_veteran_male_b__blitz_smoke_grenade_a_", 3):add_subtext("老兵", {"烟雾弹掩护！", "释放烟幕！", "利用烟雾推进！"})
E:add_audio("veteran", "AlicVeteran_ja", "plasma_vent_a_", loc_AlicVeteran, "ja_loc_veteran_male_b__plasma_vent_a_", 3, 5):add_subtext("老兵", {"武器过热，排热中！", "正在排热！", "等一下，枪管太烫了！"}):set_priority(1)

E:add_audio("veteran", "AlicVeteran_ja", "com_wheel_vo_location_ping_", loc_AlicVeteran, "ja_loc_veteran_male_b__com_wheel_vo_location_ping_", 4):add_subtext("老兵", {"往这里走。", "在这个位置。", "去那里。", "集合。"})
E:add_audio("veteran", "AlicVeteran_ja", "com_wheel_vo_location_attention_", loc_AlicVeteran, "ja_loc_veteran_male_b__com_wheel_vo_location_attention_", 3):add_subtext("老兵", {"看那里！", "注意标记位置。", "发现目标。"})
E:add_audio("veteran", "AlicVeteran_ja", "com_wheel_vo_yes_", loc_AlicVeteran, "ja_loc_veteran_male_b__com_wheel_vo_yes_", 4):add_subtext("老兵", {"收到。", "明白。", "确认。", "遵命。"})
E:add_audio("veteran", "AlicVeteran_ja", "com_wheel_vo_no_", loc_AlicVeteran, "ja_loc_veteran_male_b__com_wheel_vo_no_", 4):add_subtext("老兵", {"不行。", "拒绝。", "做不到。", "否定。"})
E:add_audio("veteran", "AlicVeteran_ja", "com_wheel_vo_enemy_over_here_", loc_AlicVeteran, "ja_loc_veteran_male_b__com_wheel_vo_enemy_over_here_", 3):add_subtext("老兵", {"这里有敌人。", "发现敌情。", "接敌准备。"})
E:add_audio("veteran", "AlicVeteran_ja", "com_wheel_vo_thank_you_", loc_AlicVeteran, "ja_loc_veteran_male_b__com_wheel_vo_thank_you_", 3):add_subtext("老兵", {"多谢。", "干得好。", "感谢支援。"})
E:add_audio("veteran", "AlicVeteran_ja", "com_wheel_vo_need_ammo_", loc_AlicVeteran, "ja_loc_veteran_male_b__com_wheel_vo_need_ammo_", 3):add_subtext("老兵", {"我需要弹药！", "弹药见底了！", "谁有备用弹药？"})
E:add_audio("veteran", "AlicVeteran_ja", "com_wheel_vo_need_health_", loc_AlicVeteran, "ja_loc_veteran_male_b__com_wheel_vo_need_health_", 3):add_subtext("老兵", {"我需要医疗包！", "需要治疗！", "我受伤了，需要支援！"})
E:add_audio("veteran", "AlicVeteran_ja", "com_wheel_vo_for_the_emperor_", loc_AlicVeteran, "ja_loc_veteran_male_b__com_wheel_vo_for_the_emperor_", 5, 9):add_subtext("老兵", {"为了帝皇！", "绝不退缩！", "以黄金王座之名！", "杀光异端！", "帝皇庇护着我们！"}):set_priority(2)
E:add_audio("veteran", "AlicVeteran_ja", "com_wheel_vo_follow_you_", loc_AlicVeteran, "ja_loc_veteran_male_b__com_wheel_vo_follow_you_", 4):add_subtext("老兵", {"跟着你。", "带路。", "我在你身后。", "掩护你推进。"})

E:add_audio("veteran", "AlicVeteran_ja", "reloading_", loc_AlicVeteran, "ja_loc_veteran_male_b__reloading_", 3):add_subtext("老兵", {"换弹中，掩护我！", "正在装填！", "弹匣空了！"})
E:add_audio("veteran", "AlicVeteran_ja", "look_at_grenade_", loc_AlicVeteran, "ja_loc_veteran_male_b__look_at_grenade_", 2):add_subtext("老兵", {"发现手雷补给。", "这里有手雷。"})
E:add_audio("veteran", "AlicVeteran_ja", "look_at_healthstation_", loc_AlicVeteran, "ja_loc_veteran_male_b__look_at_healthstation_", 2):add_subtext("老兵", {"医疗站在这。", "前面有医疗站。"})
E:add_audio("veteran", "AlicVeteran_ja", "smart_tag_vo_pickup_deployed_medical_crate_", loc_AlicVeteran, "ja_loc_veteran_male_b__smart_tag_vo_pickup_deployed_medical_crate_", 2):add_subtext("老兵", {"医疗箱已部署。", "过来治疗。"})
E:add_audio("veteran", "AlicVeteran_ja", "smart_tag_vo_pickup_deployed_ammo_crate_", loc_AlicVeteran, "ja_loc_veteran_male_b__smart_tag_vo_pickup_deployed_ammo_crate_", 2):add_subtext("老兵", {"弹药箱已放下。", "补充弹药！"})
E:add_audio("veteran", "AlicVeteran_ja", "smart_tag_vo_pickup_ammo_", loc_AlicVeteran, "ja_loc_veteran_male_b__smart_tag_vo_pickup_ammo_", 2):add_subtext("老兵", {"发现弹药。", "这里有子弹。"})
E:add_audio("veteran", "AlicVeteran_ja", "smart_tag_vo_pickup_health_booster_", loc_AlicVeteran, "ja_loc_veteran_male_b__smart_tag_vo_pickup_health_booster_", 2):add_subtext("老兵", {"发现急救针。", "医疗针补给。"})
E:add_audio("veteran", "AlicVeteran_ja", "smart_tag_vo_pickup_forge_metal_", loc_AlicVeteran, "ja_loc_veteran_male_b__smart_tag_vo_pickup_forge_metal_", 2):add_subtext("老兵", {"发现塑钢。", "找到制作材料。"})
E:add_audio("veteran", "AlicVeteran_ja", "smart_tag_vo_pickup_platinum_", loc_AlicVeteran, "ja_loc_veteran_male_b__smart_tag_vo_pickup_platinum_", 2):add_subtext("老兵", {"发现塑钢。", "找到制作材料。"})
E:add_audio("veteran", "AlicVeteran_ja", "smart_tag_vo_pickup_small_grenade_", loc_AlicVeteran, "ja_loc_veteran_male_b__smart_tag_vo_pickup_small_grenade_", 2):add_subtext("老兵", {"手雷补给。", "这里有爆破物。"})
E:add_audio("veteran", "AlicVeteran_ja", "cover_me_", loc_AlicVeteran, "ja_loc_veteran_male_b__cover_me_", 3):add_subtext("老兵", {"掩护我！", "提供火力支援！", "看着我的背后！"})
E:add_audio("veteran", "AlicVeteran_ja", "away_from_squad_", loc_AlicVeteran, "ja_loc_veteran_male_b__away_from_squad_", 3):add_subtext("老兵", {"我脱队了。", "我离你们太远了。", "正在尝试归队。"})
E:add_audio("veteran", "AlicVeteran_ja", "come_back_to_squad_", loc_AlicVeteran, "ja_loc_veteran_male_b__come_back_to_squad_", 3):add_subtext("老兵", {"别单走，回来！", "保持阵型！", "不要落单！"})

E:add_audio("veteran", "AlicVeteran_ja", "veteran_seen_killstreak_psyker_", loc_AlicVeteran, "ja_loc_veteran_male_b__veteran_seen_killstreak_psyker_", 4, 5):add_subtext("老兵", {"枪法不错。", "干得漂亮。", "完美的击杀。", "就是这样，继续保持。"}):set_priority(2)
E:add_audio("veteran", "AlicVeteran_ja", "veteran_seen_killstreak_zealot_", loc_AlicVeteran, "ja_loc_veteran_male_b__veteran_seen_killstreak_zealot_", 4, 5):add_subtext("老兵", {"枪法不错。", "干得漂亮。", "完美的击杀。", "就是这样，继续保持。"}):set_priority(2)
E:add_audio("veteran", "AlicVeteran_ja", "veteran_seen_killstreak_veteran_", loc_AlicVeteran, "ja_loc_veteran_male_b__veteran_seen_killstreak_veteran_", 4, 5):add_subtext("老兵", {"枪法不错。", "干得漂亮。", "完美的击杀。", "就是这样，继续保持。"}):set_priority(2)
E:add_audio("veteran", "AlicVeteran_ja", "veteran_seen_killstreak_ogryn_", loc_AlicVeteran, "ja_loc_veteran_male_b__veteran_seen_killstreak_ogryn_", 4, 5):add_subtext("老兵", {"枪法不错。", "干得漂亮。", "完美的击杀。", "就是这样，继续保持。"}):set_priority(2)
E:add_audio("veteran", "AlicVeteran_ja", "veteran_seen_killstreak_adamant_", loc_AlicVeteran, "ja_loc_veteran_male_b__veteran_seen_killstreak_adamant_", 4, 5):add_subtext("老兵", {"枪法不错。", "干得漂亮。", "完美的击杀。", "就是这样，继续保持。"}):set_priority(2)

E:add_audio("veteran", "AlicVeteran_ja", "response_for_zealot_seen_killstreak_veteran_", loc_AlicVeteran, "ja_loc_veteran_male_b__response_for_zealot_seen_killstreak_veteran_", 4, 5):add_subtext("老兵", {"这算不了什么。", "只是在履行职责。", "为了帝皇。", "日常训练罢了。"}):set_priority(2)
E:add_audio("veteran", "AlicVeteran_ja", "response_for_veteran_seen_killstreak_veteran_", loc_AlicVeteran, "ja_loc_veteran_male_b__response_for_veteran_seen_killstreak_veteran_", 4, 5):add_subtext("老兵", {"这算不了什么。", "只是在履行职责。", "为了帝皇。", "日常训练罢了。"}):set_priority(2)
E:add_audio("veteran", "AlicVeteran_ja", "response_for_psyker_seen_killstreak_veteran_", loc_AlicVeteran, "ja_loc_veteran_male_b__response_for_psyker_seen_killstreak_veteran_", 4, 5):add_subtext("老兵", {"这算不了什么。", "只是在履行职责。", "为了帝皇。", "日常训练罢了。"}):set_priority(2)
E:add_audio("veteran", "AlicVeteran_ja", "response_for_ogryn_seen_killstreak_veteran_", loc_AlicVeteran, "ja_loc_veteran_male_b__response_for_ogryn_seen_killstreak_veteran_", 4, 5):add_subtext("老兵", {"这算不了什么。", "只是在履行职责。", "为了帝皇。", "日常训练罢了。"}):set_priority(2)
E:add_audio("veteran", "AlicVeteran_ja", "response_for_adamant_seen_killstreak_veteran_", loc_AlicVeteran, "ja_loc_veteran_male_b__response_for_adamant_seen_killstreak_veteran_", 4, 5):add_subtext("老兵", {"这算不了什么。", "只是在履行职责。", "为了帝皇。", "日常训练罢了。"}):set_priority(2)

E:add_audio("veteran", "AlicVeteran_ja", "response_for_friendly_fire_from_zealot_", loc_AlicVeteran, "ja_loc_veteran_male_b__response_for_friendly_fire_from_zealot_", 4):add_subtext("老兵", {"看准点开火！", "你打中我了！", "友军火力！", "检查你的射击线！"})
E:add_audio("veteran", "AlicVeteran_ja", "response_for_friendly_fire_from_veteran_", loc_AlicVeteran, "ja_loc_veteran_male_b__response_for_friendly_fire_from_veteran_", 4):add_subtext("老兵", {"看准点开火！", "你打中我了！", "友军火力！", "检查你的射击线！"})
E:add_audio("veteran", "AlicVeteran_ja", "response_for_friendly_fire_from_psyker_", loc_AlicVeteran, "ja_loc_veteran_male_b__response_for_friendly_fire_from_psyker_", 4):add_subtext("老兵", {"看准点开火！", "你打中我了！", "友军火力！", "检查你的射击线！"})
E:add_audio("veteran", "AlicVeteran_ja", "response_for_friendly_fire_from_ogryn_", loc_AlicVeteran, "ja_loc_veteran_male_b__response_for_friendly_fire_from_ogryn_", 4):add_subtext("老兵", {"看准点开火！", "你打中我了！", "友军火力！", "检查你的射击线！"})
E:add_audio("veteran", "AlicVeteran_ja", "response_for_friendly_fire_from_adamant_", loc_AlicVeteran, "ja_loc_veteran_male_b__response_for_friendly_fire_from_adamant_", 4):add_subtext("老兵", {"看准点开火！", "你打中我了！", "友军火力！", "检查你的射击线！"})

E:add_audio("veteran", "AlicVeteran_ja", "friendly_fire_from_zealot_to_veteran_", loc_AlicVeteran, "ja_loc_veteran_male_b__friendly_fire_from_zealot_to_veteran_", 4):add_subtext("老兵", {"抱歉，我的错。", "当心流弹！", "火力误伤，注意规避！", "注意走位！"})
E:add_audio("veteran", "AlicVeteran_ja", "friendly_fire_from_veteran_to_veteran_", loc_AlicVeteran, "ja_loc_veteran_male_b__friendly_fire_from_veteran_to_veteran_", 4):add_subtext("老兵", {"抱歉，我的错。", "当心流弹！", "火力误伤，注意规避！", "注意走位！"})
E:add_audio("veteran", "AlicVeteran_ja", "friendly_fire_from_psyker_to_veteran_", loc_AlicVeteran, "ja_loc_veteran_male_b__friendly_fire_from_psyker_to_veteran_", 4):add_subtext("老兵", {"抱歉，我的错。", "当心流弹！", "火力误伤，注意规避！", "注意走位！"})
E:add_audio("veteran", "AlicVeteran_ja", "friendly_fire_from_ogryn_to_veteran_", loc_AlicVeteran, "ja_loc_veteran_male_b__friendly_fire_from_ogryn_to_veteran_", 4):add_subtext("老兵", {"抱歉，我的错。", "当心流弹！", "火力误伤，注意规避！", "注意走位！"})
E:add_audio("veteran", "AlicVeteran_ja", "friendly_fire_from_adamant_to_veteran_", loc_AlicVeteran, "ja_loc_veteran_male_b__friendly_fire_from_adamant_to_veteran_", 4):add_subtext("老兵", {"抱歉，我的错。", "当心流弹！", "火力误伤，注意规避！", "注意走位！"})

E:add_audio("veteran", "AlicVeteran_ja", "head_shot_", loc_AlicVeteran, "ja_loc_veteran_male_b__head_shot_", 3):add_subtext("老兵", {"完美爆头。", "一枪毙命。", "干净利落。"})
E:add_audio("veteran", "AlicVeteran_ja", "response_for_zealot_disabled_by_enemy_", loc_AlicVeteran, "ja_loc_veteran_male_b__response_for_zealot_disabled_by_enemy_", 3):add_subtext("老兵", {"队友被抓了！", "掩护队友！", "把那东西从他身上弄下来！"})
E:add_audio("veteran", "AlicVeteran_ja", "response_for_veteran_disabled_by_enemy_", loc_AlicVeteran, "ja_loc_veteran_male_b__response_for_veteran_disabled_by_enemy_", 3):add_subtext("老兵", {"队友被抓了！", "掩护队友！", "把那东西从他身上弄下来！"})
E:add_audio("veteran", "AlicVeteran_ja", "response_for_psyker_disabled_by_enemy_", loc_AlicVeteran, "ja_loc_veteran_male_b__response_for_psyker_disabled_by_enemy_", 3):add_subtext("老兵", {"队友被抓了！", "掩护队友！", "把那东西从他身上弄下来！"})
E:add_audio("veteran", "AlicVeteran_ja", "response_for_ogryn_disabled_by_enemy_", loc_AlicVeteran, "ja_loc_veteran_male_b__response_for_ogryn_disabled_by_enemy_", 3):add_subtext("老兵", {"队友被抓了！", "掩护队友！", "把那东西从他身上弄下来！"})

E:add_audio("veteran", "AlicVeteran_ja", "veteran_start_revive_zealot_", loc_AlicVeteran, "ja_loc_veteran_male_b__veteran_start_revive_zealot_", 3):add_subtext("老兵", {"坚持住，拉你起来。", "站起来，士兵。", "战斗还没结束。"})
E:add_audio("veteran", "AlicVeteran_ja", "veteran_start_revive_veteran_", loc_AlicVeteran, "ja_loc_veteran_male_b__veteran_start_revive_veteran_", 3):add_subtext("老兵", {"坚持住，拉你起来。", "站起来，士兵。", "战斗还没结束。"})
E:add_audio("veteran", "AlicVeteran_ja", "veteran_start_revive_psyker_", loc_AlicVeteran, "ja_loc_veteran_male_b__veteran_start_revive_psyker_", 3):add_subtext("老兵", {"坚持住，拉你起来。", "站起来，士兵。", "战斗还没结束。"})
E:add_audio("veteran", "AlicVeteran_ja", "veteran_start_revive_ogryn_", loc_AlicVeteran, "ja_loc_veteran_male_b__veteran_start_revive_ogryn_", 3):add_subtext("老兵", {"坚持住，拉你起来。", "站起来，士兵。", "战斗还没结束。"})
E:add_audio("veteran", "AlicVeteran_ja", "veteran_start_revive_adamant_", loc_AlicVeteran, "ja_loc_veteran_male_b__veteran_start_revive_adamant_", 3):add_subtext("老兵", {"坚持住，拉你起来。", "站起来，士兵。", "战斗还没结束。"})

E:add_audio("veteran", "AlicVeteran_ja", "combat_pause_one_liner_", loc_AlicVeteran, "ja_loc_veteran_male_b__combat_pause_one_liner_", 3):add_subtext("老兵", {"保持警惕，随时准备接敌。", "检查弹药，我们继续推进。", "不要放松，异端还在暗处。"})
E:add_audio("veteran", "AlicVeteran_ja", "surrounded_", loc_AlicVeteran, "ja_loc_veteran_male_b__surrounded_", 3):add_subtext("老兵", {"我被包围了！", "需要火力支援！", "敌人太多了！"})
E:add_audio("veteran", "AlicVeteran_ja", "surrounded_response_", loc_AlicVeteran, "ja_loc_veteran_male_b__surrounded_response_", 3):add_subtext("老兵", {"撑住，我们来了！", "向我们靠拢！", "火力掩护中！"})
E:add_audio("veteran", "AlicVeteran_ja", "heard_horde_vector_", loc_AlicVeteran, "ja_loc_veteran_male_b__heard_horde_vector_", 4):add_subtext("老兵", {"尸潮来了！", "结成防线！", "大量敌人逼近，准备迎击！", "他们冲过来了！"})
E:add_audio("veteran", "AlicVeteran_ja", "heard_horde_ambush_", loc_AlicVeteran, "ja_loc_veteran_male_b__heard_horde_ambush_", 4):add_subtext("老兵", {"尸潮来了！", "结成防线！", "大量敌人逼近，准备迎击！", "他们冲过来了！"})

E:add_audio("veteran", "AlicVeteran_ja", "heard_enemy_beast_of_nurgle_", loc_AlicVeteran, "ja_loc_veteran_male_b__heard_enemy_beast_of_nurgle_", 3):add_subtext("老兵", {"听到了巨型怪物的动静！", "有大家伙要来了！", "保持警惕，有巨兽！"})
E:add_audio("veteran", "AlicVeteran_ja", "heard_enemy_chaos_spawn_", loc_AlicVeteran, "ja_loc_veteran_male_b__heard_enemy_chaos_spawn_", 3):add_subtext("老兵", {"听到了巨型怪物的动静！", "有大家伙要来了！", "保持警惕，有巨兽！"})
E:add_audio("veteran", "AlicVeteran_ja", "heard_enemy_plague_ogryn_", loc_AlicVeteran, "ja_loc_veteran_male_b__heard_enemy_plague_ogryn_", 3):add_subtext("老兵", {"听到了巨型怪物的动静！", "有大家伙要来了！", "保持警惕，有巨兽！"})

E:add_audio("veteran", "AlicVeteran_ja", "conversation_plague_ogryn_weakpoint_01_", loc_AlicVeteran, "ja_loc_veteran_male_b__conversation_plague_ogryn_weakpoint_01_", 3):add_subtext("老兵", {"集中火力打它的弱点！", "瞄准头部打！", "打它的要害！"})
E:add_audio("veteran", "AlicVeteran_ja", "conversation_beast_of_nurgle_weakpoint_a_", loc_AlicVeteran, "ja_loc_veteran_male_b__conversation_beast_of_nurgle_weakpoint_a_", 3):add_subtext("老兵", {"集中火力打它的弱点！", "瞄准发光的地方打！", "打它的背部！"})
E:add_audio("veteran", "AlicVeteran_ja", "conversation_beast_of_nurgle_weakpoint_c_", loc_AlicVeteran, "ja_loc_veteran_male_b__conversation_beast_of_nurgle_weakpoint_c_", 3):add_subtext("老兵", {"集中火力打它的弱点！", "瞄准发光的地方打！", "打它的背部！"})

E:add_audio("veteran", "AlicVeteran_ja", "seen_enemy_plague_ogryn_", loc_AlicVeteran, "ja_loc_veteran_male_b__seen_enemy_plague_ogryn_", 3):add_subtext("老兵", {"发现巨兽，集中火力！", "怪物出现了！", "干掉那个畸变体！"})
E:add_audio("veteran", "AlicVeteran_ja", "seen_enemy_beast_of_nurgle_", loc_AlicVeteran, "ja_loc_veteran_male_b__seen_enemy_beast_of_nurgle_", 3):add_subtext("老兵", {"发现巨兽，集中火力！", "怪物出现了！", "干掉那个畸变体！"})
E:add_audio("veteran", "AlicVeteran_ja", "seen_enemy_chaos_spawn_", loc_AlicVeteran, "ja_loc_veteran_male_b__seen_enemy_chaos_spawn_", 3):add_subtext("老兵", {"发现巨兽，集中火力！", "怪物出现了！", "干掉那个畸变体！"})

E:add_audio("veteran", "AlicVeteran_ja", "smart_tag_vo_enemy_chaos_spawn_a_", loc_AlicVeteran, "ja_loc_veteran_male_b__smart_tag_vo_enemy_chaos_spawn_a_", 2):add_subtext("老兵", {"混沌卵！", "消灭那个突变体！"})
E:add_audio("veteran", "AlicVeteran_ja", "smart_tag_vo_enemy_chaos_spawn_b_", loc_AlicVeteran, "ja_loc_veteran_male_b__smart_tag_vo_enemy_chaos_spawn_b_", 2):add_subtext("老兵", {"混沌卵！", "消灭那个突变体！"})
E:add_audio("veteran", "AlicVeteran_ja", "smart_tag_vo_enemy_beast_of_nurgle_", loc_AlicVeteran, "ja_loc_veteran_male_b__smart_tag_vo_enemy_beast_of_nurgle_", 2):add_subtext("老兵", {"纳垢野兽！", "庞大的腐化怪物！"})
E:add_audio("veteran", "AlicVeteran_ja", "smart_tag_vo_enemy_plague_ogryn_", loc_AlicVeteran, "ja_loc_veteran_male_b__smart_tag_vo_enemy_plague_ogryn_", 2):add_subtext("老兵", {"瘟疫欧格林！", "当心那个被腐化的欧格林！"})

E:add_audio("veteran", "AlicVeteran_ja", "heard_enemy_daemonhost_", loc_AlicVeteran, "ja_loc_veteran_male_b__heard_enemy_daemonhost_", 2):add_subtext("老兵", {"附近有恶魔宿主，听这低语声。", "保持安静，附近有恶魔宿主。"})
E:add_audio("veteran", "AlicVeteran_ja", "seen_enemy_daemonhost_", loc_AlicVeteran, "ja_loc_veteran_male_b__seen_enemy_daemonhost_", 2):add_subtext("老兵", {"发现恶魔宿主，关掉手电绕过去。", "别惊动它，安静点。"})
E:add_audio("veteran", "AlicVeteran_ja", "alerted_ememy_daemonhost_", loc_AlicVeteran, "ja_loc_veteran_male_b__alerted_ememy_daemonhost_", 1):add_subtext("老兵", {"恶魔宿主被激怒了！开火！"})
E:add_audio("veteran", "AlicVeteran_ja", "smart_tag_vo_enemy_daemonhost_", loc_AlicVeteran, "ja_loc_veteran_male_b__smart_tag_vo_enemy_daemonhost_", 2):add_subtext("老兵", {"恶魔宿主！", "消灭那个恶魔！"})

E:add_audio("veteran", "AlicVeteran_ja", "monster_fight_start_reaction_", loc_AlicVeteran, "ja_loc_veteran_male_b__monster_fight_start_reaction_", 3, 5):add_subtext("老兵", {"巨兽战准备！", "开火，把它打成筛子！", "不要退缩！"}):set_priority(2)
E:add_audio("veteran", "AlicVeteran_ja", "enemy_near_death_monster_", loc_AlicVeteran, "ja_loc_veteran_male_b__enemy_near_death_monster_", 2, 4):add_subtext("老兵", {"它快倒下了，继续开火！", "给它最后一击！"}):set_priority(2)
E:add_audio("veteran", "AlicVeteran_ja", "enemy_kill_monster_", loc_AlicVeteran, "ja_loc_veteran_male_b__enemy_kill_monster_", 3, 5):add_subtext("老兵", {"目标已消灭。", "巨兽倒下了，干得好。", "威胁解除。"}):set_priority(2)

E:add_audio("veteran", "AlicVeteran_ja", "heard_enemy_chaos_hound_", loc_AlicVeteran, "ja_loc_veteran_male_b__heard_enemy_chaos_hound_", 2):add_subtext("老兵", {"听到猎犬嚎叫了。", "注意瘟疫猎犬！"})
E:add_audio("veteran", "AlicVeteran_ja", "seen_enemy_chaos_hound_", loc_AlicVeteran, "ja_loc_veteran_male_b__seen_enemy_chaos_hound_", 2):add_subtext("老兵", {"有瘟疫猎犬！", "发现猎犬，打死它！"})
E:add_audio("veteran", "AlicVeteran_ja", "smart_tag_vo_enemy_chaos_hound_", loc_AlicVeteran, "ja_loc_veteran_male_b__smart_tag_vo_enemy_chaos_hound_", 2):add_subtext("老兵", {"猎犬！", "瘟疫猎犬！"})
E:add_audio("veteran", "AlicVeteran_ja", "enemy_kill_chaos_hound_", loc_AlicVeteran, "ja_loc_veteran_male_b__enemy_kill_chaos_hound_", 2):add_subtext("老兵", {"死狗被干掉了。", "猎犬已清除。"})

E:add_audio("veteran", "AlicVeteran_ja", "seen_netgunner_", loc_AlicVeteran, "ja_loc_veteran_male_b__seen_netgunner_", 2):add_subtext("老兵", {"当心捕网兵！", "陷阱手在这！"})
E:add_audio("veteran", "AlicVeteran_ja", "seen_netgunner_flee_", loc_AlicVeteran, "ja_loc_veteran_male_b__seen_netgunner_flee_", 2):add_subtext("老兵", {"陷阱兵逃跑了！", "别让他跑了！"})
E:add_audio("veteran", "AlicVeteran_ja", "smart_tag_vo_enemy_netgunner_", loc_AlicVeteran, "ja_loc_veteran_male_b__smart_tag_vo_enemy_netgunner_", 2):add_subtext("老兵", {"网兵！", "陷阱兵！"})
E:add_audio("veteran", "AlicVeteran_ja", "enemy_kill_netgunner_", loc_AlicVeteran, "ja_loc_veteran_male_b__enemy_kill_netgunner_", 2):add_subtext("老兵", {"网兵死了。", "陷阱兵已清除。"})

E:add_audio("veteran", "AlicVeteran_ja", "seen_enemy_mutant_charger_", loc_AlicVeteran, "ja_loc_veteran_male_b__seen_enemy_mutant_charger_", 2):add_subtext("老兵", {"变种人冲锋！", "躲开变种人！"})
E:add_audio("veteran", "AlicVeteran_ja", "smart_tag_vo_enemy_chaos_mutant_charger_", loc_AlicVeteran, "ja_loc_veteran_male_b__smart_tag_vo_enemy_chaos_mutant_charger_", 2):add_subtext("老兵", {"变种人！", "变种人冲锋者！"})
E:add_audio("veteran", "AlicVeteran_ja", "enemy_kill_mutant_charger_", loc_AlicVeteran, "ja_loc_veteran_male_b__enemy_kill_mutant_charger_", 2):add_subtext("老兵", {"变种人倒下了。", "变种人清除。"})

E:add_audio("veteran", "AlicVeteran_ja", "heard_enemy_poxwalker_bomber_", loc_AlicVeteran, "ja_loc_veteran_male_b__heard_enemy_poxwalker_bomber_", 2):add_subtext("老兵", {"听到炸弹人的引信了！", "当心炸弹人！"})
E:add_audio("veteran", "AlicVeteran_ja", "seen_enemy_poxwalker_bomber_", loc_AlicVeteran, "ja_loc_veteran_male_b__seen_enemy_poxwalker_bomber_", 2):add_subtext("老兵", {"炸弹人！当心手雷！", "自爆兵出现了！"})
E:add_audio("veteran", "AlicVeteran_ja", "smart_tag_vo_enemy_chaos_poxwalker_bomber_", loc_AlicVeteran, "ja_loc_veteran_male_b__smart_tag_vo_enemy_chaos_poxwalker_bomber_", 2):add_subtext("老兵", {"炸弹人！", "投弹手！"})
E:add_audio("veteran", "AlicVeteran_ja", "enemy_kill_poxwalker_bomber_", loc_AlicVeteran, "ja_loc_veteran_male_b__enemy_kill_poxwalker_bomber_", 2):add_subtext("老兵", {"自爆兵解决。", "炸弹人清除。"})

E:add_audio("veteran", "AlicVeteran_ja", "smart_tag_vo_enemy_scab_flamer_a_", loc_AlicVeteran, "ja_loc_veteran_male_b__smart_tag_vo_enemy_scab_flamer_a_", 2):add_subtext("老兵", {"喷火兵！躲开火焰！", "纵火犯！"})
E:add_audio("veteran", "AlicVeteran_ja", "smart_tag_vo_tox_flamer_", loc_AlicVeteran, "ja_loc_veteran_male_b__smart_tag_vo_tox_flamer_", 2):add_subtext("老兵", {"毒气兵！躲开毒火！", "纵火犯！"})
E:add_audio("veteran", "AlicVeteran_ja", "seen_enemy_tox_flamer_", loc_AlicVeteran, "ja_loc_veteran_male_b__seen_enemy_tox_flamer_", 2):add_subtext("老兵", {"喷火兵！躲开火焰！", "纵火犯出现了！"})
E:add_audio("veteran", "AlicVeteran_ja", "seen_enemy_scab_flamer_a_", loc_AlicVeteran, "ja_loc_veteran_male_b__seen_enemy_scab_flamer_a_", 2):add_subtext("老兵", {"喷火兵！躲开火焰！", "纵火犯出现了！"})
E:add_audio("veteran", "AlicVeteran_ja", "enemy_kill_tox_flamer_", loc_AlicVeteran, "ja_loc_veteran_male_b__enemy_kill_tox_flamer_", 2):add_subtext("老兵", {"纵火犯死了。", "喷火兵已清除。"})
E:add_audio("veteran", "AlicVeteran_ja", "enemy_kill_scab_flamer_a_", loc_AlicVeteran, "ja_loc_veteran_male_b__enemy_kill_scab_flamer_a_", 2):add_subtext("老兵", {"纵火犯死了。", "喷火兵已清除。"})

E:add_audio("veteran", "AlicVeteran_ja", "seen_enemy_traitor_grenadier_", loc_AlicVeteran, "ja_loc_veteran_male_b__seen_enemy_traitor_grenadier_", 2):add_subtext("老兵", {"掷弹兵！", "当心手雷！"})
E:add_audio("veteran", "AlicVeteran_ja", "smart_tag_vo_enemy_traitor_grenadier_", loc_AlicVeteran, "ja_loc_veteran_male_b__smart_tag_vo_enemy_traitor_grenadier_", 2):add_subtext("老兵", {"掷弹兵！", "手雷兵！"})
E:add_audio("veteran", "AlicVeteran_ja", "enemy_kill_traitor_grenadier_", loc_AlicVeteran, "ja_loc_veteran_male_b__enemy_kill_traitor_grenadier_", 2):add_subtext("老兵", {"掷弹兵死了。", "投弹手清除。"})
E:add_audio("veteran", "AlicVeteran_ja", "seen_enemy_cultist_grenadier_", loc_AlicVeteran, "ja_loc_veteran_male_b__seen_enemy_cultist_grenadier_", 2):add_subtext("老兵", {"掷弹兵！", "当心毒气！"})
E:add_audio("veteran", "AlicVeteran_ja", "smart_tag_vo_enemy_cultist_grenadier_", loc_AlicVeteran, "ja_loc_veteran_male_b__smart_tag_vo_enemy_cultist_grenadier_", 2):add_subtext("老兵", {"毒气兵！", "手雷兵！"})
E:add_audio("veteran", "AlicVeteran_ja", "enemy_kill_grenadier_", loc_AlicVeteran, "ja_loc_veteran_male_b__enemy_kill_grenadier_", 2):add_subtext("老兵", {"毒气兵死了。", "投弹手清除。"})

E:add_audio("veteran", "AlicVeteran_ja", "smart_tag_vo_enemy_traitor_sniper_", loc_AlicVeteran, "ja_loc_veteran_male_b__smart_tag_vo_enemy_traitor_sniper_", 2):add_subtext("老兵", {"当心狙击手激光！", "狙击手在暗处！"})
E:add_audio("veteran", "AlicVeteran_ja", "seen_enemy_sniper_", loc_AlicVeteran, "ja_loc_veteran_male_b__seen_enemy_sniper_", 2):add_subtext("老兵", {"发现狙击手！", "隐蔽，有狙击手！"})
E:add_audio("veteran", "AlicVeteran_ja", "enemy_kill_sniper_a_", loc_AlicVeteran, "ja_loc_veteran_male_b__enemy_kill_sniper_a_", 2):add_subtext("老兵", {"狙击手被击毙。", "威胁消除。"})

E:add_audio("veteran", "AlicVeteran_ja", "seen_enemy_traitor_gunner_", loc_AlicVeteran, "ja_loc_veteran_male_b__seen_enemy_traitor_gunner_", 2):add_subtext("老兵", {"机枪手！找掩体！", "重机枪压制！"})
E:add_audio("veteran", "AlicVeteran_ja", "smart_tag_vo_enemy_traitor_gunner_", loc_AlicVeteran, "ja_loc_veteran_male_b__smart_tag_vo_enemy_traitor_gunner_", 2):add_subtext("老兵", {"机枪手！", "干掉火力点！"})
E:add_audio("veteran", "AlicVeteran_ja", "seen_enemy_cultist_holy_stubber_gunner_", loc_AlicVeteran, "ja_loc_veteran_male_b__seen_enemy_cultist_holy_stubber_gunner_", 2):add_subtext("老兵", {"机枪手！找掩体！", "重机枪压制！"})
E:add_audio("veteran", "AlicVeteran_ja", "smart_tag_vo_enemy_cultist_holy_stubber_gunner_", loc_AlicVeteran, "ja_loc_veteran_male_b__smart_tag_vo_enemy_cultist_holy_stubber_gunner_", 2):add_subtext("老兵", {"机枪手！", "干掉火力点！"})
E:add_audio("veteran", "AlicVeteran_ja", "seen_enemy_heavy_gunner_", loc_AlicVeteran, "ja_loc_veteran_male_b__seen_enemy_heavy_gunner_", 2):add_subtext("老兵", {"机枪手！找掩体！", "重机枪压制！"})
E:add_audio("veteran", "AlicVeteran_ja", "smart_tag_vo_enemy_heavy_gunner_", loc_AlicVeteran, "ja_loc_veteran_male_b__smart_tag_vo_enemy_heavy_gunner_", 2):add_subtext("老兵", {"机枪手！", "干掉火力点！"})

E:add_audio("veteran", "AlicVeteran_ja", "seen_enemy_shocktrooper_", loc_AlicVeteran, "ja_loc_veteran_male_b__seen_enemy_shocktrooper_", 2):add_subtext("老兵", {"霰弹枪手靠近！", "当心近距离突击！"})
E:add_audio("veteran", "AlicVeteran_ja", "smart_tag_vo_enemy_traitor_scout_shocktrooper_", loc_AlicVeteran, "ja_loc_veteran_male_b__smart_tag_vo_enemy_traitor_scout_shocktrooper_", 2):add_subtext("老兵", {"霰弹枪手！", "突击兵！"})
E:add_audio("veteran", "AlicVeteran_ja", "seen_enemy_cultist_shocktrooper_", loc_AlicVeteran, "ja_loc_veteran_male_b__seen_enemy_cultist_shocktrooper_", 2):add_subtext("老兵", {"霰弹枪手靠近！", "当心近距离突击！"})
E:add_audio("veteran", "AlicVeteran_ja", "smart_tag_vo_enemy_cultist_shocktrooper_", loc_AlicVeteran, "ja_loc_veteran_male_b__smart_tag_vo_enemy_cultist_shocktrooper_", 2):add_subtext("老兵", {"霰弹枪手！", "突击兵！"})

E:add_audio("veteran", "AlicVeteran_ja", "seen_enemy_executor_", loc_AlicVeteran, "ja_loc_veteran_male_b__seen_enemy_executor_", 2):add_subtext("老兵", {"重锤兵！当心近战！", "刽子手来了！"})
E:add_audio("veteran", "AlicVeteran_ja", "smart_tag_vo_enemy_traitor_executor_", loc_AlicVeteran, "ja_loc_veteran_male_b__smart_tag_vo_enemy_traitor_executor_", 2):add_subtext("老兵", {"重锤兵！", "链锯兵！"})

E:add_audio("veteran", "AlicVeteran_ja", "smart_tag_vo_enemy_chaos_ogryn_bulwark_", loc_AlicVeteran, "ja_loc_veteran_male_b__smart_tag_vo_enemy_chaos_ogryn_bulwark_", 2):add_subtext("老兵", {"盾卫！打他的侧翼！", "重甲盾兵！"})
E:add_audio("veteran", "AlicVeteran_ja", "seen_enemy_bulwark_", loc_AlicVeteran, "ja_loc_veteran_male_b__seen_enemy_bulwark_", 2):add_subtext("老兵", {"盾卫！打他的侧翼！", "重甲盾兵！"})

E:add_audio("veteran", "AlicVeteran_ja", "seen_enemy_chaos_ogryn_armored_executor_", loc_AlicVeteran, "ja_loc_veteran_male_b__seen_enemy_chaos_ogryn_armored_executor_", 2):add_subtext("老兵", {"粉碎者！重甲单位！", "装甲欧格林！"})
E:add_audio("veteran", "AlicVeteran_ja", "smart_tag_vo_enemy_chaos_ogryn_armored_executor_", loc_AlicVeteran, "ja_loc_veteran_male_b__smart_tag_vo_enemy_chaos_ogryn_armored_executor_", 2):add_subtext("老兵", {"粉碎者！", "破甲手！"})

E:add_audio("veteran", "AlicVeteran_ja", "seen_enemy_chaos_ogryn_heavy_gunner_", loc_AlicVeteran, "ja_loc_veteran_male_b__seen_enemy_chaos_ogryn_heavy_gunner_", 2):add_subtext("老兵", {"收割者！当心重机枪！", "欧格林机枪手！"})
E:add_audio("veteran", "AlicVeteran_ja", "smart_tag_vo_enemy_chaos_ogryn_heavy_gunner_", loc_AlicVeteran, "ja_loc_veteran_male_b__smart_tag_vo_enemy_chaos_ogryn_heavy_gunner_", 2):add_subtext("老兵", {"收割者！", "重机枪！"})

E:add_audio("veteran", "AlicVeteran_ja", "seen_enemy_berserker_", loc_AlicVeteran, "ja_loc_veteran_male_b__seen_enemy_berserker_", 2):add_subtext("老兵", {"狂战士！集中火力！", "狂暴者来了！"})
E:add_audio("veteran", "AlicVeteran_ja", "smart_tag_vo_enemy_berserker_", loc_AlicVeteran, "ja_loc_veteran_male_b__smart_tag_vo_enemy_berserker_", 2):add_subtext("老兵", {"狂战士！", "狂暴者！"})
E:add_audio("veteran", "AlicVeteran_ja", "enemy_kill_berserker_", loc_AlicVeteran, "ja_loc_veteran_male_b__enemy_kill_berserker_", 2):add_subtext("老兵", {"狂暴者被消灭。", "狂战士死了。"})
E:add_audio("veteran", "AlicVeteran_ja", "enemy_kill_berserker_ext_03_c_", loc_AlicVeteran, "ja_loc_veteran_male_b__enemy_kill_berserker_ext_03_c_", 2):add_subtext("老兵", {"狂暴者被消灭。", "狂战士死了。"})

E:add_audio("veteran", "AlicVeteran_ja", "seen_enemy_group_far_range_shooting_behind_cover_", loc_AlicVeteran, "ja_loc_veteran_male_b__seen_enemy_group_far_range_shooting_behind_cover_", 2):add_subtext("老兵", {"敌人在掩体后射击！", "提供火力压制！"})
E:add_audio("veteran", "AlicVeteran_ja", "seen_enemy_group_assaulting_", loc_AlicVeteran, "ja_loc_veteran_male_b__seen_enemy_group_assaulting_", 2):add_subtext("老兵", {"敌人突击！准备近战！", "守住防线！"})
E:add_audio("veteran", "AlicVeteran_ja", "quick_agnostic_enemy_kill_a_", loc_AlicVeteran, "ja_loc_veteran_male_b__quick_agnostic_enemy_kill_a_", 5, 4):add_subtext("老兵", {"异端当诛。", "为了帝皇。", "下一个。", "就这点本事。", "精准命中。"}):set_priority(2)

E:add_audio("veteran", "AlicVeteran_ja", "player_tip_armor_hit_generic_", loc_AlicVeteran, "ja_loc_veteran_male_b__player_tip_armor_hit_generic_", 3):add_subtext("老兵", {"打不穿护甲！", "需要穿甲武器！", "攻击无效！"})
E:add_audio("veteran", "AlicVeteran_ja", "event_kill_tareget_damaged_", loc_AlicVeteran, "ja_loc_veteran_male_b__event_kill_tareget_damaged_", 2):add_subtext("老兵", {"目标受损！", "攻击有效！"})
E:add_audio("veteran", "AlicVeteran_ja", "event_kill_target_heavy_damage_a_", loc_AlicVeteran, "ja_loc_veteran_male_b__event_kill_target_heavy_damage_a_", 2):add_subtext("老兵", {"目标重创！", "它撑不了多久了！"})
E:add_audio("veteran", "AlicVeteran_ja", "event_kill_target_destroyed_a_", loc_AlicVeteran, "ja_loc_veteran_male_b__event_kill_target_destroyed_a_", 2):add_subtext("老兵", {"目标摧毁！", "干得好，任务继续。"})

E:add_audio("veteran", "AlicVeteran_ja", "guidance_switch_", loc_AlicVeteran, "ja_loc_veteran_male_b__guidance_switch_", 2):add_subtext("老兵", {"这里有开关。", "拉下开关。"})
E:add_audio("veteran", "AlicVeteran_ja", "luggable_mission_pick_up_", loc_AlicVeteran, "ja_loc_veteran_male_b__luggable_mission_pick_up_", 2):add_subtext("老兵", {"我拿到任务物品了。", "我来搬运，掩护我。"})

E:add_audio("veteran", "AlicVeteran_ja", "critical_health_", loc_AlicVeteran, "ja_loc_veteran_male_b__critical_health_", 4, 7):add_subtext("老兵", {"我受了重伤...", "急需医疗支援...", "撑不住了...", "啊，该死..."}):set_priority(1)

E:add_audio("veteran", "AlicVeteran_ja", "smart_tag_stimm_power_a_", loc_AlicVeteran, "ja_loc_veteran_male_b__smart_tag_stimm_power_a_", 2):add_subtext("老兵", {"力量针。", "发现红色兴奋剂。"})
E:add_audio("veteran", "AlicVeteran_ja", "smart_tag_stimm_speed_a_", loc_AlicVeteran, "ja_loc_veteran_male_b__smart_tag_stimm_speed_a_", 2):add_subtext("老兵", {"敏捷针。", "发现蓝色兴奋剂。"})
E:add_audio("veteran", "AlicVeteran_ja", "smart_tag_stimm_concentration_a_", loc_AlicVeteran, "ja_loc_veteran_male_b__smart_tag_stimm_concentration_a_", 2):add_subtext("老兵", {"专注针。", "发现黄色兴奋剂。"})
E:add_audio("veteran", "AlicVeteran_ja", "smart_tag_vo_small_grenade_", loc_AlicVeteran, "ja_loc_veteran_male_b__smart_tag_vo_small_grenade_", 2):add_subtext("老兵", {"手雷补给。", "爆破物补给。"})

E:add_audio("veteran", "AlicVeteran_ja", "calling_for_help_", loc_AlicVeteran, "ja_loc_veteran_male_b__calling_for_help_", 3):add_subtext("老兵", {"我需要拉一把！", "谁来帮帮我！", "请求救援！"})
E:add_audio("veteran", "AlicVeteran_ja", "response_for_calling_for_help_", loc_AlicVeteran, "ja_loc_veteran_male_b__response_for_calling_for_help_", 3):add_subtext("老兵", {"我来了！", "坚持住，马上到！", "掩护我，我去救人！"})

E:add_audio("veteran", "AlicVeteran_ja", "response_for_zealot_critical_health_", loc_AlicVeteran, "ja_loc_veteran_male_b__response_for_zealot_critical_health_", 2):add_subtext("老兵", {"你的状态很糟。", "快去寻找医疗包。"})
E:add_audio("veteran", "AlicVeteran_ja", "response_for_veteran_critical_health_", loc_AlicVeteran, "ja_loc_veteran_male_b__response_for_veteran_critical_health_", 2):add_subtext("老兵", {"你的状态很糟。", "快去寻找医疗包。"})
E:add_audio("veteran", "AlicVeteran_ja", "response_for_psyker_critical_health_", loc_AlicVeteran, "ja_loc_veteran_male_b__response_for_psyker_critical_health_", 2):add_subtext("老兵", {"你的状态很糟。", "快去寻找医疗包。"})
E:add_audio("veteran", "AlicVeteran_ja", "response_for_ogryn_critical_health_", loc_AlicVeteran, "ja_loc_veteran_male_b__response_for_ogryn_critical_health_", 2):add_subtext("老兵", {"你的状态很糟。", "快去寻找医疗包。"})
E:add_audio("veteran", "AlicVeteran_ja", "response_for_adamant_critical_health_", loc_AlicVeteran, "ja_loc_veteran_male_b__response_for_adamant_critical_health_", 2):add_subtext("老兵", {"你的状态很糟。", "快去寻找医疗包。"})

E:add_audio("veteran", "AlicVeteran_ja", "knocked_down_multiple_times_zealot_", loc_AlicVeteran, "ja_loc_veteran_male_b__knocked_down_multiple_times_zealot_", 3):add_subtext("老兵", {"你倒下太多次了！", "小心点，别送命！", "站稳了，别再倒下！"})
E:add_audio("veteran", "AlicVeteran_ja", "knocked_down_multiple_times_veteran_", loc_AlicVeteran, "ja_loc_veteran_male_b__knocked_down_multiple_times_veteran_", 3):add_subtext("老兵", {"你倒下太多次了！", "小心点，别送命！", "站稳了，别再倒下！"})
E:add_audio("veteran", "AlicVeteran_ja", "knocked_down_multiple_times_psyker_", loc_AlicVeteran, "ja_loc_veteran_male_b__knocked_down_multiple_times_psyker_", 3):add_subtext("老兵", {"你倒下太多次了！", "小心点，别送命！", "站稳了，别再倒下！"})
E:add_audio("veteran", "AlicVeteran_ja", "knocked_down_multiple_times_ogryn_", loc_AlicVeteran, "ja_loc_veteran_male_b__knocked_down_multiple_times_ogryn_", 3):add_subtext("老兵", {"你倒下太多次了！", "小心点，别送命！", "站稳了，别再倒下！"})
E:add_audio("veteran", "AlicVeteran_ja", "knocked_down_multiple_times_adamant_", loc_AlicVeteran, "ja_loc_veteran_male_b__knocked_down_multiple_times_adamant_", 3):add_subtext("老兵", {"你倒下太多次了！", "小心点，别送命！", "站稳了，别再倒下！"})

E:add_audio("veteran", "AlicVeteran_ja", "player_death_zealot_", loc_AlicVeteran, "ja_loc_veteran_male_b__player_death_zealot_", 1):add_subtext("老兵", {"一名特工阵亡！"})
E:add_audio("veteran", "AlicVeteran_ja", "player_death_veteran_", loc_AlicVeteran, "ja_loc_veteran_male_b__player_death_veteran_", 1):add_subtext("老兵", {"一名特工阵亡！"})
E:add_audio("veteran", "AlicVeteran_ja", "player_death_psyker_", loc_AlicVeteran, "ja_loc_veteran_male_b__player_death_psyker_", 1):add_subtext("老兵", {"一名特工阵亡！"})
E:add_audio("veteran", "AlicVeteran_ja", "player_death_ogryn_", loc_AlicVeteran, "ja_loc_veteran_male_b__player_death_ogryn_", 1):add_subtext("老兵", {"一名特工阵亡！"})
E:add_audio("veteran", "AlicVeteran_ja", "player_death_adamant_", loc_AlicVeteran, "ja_loc_veteran_male_b__player_death_adamant_", 1):add_subtext("老兵", {"一名特工阵亡！"})

E:add_audio("veteran", "AlicVeteran_ja", "pinned_by_enemies_", loc_AlicVeteran, "ja_loc_veteran_male_b__pinned_by_enemies_", 2):add_subtext("老兵", {"被压制了！找掩体！", "敌方火力太猛！"})
E:add_audio("veteran", "AlicVeteran_ja", "response_for_pinned_by_enemies_zealot_", loc_AlicVeteran, "ja_loc_veteran_male_b__response_for_pinned_by_enemies_zealot_", 3):add_subtext("老兵", {"火力反击！", "扔手雷清场！", "我来掩护你！"})
E:add_audio("veteran", "AlicVeteran_ja", "response_for_pinned_by_enemies_veteran_", loc_AlicVeteran, "ja_loc_veteran_male_b__response_for_pinned_by_enemies_veteran_", 3):add_subtext("老兵", {"火力反击！", "扔手雷清场！", "我来掩护你！"})
E:add_audio("veteran", "AlicVeteran_ja", "response_for_pinned_by_enemies_psyker_", loc_AlicVeteran, "ja_loc_veteran_male_b__response_for_pinned_by_enemies_psyker_", 3):add_subtext("老兵", {"火力反击！", "扔手雷清场！", "我来掩护你！"})
E:add_audio("veteran", "AlicVeteran_ja", "response_for_pinned_by_enemies_ogryn_", loc_AlicVeteran, "ja_loc_veteran_male_b__response_for_pinned_by_enemies_ogryn_", 3):add_subtext("老兵", {"火力反击！", "扔手雷清场！", "我来掩护你！"})

E:add_audio("veteran", "AlicVeteran_ja", "response_for_zealot_cover_me_", loc_AlicVeteran, "ja_loc_veteran_male_b__response_for_zealot_cover_me_", 3):add_subtext("老兵", {"火力掩护中！", "你的背后交给我了！", "放手干吧，我掩护！"})
E:add_audio("veteran", "AlicVeteran_ja", "response_for_veteran_cover_me_", loc_AlicVeteran, "ja_loc_veteran_male_b__response_for_veteran_cover_me_", 3):add_subtext("老兵", {"火力掩护中！", "你的背后交给我了！", "放手干吧，我掩护！"})
E:add_audio("veteran", "AlicVeteran_ja", "response_for_psyker_cover_me_", loc_AlicVeteran, "ja_loc_veteran_male_b__response_for_psyker_cover_me_", 3):add_subtext("老兵", {"火力掩护中！", "你的背后交给我了！", "放手干吧，我掩护！"})
E:add_audio("veteran", "AlicVeteran_ja", "response_for_ogryn_cover_me_", loc_AlicVeteran, "ja_loc_veteran_male_b__response_for_ogryn_cover_me_", 3):add_subtext("老兵", {"火力掩护中！", "你的背后交给我了！", "放手干吧，我掩护！"})

E:add_audio("veteran", "AlicVeteran_ja", "conversation_combat_chaos_spawn_chew_a_", loc_AlicVeteran, "ja_loc_veteran_male_b__conversation_combat_chaos_spawn_chew_a_", 2):add_subtext("老兵", {"它在啃咬队友！开火！", "集火那个怪物救人！"})
E:add_audio("veteran", "AlicVeteran_ja", "conversation_combat_chaos_spawn_chew_b_", loc_AlicVeteran, "ja_loc_veteran_male_b__conversation_combat_chaos_spawn_chew_b_", 2):add_subtext("老兵", {"它在啃咬队友！开火！", "集火那个怪物救人！"})
E:add_audio("veteran", "AlicVeteran_ja", "conversation_combat_chaos_spawn_chew_c_", loc_AlicVeteran, "ja_loc_veteran_male_b__conversation_combat_chaos_spawn_chew_c_", 2):add_subtext("老兵", {"它在啃咬队友！开火！", "集火那个怪物救人！"})

E:add_audio("veteran", "AlicVeteran_ja", "vce_hurt_heavy", play_AlicVeteran, "play_veteran_male_b__vce_hurt_heavy", 19):set_priority(1)
E:add_audio("veteran", "AlicVeteran_ja", "vce_catapulted", play_AlicVeteran, "play_veteran_male_b__vce_catapulted", 59):set_priority(2)
E:add_audio("veteran", "AlicVeteran_ja", "vce_catapulted_land", play_AlicVeteran, "play_veteran_male_b__vce_catapulted_land", 12):set_priority(4)
E:add_audio("veteran", "AlicVeteran_ja", "vce_scream_long", play_AlicVeteran, "play_veteran_male_b__vce_scream_long", 34):set_priority(2)
E:add_audio("veteran", "AlicVeteran_ja", "vce_hurt_light", play_AlicVeteran, "play_veteran_male_b__vce_hurt_light", 58):set_priority(4)
E:add_audio("veteran", "AlicVeteran_ja", "vce_jump", play_AlicVeteran, "play_veteran_male_b__vce_jump", 29):set_priority(4)
E:add_audio("veteran", "AlicVeteran_ja", "vce_land_heavy", play_AlicVeteran, "play_veteran_male_b__vce_land_heavy", 16):set_priority(4)
E:add_audio("veteran", "AlicVeteran_ja", "vce_grunt_short", play_AlicVeteran, "play_veteran_male_b__vce_grunt_short", 12):set_priority(4)
E:add_audio("veteran", "AlicVeteran_ja", "vce_attack_short", play_AlicVeteran, "play_veteran_male_b__vce_attack_short", 39):set_priority(4)
E:add_audio("veteran", "AlicVeteran_ja", "vce_attack_long", play_AlicVeteran, "play_veteran_male_b__vce_attack_long", 28):set_priority(4)
E:add_audio("veteran", "AlicVeteran_ja", "vce_coughing", play_AlicVeteran, "play_veteran_male_b__vce_coughing", 6):set_priority(4)
E:add_audio("veteran", "AlicVeteran_ja", "vce_getting_up", play_AlicVeteran, "play_veteran_male_b__vce_getting_up", 2):set_priority(4)
E:add_audio("veteran", "AlicVeteran_ja", "vce_struggle_heavy", play_AlicVeteran, "play_veteran_male_b__vce_struggle_heavy", 2):set_priority(4)
E:add_audio("veteran", "AlicVeteran_ja", "play_hud_heal_2d", play_AlicVeteran, "play_veteran_male_b__vce_healing", 40, nil, "play_hud_heal_2d")
E:add_audio("veteran", "AlicVeteran_ja", "play_syringe_power_start", play_AlicVeteran, "play_syringe_power_start", 4, nil, "play_syringe_power_start"):set_priority(0)
E:add_audio("veteran", "AlicVeteran_ja", "play_syringe_ability_start", play_AlicVeteran, "play_syringe_ability_start", 4, nil, "play_syringe_ability_start"):set_priority(0)
E:add_audio("veteran", "AlicVeteran_ja", "play_syringe_speed_start", play_AlicVeteran, "play_syringe_speed_start", 4, nil, "play_syringe_speed_start"):set_priority(0)
