-- 【狂信徒】【通用版】
local loc_ako = "loc_zealot_female_a/ako/"
local play_ako = "wwise/events/player/play_zealot_female_a/ako"
E:set_class("zealot", "ako_ja", "通用狂信徒(日语)"):old_version()

E:add_audio("zealot", "ako_ja", "guidance_correct_path_", loc_ako, "ja_loc_zealot_female_a__guidance_correct_path_", 4):add_subtext("狂信徒", {"走这边，信徒们。", "这是正确的道路。", "神皇指引我们走这里。", "跟我来，不要掉队。"})
E:add_audio("zealot", "ako_ja", "guidance_correct_path_up_", loc_ako, "ja_loc_zealot_female_a__guidance_correct_path_up_", 3):add_subtext("狂信徒", {"向上走，向着光明。", "上面是正确的路。", "跟我往上走。"})
E:add_audio("zealot", "ako_ja", "guidance_correct_path_drop_", loc_ako, "ja_loc_zealot_female_a__guidance_correct_path_drop_", 3):add_subtext("狂信徒", {"跳下去，迎接审判！", "深入深渊！", "下去之后就没有回头路了。"})
E:add_audio("zealot", "ako_ja", "stairs_sighted_", loc_ako, "ja_loc_zealot_female_a__stairs_sighted_", 2):add_subtext("狂信徒", {"这里有楼梯。", "从阶梯上去。"})
E:add_audio("zealot", "ako_ja", "guidance_starting_area_", loc_ako, "ja_loc_zealot_female_a__guidance_starting_area_", 3):add_subtext("狂信徒", {"赞美神皇，让我们开始净化吧。", "异端必将在这片土地上被焚毁。", "准备好你们的武器，信徒们。"})
E:add_audio("zealot", "ako_ja", "region_carnival_a_", loc_ako, "ja_loc_zealot_female_a__region_carnival_a_", 2):add_subtext("狂信徒", {"这里的空气充满了堕落的恶臭。", "罪人聚集之地，正适合我们净化。"})
E:add_audio("zealot", "ako_ja", "info_event_det_pack_a_", loc_ako, "ja_loc_zealot_female_a__info_event_det_pack_a_", 3):add_subtext("狂信徒", {"炸药已部署，准备迎接圣火！", "爆破准备就绪。", "让爆炸净化一切障碍！"})
E:add_audio("zealot", "ako_ja", "event_survive_keep_coming_a_", loc_ako, "ja_loc_zealot_female_a__event_survive_keep_coming_a_", 3):add_subtext("狂信徒", {"异端源源不断，杀光他们！", "坚守阵地，为了黄金王座！", "用他们的血献祭神皇！"})
E:add_audio("zealot", "ako_ja", "event_demolition_first_corruptor_destroyed_a_", loc_ako, "ja_loc_zealot_female_a__event_demolition_first_corruptor_destroyed_a_", 3):add_subtext("狂信徒", {"腐化之源已被摧毁！", "第一处污秽已拔除！", "神皇的怒火烧尽了它。"})
E:add_audio("zealot", "ako_ja", "event_survive_almost_done_", loc_ako, "ja_loc_zealot_female_a__event_survive_almost_done_", 3):add_subtext("狂信徒", {"快结束了，不要停下杀戮！", "异端在退缩！", "坚持住，胜利属于神皇！"})
E:add_audio("zealot", "ako_ja", "info_event_one_down_", loc_ako, "ja_loc_zealot_female_a__info_event_one_down_", 3):add_subtext("狂信徒", {"目标摧毁。", "净化完成一个。", "继续前进，不要怜悯。"})
E:add_audio("zealot", "ako_ja", "response_to_hacking_fix_decode_", loc_ako, "ja_loc_zealot_female_a__response_to_hacking_fix_decode_", 3):add_subtext("狂信徒", {"该死的机器卡住了！", "谁来让这台机器重新运转！", "伺服头骨需要修理！"})
E:add_audio("zealot", "ako_ja", "info_event_almost_done_", loc_ako, "ja_loc_zealot_female_a__info_event_almost_done_", 3):add_subtext("狂信徒", {"快要完成了，保持警惕！", "就差最后一步！", "神皇在注视着我们的胜利。"})
E:add_audio("zealot", "ako_ja", "warning_exploding_barrel_", loc_ako, "ja_loc_zealot_female_a__warning_exploding_barrel_", 3):add_subtext("狂信徒", {"当心异端的炸药桶！", "远离爆炸物！", "小心那个油桶！"})
E:add_audio("zealot", "ako_ja", "response_rechargable_for_look_at_healthstation_", loc_ako, "ja_loc_zealot_female_a__response_rechargable_for_look_at_healthstation_", 2):add_subtext("狂信徒", {"医疗站没有能量了。", "这台机器需要电池才能运作。"})
E:add_audio("zealot", "ako_ja", "smart_tag_vo_station_health_", loc_ako, "ja_loc_zealot_female_a__smart_tag_vo_station_health_", 3):add_subtext("狂信徒", {"医疗站在那里。", "受伤的信徒，去接受治疗。", "发现医疗设施。"})

E:add_audio("zealot", "ako_ja", "ability_litany_temp_", loc_ako, "ja_loc_zealot_female_a__ability_litany_temp_", 4, 4):add_subtext("狂信徒", {"感受神皇的怒火！", "以黄金王座之名！", "异端，接受审判！", "忏悔吧！"}):set_priority(2)
E:add_audio("zealot", "ako_ja", "ability_repent_a_", loc_ako, "ja_loc_zealot_female_a__ability_repent_a_", 4, 4):add_subtext("狂信徒", {"感受神皇的怒火！", "以黄金王座之名！", "异端，接受审判！", "忏悔吧！"}):set_priority(2)
E:add_audio("zealot", "ako_ja", "ability_maniac_", loc_ako, "ja_loc_zealot_female_a__ability_maniac_", 3, 3):add_subtext("狂信徒", {"血祭神皇！", "杀光他们！", "死吧！"}):set_priority(2)
E:add_audio("zealot", "ako_ja", "ability_pious_stabber_", loc_ako, "ja_loc_zealot_female_a__ability_pious_stabber_", 3, 4):add_subtext("狂信徒", {"潜入阴影！", "异端，你的死期到了！", "化为神皇的利刃！"}):set_priority(2)

E:add_audio("zealot", "ako_ja", "blitz_flame_grenade_a_", loc_ako, "ja_loc_zealot_female_a__blitz_flame_grenade_a_", 3):add_subtext("狂信徒", {"在圣火中焚毁吧！", "净化之火！", "燃烧吧，异端！"})
E:add_audio("zealot", "ako_ja", "com_wheel_vo_location_ping_", loc_ako, "ja_loc_zealot_female_a__com_wheel_vo_location_ping_", 3):add_subtext("狂信徒", {"前往此地。", "往这边走。", "目标地点在此。"})
E:add_audio("zealot", "ako_ja", "com_wheel_vo_location_attention_", loc_ako, "ja_loc_zealot_female_a__com_wheel_vo_location_attention_", 3):add_subtext("狂信徒", {"注意那里。", "看那边！", "留心这个位置。"})
E:add_audio("zealot", "ako_ja", "com_wheel_vo_yes_", loc_ako, "ja_loc_zealot_female_a__com_wheel_vo_yes_", 4):add_subtext("狂信徒", {"如你所愿。", "明白。", "神皇准许。", "收到。"})
E:add_audio("zealot", "ako_ja", "com_wheel_vo_no_", loc_ako, "ja_loc_zealot_female_a__com_wheel_vo_no_", 3):add_subtext("狂信徒", {"绝不！", "不可接受。", "我拒绝。"})
E:add_audio("zealot", "ako_ja", "com_wheel_vo_enemy_over_here_", loc_ako, "ja_loc_zealot_female_a__com_wheel_vo_enemy_over_here_", 3):add_subtext("狂信徒", {"异端就在附近！", "敌人在此！", "准备接敌！"})
E:add_audio("zealot", "ako_ja", "com_wheel_vo_thank_you_", loc_ako, "ja_loc_zealot_female_a__com_wheel_vo_thank_you_", 3):add_subtext("狂信徒", {"愿神皇庇佑你。", "感谢你的援助。", "干得好。"})
E:add_audio("zealot", "ako_ja", "com_wheel_vo_need_ammo_", loc_ako, "ja_loc_zealot_female_a__com_wheel_vo_need_ammo_", 3):add_subtext("狂信徒", {"我需要弹药来继续圣战！", "弹药枯竭了！", "给我补给！"})
E:add_audio("zealot", "ako_ja", "com_wheel_vo_need_health_", loc_ako, "ja_loc_zealot_female_a__com_wheel_vo_need_health_", 3):add_subtext("狂信徒", {"这具躯体需要治疗。", "我流血过多，需要医疗！", "给我医疗包！"})
E:add_audio("zealot", "ako_ja", "com_wheel_vo_for_the_emperor_", loc_ako, "ja_loc_zealot_female_a__com_wheel_vo_for_the_emperor_", 4, 5):add_subtext("狂信徒", {"为了黄金王座！", "以神皇之名！", "杀戮无止境！", "死战到底！"}):set_priority(2)

E:add_audio("zealot", "ako_ja", "reloading_", loc_ako, "ja_loc_zealot_female_a__reloading_", 3):add_subtext("狂信徒", {"装填弹药！", "掩护我，正在换弹！", "武器枯竭，重装中！"})
E:add_audio("zealot", "ako_ja", "look_at_grenade_", loc_ako, "ja_loc_zealot_female_a__look_at_grenade_", 2):add_subtext("狂信徒", {"发现爆破物。", "这有手雷补给。"})
E:add_audio("zealot", "ako_ja", "look_at_healthstation_", loc_ako, "ja_loc_zealot_female_a__look_at_healthstation_", 3):add_subtext("狂信徒", {"医疗站在前方。", "去那里治疗伤口。", "神皇恩赐的医疗站。"})
E:add_audio("zealot", "ako_ja", "smart_tag_vo_pickup_medical_crate_", loc_ako, "ja_loc_zealot_female_a__smart_tag_vo_pickup_medical_crate_", 2):add_subtext("狂信徒", {"这里有医疗包。", "携带这个医疗包。"})
E:add_audio("zealot", "ako_ja", "smart_tag_vo_pickup_ammo_crate_", loc_ako, "ja_loc_zealot_female_a__smart_tag_vo_pickup_ammo_crate_", 2):add_subtext("狂信徒", {"这里有弹药箱。", "带上弹药箱。"})
E:add_audio("zealot", "ako_ja", "smart_tag_vo_pickup_deployed_medical_crate_", loc_ako, "ja_loc_zealot_female_a__smart_tag_vo_pickup_deployed_medical_crate_", 2):add_subtext("狂信徒", {"医疗箱已部署！", "快来治疗你们的伤口！"})
E:add_audio("zealot", "ako_ja", "smart_tag_vo_pickup_deployed_ammo_crate_", loc_ako, "ja_loc_zealot_female_a__smart_tag_vo_pickup_deployed_ammo_crate_", 2):add_subtext("狂信徒", {"弹药已部署！", "补充你们的怒火！"})
E:add_audio("zealot", "ako_ja", "smart_tag_vo_pickup_ammo_", loc_ako, "ja_loc_zealot_female_a__smart_tag_vo_pickup_ammo_", 3):add_subtext("狂信徒", {"发现弹药。", "子弹在此。", "拿去消灭异端。"})
E:add_audio("zealot", "ako_ja", "smart_tag_vo_pickup_health_booster_", loc_ako, "ja_loc_zealot_female_a__smart_tag_vo_pickup_health_booster_", 2):add_subtext("狂信徒", {"发现医疗针。", "拿上这个急救针。"})
E:add_audio("zealot", "ako_ja", "smart_tag_vo_pickup_forge_metal_", loc_ako, "ja_loc_zealot_female_a__smart_tag_vo_pickup_forge_metal_", 2):add_subtext("狂信徒", {"找到塑钢材料。", "有用的物资。"})
E:add_audio("zealot", "ako_ja", "smart_tag_vo_pickup_platinum_", loc_ako, "ja_loc_zealot_female_a__smart_tag_vo_pickup_platinum_", 2):add_subtext("狂信徒", {"找到塑钢材料。", "有用的物资。"})
E:add_audio("zealot", "ako_ja", "smart_tag_vo_pickup_small_grenade_", loc_ako, "ja_loc_zealot_female_a__smart_tag_vo_pickup_small_grenade_", 2):add_subtext("狂信徒", {"手雷补给在此。", "补充爆破物。"})

E:add_audio("zealot", "ako_ja", "cover_me_", loc_ako, "ja_loc_zealot_female_a__cover_me_", 3):add_subtext("狂信徒", {"掩护我！", "保护我的侧翼！", "提供掩护火力！"})
E:add_audio("zealot", "ako_ja", "away_from_squad_", loc_ako, "ja_loc_zealot_female_a__away_from_squad_", 3):add_subtext("狂信徒", {"我离队伍太远了。", "我得归队。", "切勿孤军深入。"})
E:add_audio("zealot", "ako_ja", "come_back_to_squad_", loc_ako, "ja_loc_zealot_female_a__come_back_to_squad_", 3):add_subtext("狂信徒", {"不要脱队，回来！", "向我靠拢！", "离开队伍等于寻死！"})

E:add_audio("zealot", "ako_ja", "zealot_seen_killstreak_psyker_", loc_ako, "ja_loc_zealot_female_a__zealot_seen_killstreak_psyker_", 4, 5):add_subtext("狂信徒", {"神皇在指引你的利刃！", "杀得好！", "完美的净化！", "不要停下杀戮！"}):set_priority(2)
E:add_audio("zealot", "ako_ja", "zealot_seen_killstreak_zealot_", loc_ako, "ja_loc_zealot_female_a__zealot_seen_killstreak_zealot_", 4, 5):add_subtext("狂信徒", {"神皇在指引你的利刃！", "杀得好！", "完美的净化！", "不要停下杀戮！"}):set_priority(2)
E:add_audio("zealot", "ako_ja", "zealot_seen_killstreak_veteran_", loc_ako, "ja_loc_zealot_female_a__zealot_seen_killstreak_veteran_", 4, 5):add_subtext("狂信徒", {"神皇在指引你的利刃！", "杀得好！", "完美的净化！", "不要停下杀戮！"}):set_priority(2)
E:add_audio("zealot", "ako_ja", "zealot_seen_killstreak_ogryn_", loc_ako, "ja_loc_zealot_female_a__zealot_seen_killstreak_ogryn_", 4, 5):add_subtext("狂信徒", {"神皇在指引你的利刃！", "杀得好！", "完美的净化！", "不要停下杀戮！"}):set_priority(2)
E:add_audio("zealot", "ako_ja", "zealot_seen_killstreak_adamant_", loc_ako, "ja_loc_zealot_female_a__zealot_seen_killstreak_adamant_", 4, 5):add_subtext("狂信徒", {"神皇在指引你的利刃！", "杀得好！", "完美的净化！", "不要停下杀戮！"}):set_priority(2)

E:add_audio("zealot", "ako_ja", "response_for_zealot_seen_killstreak_zealot_", loc_ako, "ja_loc_zealot_female_a__response_for_zealot_seen_killstreak_zealot_", 4, 5):add_subtext("狂信徒", {"这都是神皇的意志！", "我的信仰即是武器！", "为了黄金王座！", "异端必将覆灭！"}):set_priority(2)
E:add_audio("zealot", "ako_ja", "response_for_veteran_seen_killstreak_zealot_", loc_ako, "ja_loc_zealot_female_a__response_for_veteran_seen_killstreak_zealot_", 4, 5):add_subtext("狂信徒", {"这都是神皇的意志！", "我的信仰即是武器！", "为了黄金王座！", "异端必将覆灭！"}):set_priority(2)
E:add_audio("zealot", "ako_ja", "response_for_psyker_seen_killstreak_zealot_", loc_ako, "ja_loc_zealot_female_a__response_for_psyker_seen_killstreak_zealot_", 4, 5):add_subtext("狂信徒", {"这都是神皇的意志！", "我的信仰即是武器！", "为了黄金王座！", "异端必将覆灭！"}):set_priority(2)
E:add_audio("zealot", "ako_ja", "response_for_ogryn_seen_killstreak_zealot_", loc_ako, "ja_loc_zealot_female_a__response_for_ogryn_seen_killstreak_zealot_", 4, 5):add_subtext("狂信徒", {"这都是神皇的意志！", "我的信仰即是武器！", "为了黄金王座！", "异端必将覆灭！"}):set_priority(2)
E:add_audio("zealot", "ako_ja", "response_for_adamant_seen_killstreak_zealot_", loc_ako, "ja_loc_zealot_female_a__response_for_adamant_seen_killstreak_zealot_", 4, 5):add_subtext("狂信徒", {"这都是神皇的意志！", "我的信仰即是武器！", "为了黄金王座！", "异端必将覆灭！"}):set_priority(2)

E:add_audio("zealot", "ako_ja", "response_for_friendly_fire_from_zealot_", loc_ako, "ja_loc_zealot_female_a__response_for_friendly_fire_from_zealot_", 1):add_subtext("狂信徒", {"看着点，小心你的火力！"})
E:add_audio("zealot", "ako_ja", "response_for_friendly_fire_from_veteran_", loc_ako, "ja_loc_zealot_female_a__response_for_friendly_fire_from_veteran_", 1):add_subtext("狂信徒", {"看着点，小心你的火力！"})
E:add_audio("zealot", "ako_ja", "response_for_friendly_fire_from_psyker_", loc_ako, "ja_loc_zealot_female_a__response_for_friendly_fire_from_psyker_", 1):add_subtext("狂信徒", {"看着点，小心你的火力！"})
E:add_audio("zealot", "ako_ja", "response_for_friendly_fire_from_ogryn_", loc_ako, "ja_loc_zealot_female_a__response_for_friendly_fire_from_ogryn_", 1):add_subtext("狂信徒", {"看着点，小心你的火力！"})
E:add_audio("zealot", "ako_ja", "response_for_friendly_fire_from_adamant_", loc_ako, "ja_loc_zealot_female_a__response_for_friendly_fire_from_adamant_", 1):add_subtext("狂信徒", {"看着点，小心你的火力！"})

E:add_audio("zealot", "ako_ja", "friendly_fire_from_zealot_to_zealot_", loc_ako, "ja_loc_zealot_female_a__friendly_fire_from_zealot_to_zealot_", 1):add_subtext("狂信徒", {"抱歉，避开我的枪线！"})
E:add_audio("zealot", "ako_ja", "friendly_fire_from_veteran_to_zealot_", loc_ako, "ja_loc_zealot_female_a__friendly_fire_from_veteran_to_zealot_", 1):add_subtext("狂信徒", {"抱歉，避开我的枪线！"})
E:add_audio("zealot", "ako_ja", "friendly_fire_from_psyker_to_zealot_", loc_ako, "ja_loc_zealot_female_a__friendly_fire_from_psyker_to_zealot_", 1):add_subtext("狂信徒", {"抱歉，避开我的枪线！"})
E:add_audio("zealot", "ako_ja", "friendly_fire_from_ogryn_to_zealot_", loc_ako, "ja_loc_zealot_female_a__friendly_fire_from_ogryn_to_zealot_", 1):add_subtext("狂信徒", {"抱歉，避开我的枪线！"})
E:add_audio("zealot", "ako_ja", "friendly_fire_from_adamant_to_zealot_", loc_ako, "ja_loc_zealot_female_a__friendly_fire_from_adamant_to_zealot_", 1):add_subtext("狂信徒", {"抱歉，避开我的枪线！"})

E:add_audio("zealot", "ako_ja", "head_shot_", loc_ako, "ja_loc_zealot_female_a__head_shot_", 3):add_subtext("狂信徒", {"神皇之眼引导着我。", "爆头！", "一击毙命！"})

E:add_audio("zealot", "ako_ja", "response_for_psyker_disabled_by_enemy_", loc_ako, "ja_loc_zealot_female_a__response_for_psyker_disabled_by_enemy_", 3):add_subtext("狂信徒", {"有同胞被困住了！", "去救人！", "把那异端从他身上砍下来！"})
E:add_audio("zealot", "ako_ja", "response_for_zealot_disabled_by_enemy_", loc_ako, "ja_loc_zealot_female_a__response_for_zealot_disabled_by_enemy_", 3):add_subtext("狂信徒", {"有同胞被困住了！", "去救人！", "把那异端从他身上砍下来！"})
E:add_audio("zealot", "ako_ja", "response_for_veteran_disabled_by_enemy_", loc_ako, "ja_loc_zealot_female_a__response_for_veteran_disabled_by_enemy_", 3):add_subtext("狂信徒", {"有同胞被困住了！", "去救人！", "把那异端从他身上砍下来！"})
E:add_audio("zealot", "ako_ja", "response_for_ogryn_disabled_by_enemy_", loc_ako, "ja_loc_zealot_female_a__response_for_ogryn_disabled_by_enemy_", 3):add_subtext("狂信徒", {"有同胞被困住了！", "去救人！", "把那异端从他身上砍下来！"})

E:add_audio("zealot", "ako_ja", "zealot_start_revive_ogryn_", loc_ako, "ja_loc_zealot_female_a__zealot_start_revive_ogryn_", 3):add_subtext("狂信徒", {"站起来，你的赎罪还未结束！", "神皇不允许你倒下！", "坚持住，我拉你起来。"})
E:add_audio("zealot", "ako_ja", "zealot_start_revive_zealot_", loc_ako, "ja_loc_zealot_female_a__zealot_start_revive_zealot_", 3):add_subtext("狂信徒", {"站起来，你的赎罪还未结束！", "神皇不允许你倒下！", "坚持住，我拉你起来。"})
E:add_audio("zealot", "ako_ja", "zealot_start_revive_veteran_", loc_ako, "ja_loc_zealot_female_a__zealot_start_revive_veteran_", 3):add_subtext("狂信徒", {"站起来，你的赎罪还未结束！", "神皇不允许你倒下！", "坚持住，我拉你起来。"})
E:add_audio("zealot", "ako_ja", "zealot_start_revive_psyker_", loc_ako, "ja_loc_zealot_female_a__zealot_start_revive_psyker_", 3):add_subtext("狂信徒", {"站起来，你的赎罪还未结束！", "神皇不允许你倒下！", "坚持住，我拉你起来。"})

E:add_audio("zealot", "ako_ja", "combat_pause_one_liner_", loc_ako, "ja_loc_zealot_female_a__combat_pause_one_liner_", 2):add_subtext("狂信徒", {"短暂的安宁掩盖不了异端的恶臭。", "保持警惕，黑暗中潜伏着危险。"})
E:add_audio("zealot", "ako_ja", "surrounded_", loc_ako, "ja_loc_zealot_female_a__surrounded_", 3):add_subtext("狂信徒", {"我被包围了！", "异端太多了，但我无所畏惧！", "来吧，让我送你们下地狱！"})
E:add_audio("zealot", "ako_ja", "surrounded_response_", loc_ako, "ja_loc_zealot_female_a__surrounded_response_", 2):add_subtext("狂信徒", {"坚守阵地，我们来支援你！", "不要退缩，杀出一条血路！"})
E:add_audio("zealot", "ako_ja", "heard_horde_vector_", loc_ako, "ja_loc_zealot_female_a__heard_horde_vector_", 3):add_subtext("狂信徒", {"尸潮来袭！准备迎战！", "腐败的怪物涌过来了！", "结成防线，净化他们！"})
E:add_audio("zealot", "ako_ja", "heard_horde_ambush_", loc_ako, "ja_loc_zealot_female_a__heard_horde_ambush_", 3):add_subtext("狂信徒", {"这是伏击！", "异端从四面八方涌来！", "保持阵型！"})

E:add_audio("zealot", "ako_ja", "heard_enemy_beast_of_nurgle_", loc_ako, "ja_loc_zealot_female_a__heard_enemy_beast_of_nurgle_", 4):add_subtext("狂信徒", {"那令人作呕的声音！有巨兽靠近！", "纳垢的邪物在附近！", "准备迎接巨型恶魔！", "巨大的异端逼近了！"})
E:add_audio("zealot", "ako_ja", "heard_enemy_chaos_spawn_", loc_ako, "ja_loc_zealot_female_a__heard_enemy_chaos_spawn_", 4):add_subtext("狂信徒", {"混沌的憎物在逼近！", "听到那扭曲的嚎叫了吗！", "有怪物正在靠近！", "准备迎击巨兽！"})
E:add_audio("zealot", "ako_ja", "heard_enemy_plague_ogryn_", loc_ako, "ja_loc_zealot_female_a__heard_enemy_plague_ogryn_", 4):add_subtext("狂信徒", {"那沉重的脚步声...是瘟疫欧格林！", "被腐化的巨兽在附近！", "当心，巨兽要来了！", "有大家伙在靠近！"})

E:add_audio("zealot", "ako_ja", "conversation_plague_ogryn_weakpoint_01_", loc_ako, "ja_loc_zealot_female_a__conversation_plague_ogryn_weakpoint_01_", 3):add_subtext("狂信徒", {"攻击它的头部！", "打爆它的脑袋！", "集火它的弱点！"})
E:add_audio("zealot", "ako_ja", "conversation_beast_of_nurgle_weakpoint_a_", loc_ako, "ja_loc_zealot_female_a__conversation_beast_of_nurgle_weakpoint_a_", 3):add_subtext("狂信徒", {"攻击它背上的脓包！", "打它的背部弱点！", "瞄准发光的地方打！"})
E:add_audio("zealot", "ako_ja", "conversation_beast_of_nurgle_weakpoint_c_", loc_ako, "ja_loc_zealot_female_a__conversation_beast_of_nurgle_weakpoint_c_", 3):add_subtext("狂信徒", {"攻击它背上的脓包！", "打它的背部弱点！", "瞄准发光的地方打！"})

E:add_audio("zealot", "ako_ja", "seen_enemy_plague_ogryn_", loc_ako, "ja_loc_zealot_female_a__seen_enemy_plague_ogryn_", 3):add_subtext("狂信徒", {"巨兽现身了！", "瘟疫欧格林来了！", "准备迎战庞然大物！"})
E:add_audio("zealot", "ako_ja", "seen_enemy_beast_of_nurgle_", loc_ako, "ja_loc_zealot_female_a__seen_enemy_beast_of_nurgle_", 3):add_subtext("狂信徒", {"纳垢野兽出现了！", "恶心的巨物来袭！", "准备净化这头巨兽！"})
E:add_audio("zealot", "ako_ja", "seen_enemy_chaos_spawn_", loc_ako, "ja_loc_zealot_female_a__seen_enemy_chaos_spawn_", 3):add_subtext("狂信徒", {"混沌卵现身！", "丑陋的变异体来了！", "消灭这个畸变体！"})

E:add_audio("zealot", "ako_ja", "smart_tag_vo_enemy_chaos_spawn_a_", loc_ako, "ja_loc_zealot_female_a__smart_tag_vo_enemy_chaos_spawn_a_", 3):add_subtext("狂信徒", {"混沌卵！", "恶心的血肉造物！", "净化它！"})
E:add_audio("zealot", "ako_ja", "smart_tag_vo_enemy_chaos_spawn_b_", loc_ako, "ja_loc_zealot_female_a__smart_tag_vo_enemy_chaos_spawn_b_", 3):add_subtext("狂信徒", {"混沌卵！", "恶心的血肉造物！", "净化它！"})
E:add_audio("zealot", "ako_ja", "smart_tag_vo_enemy_beast_of_nurgle_", loc_ako, "ja_loc_zealot_female_a__smart_tag_vo_enemy_beast_of_nurgle_", 3):add_subtext("狂信徒", {"纳垢野兽！", "庞大的腐化怪物！", "杀光这头巨兽！"})
E:add_audio("zealot", "ako_ja", "smart_tag_vo_enemy_plague_ogryn_", loc_ako, "ja_loc_zealot_female_a__smart_tag_vo_enemy_plague_ogryn_", 3):add_subtext("狂信徒", {"瘟疫欧格林！", "被腐化的巨兽！", "准备迎击！"})

E:add_audio("zealot", "ako_ja", "heard_enemy_daemonhost_", loc_ako, "ja_loc_zealot_female_a__heard_enemy_daemonhost_", 3):add_subtext("狂信徒", {"有恶魔在低语！关闭灯光！", "附近有恶魔宿主，保持安静。", "我感受到了极端的亵渎，有恶魔在此。"})
E:add_audio("zealot", "ako_ja", "seen_enemy_daemonhost_", loc_ako, "ja_loc_zealot_female_a__seen_enemy_daemonhost_", 3):add_subtext("狂信徒", {"恶魔宿主在沉睡，绕开她！", "不要惊动那个恶魔！", "发现恶魔宿主，小心行事。"})
E:add_audio("zealot", "ako_ja", "alerted_ememy_daemonhost_", loc_ako, "ja_loc_zealot_female_a__alerted_ememy_daemonhost_", 2):add_subtext("狂信徒", {"恶魔苏醒了！准备战斗！", "异端恶魔被激怒了！"})
E:add_audio("zealot", "ako_ja", "smart_tag_vo_enemy_daemonhost_", loc_ako, "ja_loc_zealot_female_a__smart_tag_vo_enemy_daemonhost_", 2):add_subtext("狂信徒", {"恶魔宿主！", "深渊的恶魔！"})

E:add_audio("zealot", "ako_ja", "monster_fight_start_reaction_", loc_ako, "ja_loc_zealot_female_a__monster_fight_start_reaction_", 4, 5):add_subtext("狂信徒", {"为了神皇，砍碎它！", "巨兽战准备！", "净化这肮脏的异形！", "死斗到底！"}):set_priority(2)
E:add_audio("zealot", "ako_ja", "enemy_near_death_monster_", loc_ako, "ja_loc_zealot_female_a__enemy_near_death_monster_", 3, 5):add_subtext("狂信徒", {"它快倒下了，给它最后一击！", "异形奄奄一息了！", "彻底净化它！"}):set_priority(2)
E:add_audio("zealot", "ako_ja", "enemy_kill_monster_", loc_ako, "ja_loc_zealot_female_a__enemy_kill_monster_", 3, 5):add_subtext("狂信徒", {"巨兽已被彻底净化！", "恶魔已被驱逐！", "神皇的意志不可战胜！"}):set_priority(2)

E:add_audio("zealot", "ako_ja", "mission_cargo_something_big_", loc_ako, "ja_loc_zealot_female_a__mission_cargo_something_big_", 2):add_subtext("狂信徒", {"巨大的震动，有东西要来了。", "地面在颤抖，准备迎战。"})

E:add_audio("zealot", "ako_ja", "heard_enemy_chaos_hound_", loc_ako, "ja_loc_zealot_female_a__heard_enemy_chaos_hound_", 3):add_subtext("狂信徒", {"听到了猎犬的嚎叫！", "瘟疫猎犬在附近！", "注意周围，有猎犬。"})
E:add_audio("zealot", "ako_ja", "seen_enemy_chaos_hound_", loc_ako, "ja_loc_zealot_female_a__seen_enemy_chaos_hound_", 3):add_subtext("狂信徒", {"异端猎犬来了！", "打死那只狗！", "瘟疫猎犬冲过来了！"})
E:add_audio("zealot", "ako_ja", "smart_tag_vo_enemy_chaos_hound_", loc_ako, "ja_loc_zealot_female_a__smart_tag_vo_enemy_chaos_hound_", 3):add_subtext("狂信徒", {"瘟疫猎犬！", "异端的走狗！", "杀掉那只野兽！"})
E:add_audio("zealot", "ako_ja", "enemy_kill_chaos_hound_", loc_ako, "ja_loc_zealot_female_a__enemy_kill_chaos_hound_", 3):add_subtext("狂信徒", {"猎犬已被净化！", "肮脏的畜生死了。", "死狗一条。"})

E:add_audio("zealot", "ako_ja", "seen_netgunner_", loc_ako, "ja_loc_zealot_female_a__seen_netgunner_", 3):add_subtext("狂信徒", {"当心陷阱捕手！", "发现网兵！", "躲开他的网！"})
E:add_audio("zealot", "ako_ja", "seen_netgunner_flee_", loc_ako, "ja_loc_zealot_female_a__seen_netgunner_flee_", 2):add_subtext("狂信徒", {"陷阱捕手跑了！", "别让异端逃走！"})
E:add_audio("zealot", "ako_ja", "smart_tag_vo_enemy_netgunner_", loc_ako, "ja_loc_zealot_female_a__smart_tag_vo_enemy_netgunner_", 3):add_subtext("狂信徒", {"陷阱手！", "阴险的网兵！", "杀掉他！"})
E:add_audio("zealot", "ako_ja", "enemy_kill_netgunner_", loc_ako, "ja_loc_zealot_female_a__enemy_kill_netgunner_", 3):add_subtext("狂信徒", {"陷阱手已死。", "卑鄙的异端已被净化。", "捕网兵被消灭。"})

E:add_audio("zealot", "ako_ja", "seen_enemy_mutant_charger_", loc_ako, "ja_loc_zealot_female_a__seen_enemy_mutant_charger_", 3):add_subtext("狂信徒", {"变种人冲过来了！", "躲开变种人！", "变异的怪物！"})
E:add_audio("zealot", "ako_ja", "smart_tag_vo_enemy_chaos_mutant_charger_", loc_ako, "ja_loc_zealot_female_a__smart_tag_vo_enemy_chaos_mutant_charger_", 3):add_subtext("狂信徒", {"变种人冲锋者！", "变种人！", "集火那个变种人！"})
E:add_audio("zealot", "ako_ja", "enemy_kill_mutant_charger_", loc_ako, "ja_loc_zealot_female_a__enemy_kill_mutant_charger_", 3):add_subtext("狂信徒", {"变种人倒下了！", "异形已被净化！", "怪物死了！"})

E:add_audio("zealot", "ako_ja", "heard_enemy_poxwalker_bomber_", loc_ako, "ja_loc_zealot_female_a__heard_enemy_poxwalker_bomber_", 3):add_subtext("狂信徒", {"听到炸弹的声音了！", "自爆兵靠近了！", "当心炸弹人！"})
E:add_audio("zealot", "ako_ja", "seen_enemy_poxwalker_bomber_", loc_ako, "ja_loc_zealot_female_a__seen_enemy_poxwalker_bomber_", 3):add_subtext("狂信徒", {"炸弹人出现了！", "远离那个自爆兵！", "那是炸弹人！"})
E:add_audio("zealot", "ako_ja", "smart_tag_vo_enemy_chaos_poxwalker_bomber_", loc_ako, "ja_loc_zealot_female_a__smart_tag_vo_enemy_chaos_poxwalker_bomber_", 3):add_subtext("狂信徒", {"炸弹人！", "自爆狂徒！", "打爆他！"})
E:add_audio("zealot", "ako_ja", "enemy_kill_poxwalker_bomber_", loc_ako, "ja_loc_zealot_female_a__enemy_kill_poxwalker_bomber_", 3):add_subtext("狂信徒", {"异端炸弹人已清除。", "让他和他的炸弹一起下地狱吧。", "自爆兵死了！"})

E:add_audio("zealot", "ako_ja", "smart_tag_vo_enemy_scab_flamer_a_", loc_ako, "ja_loc_zealot_female_a__smart_tag_vo_enemy_scab_flamer_a_", 3):add_subtext("狂信徒", {"喷火兵！", "躲开异端的火焰！", "纵火犯在此！"})
E:add_audio("zealot", "ako_ja", "smart_tag_vo_tox_flamer_", loc_ako, "ja_loc_zealot_female_a__smart_tag_vo_tox_flamer_", 3):add_subtext("狂信徒", {"毒火兵！", "当心绿色毒焰！", "恶毒的喷火兵！"})
E:add_audio("zealot", "ako_ja", "seen_enemy_tox_flamer_", loc_ako, "ja_loc_zealot_female_a__seen_enemy_tox_flamer_", 3):add_subtext("狂信徒", {"毒火兵来了，躲开！", "发现喷火兵！", "纵火异端！"})
E:add_audio("zealot", "ako_ja", "seen_enemy_scab_flamer_a_", loc_ako, "ja_loc_zealot_female_a__seen_enemy_scab_flamer_a_", 3):add_subtext("狂信徒", {"喷火兵来了，躲开！", "发现喷火兵！", "纵火异端！"})
E:add_audio("zealot", "ako_ja", "enemy_kill_tox_flamer_", loc_ako, "ja_loc_zealot_female_a__enemy_kill_tox_flamer_", 3):add_subtext("狂信徒", {"玩火自焚的异端！", "异端毒焰已熄灭。", "喷火兵死了。"})
E:add_audio("zealot", "ako_ja", "enemy_kill_scab_flamer_a_", loc_ako, "ja_loc_zealot_female_a__enemy_kill_scab_flamer_a_", 3):add_subtext("狂信徒", {"玩火自焚的异端！", "异端火焰已熄灭。", "喷火兵死了。"})

E:add_audio("zealot", "ako_ja", "seen_enemy_traitor_grenadier_", loc_ako, "ja_loc_zealot_female_a__seen_enemy_traitor_grenadier_", 3):add_subtext("狂信徒", {"掷弹兵出现了！", "当心手雷！", "发现掷弹手！"})
E:add_audio("zealot", "ako_ja", "smart_tag_vo_enemy_traitor_grenadier_", loc_ako, "ja_loc_zealot_female_a__smart_tag_vo_enemy_traitor_grenadier_", 3):add_subtext("狂信徒", {"掷弹兵！", "手雷兵！", "消灭那个投掷手！"})
E:add_audio("zealot", "ako_ja", "enemy_kill_traitor_grenadier_", loc_ako, "ja_loc_zealot_female_a__enemy_kill_traitor_grenadier_", 3):add_subtext("狂信徒", {"异端投弹手已死。", "净化完成。", "威胁解除。"})
E:add_audio("zealot", "ako_ja", "seen_enemy_cultist_grenadier_", loc_ako, "ja_loc_zealot_female_a__seen_enemy_cultist_grenadier_", 3):add_subtext("狂信徒", {"毒气兵出现了！", "当心毒气！", "发现毒气投掷手！"})
E:add_audio("zealot", "ako_ja", "smart_tag_vo_enemy_cultist_grenadier_", loc_ako, "ja_loc_zealot_female_a__smart_tag_vo_enemy_cultist_grenadier_", 3):add_subtext("狂信徒", {"毒气兵！", "毒气手雷！", "消灭毒气兵！"})
E:add_audio("zealot", "ako_ja", "enemy_kill_grenadier_", loc_ako, "ja_loc_zealot_female_a__enemy_kill_grenadier_", 3):add_subtext("狂信徒", {"异端投弹手已死。", "净化完成。", "威胁解除。"})

E:add_audio("zealot", "ako_ja", "smart_tag_vo_enemy_traitor_sniper_", loc_ako, "ja_loc_zealot_female_a__smart_tag_vo_enemy_traitor_sniper_", 3):add_subtext("狂信徒", {"狙击手！", "注意激光红线！", "找掩体，有狙击手！"})
E:add_audio("zealot", "ako_ja", "seen_enemy_sniper_", loc_ako, "ja_loc_zealot_female_a__seen_enemy_sniper_", 3):add_subtext("狂信徒", {"发现狙击手！", "暗处有狙击手！", "狙击手在盯着我们！"})
E:add_audio("zealot", "ako_ja", "enemy_kill_sniper_a_", loc_ako, "ja_loc_zealot_female_a__enemy_kill_sniper_a_", 3):add_subtext("狂信徒", {"卑劣的懦夫已死。", "狙击手被正法。", "暗箭伤人的下场。"})

E:add_audio("zealot", "ako_ja", "seen_enemy_traitor_gunner_", loc_ako, "ja_loc_zealot_female_a__seen_enemy_traitor_gunner_", 3):add_subtext("狂信徒", {"机枪手现身！", "找掩护，有机枪火力！", "机枪手在那！"})
E:add_audio("zealot", "ako_ja", "smart_tag_vo_enemy_traitor_gunner_", loc_ako, "ja_loc_zealot_female_a__smart_tag_vo_enemy_traitor_gunner_", 3):add_subtext("狂信徒", {"机枪手！", "炮手！", "干掉机枪手！"})
E:add_audio("zealot", "ako_ja", "seen_enemy_cultist_holy_stubber_gunner_", loc_ako, "ja_loc_zealot_female_a__seen_enemy_cultist_holy_stubber_gunner_", 3):add_subtext("狂信徒", {"重火力机枪手！", "找掩护！", "机枪手在那！"})
E:add_audio("zealot", "ako_ja", "smart_tag_vo_enemy_cultist_holy_stubber_gunner_", loc_ako, "ja_loc_zealot_female_a__smart_tag_vo_enemy_cultist_holy_stubber_gunner_", 3):add_subtext("狂信徒", {"机枪手！", "炮手！", "干掉机枪手！"})
E:add_audio("zealot", "ako_ja", "seen_enemy_heavy_gunner_", loc_ako, "ja_loc_zealot_female_a__seen_enemy_heavy_gunner_", 3):add_subtext("狂信徒", {"重机枪现身！", "重机枪压制！", "机枪手在那！"})
E:add_audio("zealot", "ako_ja", "smart_tag_vo_enemy_heavy_gunner_", loc_ako, "ja_loc_zealot_female_a__smart_tag_vo_enemy_heavy_gunner_", 3):add_subtext("狂信徒", {"重炮手！", "重型机枪！", "消灭重机枪！"})

E:add_audio("zealot", "ako_ja", "seen_enemy_shocktrooper_", loc_ako, "ja_loc_zealot_female_a__seen_enemy_shocktrooper_", 3):add_subtext("狂信徒", {"霰弹枪手靠近了！", "当心近战火力！", "散弹兵！"})
E:add_audio("zealot", "ako_ja", "smart_tag_vo_enemy_traitor_scout_shocktrooper_", loc_ako, "ja_loc_zealot_female_a__smart_tag_vo_enemy_traitor_scout_shocktrooper_", 3):add_subtext("狂信徒", {"霰弹枪手！", "散弹兵！", "突击兵！"})
E:add_audio("zealot", "ako_ja", "seen_enemy_cultist_shocktrooper_", loc_ako, "ja_loc_zealot_female_a__seen_enemy_cultist_shocktrooper_", 3):add_subtext("狂信徒", {"霰弹枪手靠近了！", "当心近战火力！", "散弹兵！"})
E:add_audio("zealot", "ako_ja", "smart_tag_vo_enemy_cultist_shocktrooper_", loc_ako, "ja_loc_zealot_female_a__smart_tag_vo_enemy_cultist_shocktrooper_", 3):add_subtext("狂信徒", {"霰弹枪手！", "散弹兵！", "突击兵！"})

E:add_audio("zealot", "ako_ja", "seen_enemy_executor_", loc_ako, "ja_loc_zealot_female_a__seen_enemy_executor_", 3):add_subtext("狂信徒", {"重型近战兵来了！", "重锤兵现身！", "链锯兵来袭！"})
E:add_audio("zealot", "ako_ja", "smart_tag_vo_enemy_traitor_executor_", loc_ako, "ja_loc_zealot_female_a__smart_tag_vo_enemy_traitor_executor_", 3):add_subtext("狂信徒", {"重锤兵！", "链锯异端！", "粉碎他！"})

E:add_audio("zealot", "ako_ja", "smart_tag_vo_enemy_chaos_ogryn_bulwark_", loc_ako, "ja_loc_zealot_female_a__smart_tag_vo_enemy_chaos_ogryn_bulwark_", 3):add_subtext("狂信徒", {"盾卫欧格林！", "绕开他的盾牌！", "重甲盾兵！"})
E:add_audio("zealot", "ako_ja", "seen_enemy_bulwark_", loc_ako, "ja_loc_zealot_female_a__seen_enemy_bulwark_", 3):add_subtext("狂信徒", {"盾卫来了！", "巨型盾牌兵！", "打他的侧翼！"})

E:add_audio("zealot", "ako_ja", "seen_enemy_chaos_ogryn_armored_executor_", loc_ako, "ja_loc_zealot_female_a__seen_enemy_chaos_ogryn_armored_executor_", 3):add_subtext("狂信徒", {"重甲粉碎者出现了！", "粉碎者来袭！", "当心重锤巨汉！"})
E:add_audio("zealot", "ako_ja", "smart_tag_vo_enemy_chaos_ogryn_armored_executor_", loc_ako, "ja_loc_zealot_female_a__smart_tag_vo_enemy_chaos_ogryn_armored_executor_", 3):add_subtext("狂信徒", {"粉碎者！", "重装巨汉！", "破甲手！"})

E:add_audio("zealot", "ako_ja", "seen_enemy_chaos_ogryn_heavy_gunner_", loc_ako, "ja_loc_zealot_female_a__seen_enemy_chaos_ogryn_heavy_gunner_", 3):add_subtext("狂信徒", {"收割者重机枪！", "当心欧格林机枪！", "发现收割者！"})
E:add_audio("zealot", "ako_ja", "smart_tag_vo_enemy_chaos_ogryn_heavy_gunner_", loc_ako, "ja_loc_zealot_female_a__smart_tag_vo_enemy_chaos_ogryn_heavy_gunner_", 3):add_subtext("狂信徒", {"收割者！", "巨型枪手！", "干掉那挺重机枪！"})

E:add_audio("zealot", "ako_ja", "seen_enemy_berserker_", loc_ako, "ja_loc_zealot_female_a__seen_enemy_berserker_", 3):add_subtext("狂信徒", {"狂战士冲过来了！", "失去理智的异端！", "准备近战，狂暴者来了！"})
E:add_audio("zealot", "ako_ja", "smart_tag_vo_enemy_berserker_", loc_ako, "ja_loc_zealot_female_a__smart_tag_vo_enemy_berserker_", 3):add_subtext("狂信徒", {"狂战士！", "狂暴者！", "杀掉疯子！"})
E:add_audio("zealot", "ako_ja", "enemy_kill_berserker_", loc_ako, "ja_loc_zealot_female_a__enemy_kill_berserker_", 3):add_subtext("狂信徒", {"狂暴者得到了安息！", "疯狂的异端已死。", "狂战士被净化。"})
E:add_audio("zealot", "ako_ja", "enemy_kill_berserker_ext_03_c_", loc_ako, "ja_loc_zealot_female_a__enemy_kill_berserker_ext_03_c_", 3):add_subtext("狂信徒", {"狂暴者得到了安息！", "疯狂的异端已死。", "狂战士被净化。"})

E:add_audio("zealot", "ako_ja", "seen_enemy_group_far_range_shooting_behind_cover_", loc_ako, "ja_loc_zealot_female_a__seen_enemy_group_far_range_shooting_behind_cover_", 2):add_subtext("狂信徒", {"异端躲在掩体后射击！", "把他们从掩体里逼出来！"})
E:add_audio("zealot", "ako_ja", "seen_enemy_group_assaulting_", loc_ako, "ja_loc_zealot_female_a__seen_enemy_group_assaulting_", 3):add_subtext("狂信徒", {"他们冲过来了！", "准备白刃战！", "用你们的鲜血赎罪吧！"})
E:add_audio("zealot", "ako_ja", "quick_agnostic_enemy_kill_a_", loc_ako, "ja_loc_zealot_female_a__quick_agnostic_enemy_kill_a_", 5, 4):add_subtext("狂信徒", {"异端已死！", "神皇的制裁！", "化为灰烬！", "绝不留情！", "这就是亵渎者的下场！"}):set_priority(2)

E:add_audio("zealot", "ako_ja", "player_tip_armor_hit_generic_", loc_ako, "ja_loc_zealot_female_a__player_tip_armor_hit_generic_", 3):add_subtext("狂信徒", {"护甲太厚了！", "我们需要破甲武器！", "不要攻击硬壳！"})

E:add_audio("zealot", "ako_ja", "event_kill_tareget_damaged_", loc_ako, "ja_loc_zealot_female_a__event_kill_tareget_damaged_", 2):add_subtext("狂信徒", {"目标受损！", "攻击见效了！"})
E:add_audio("zealot", "ako_ja", "event_kill_target_heavy_damage_a_", loc_ako, "ja_loc_zealot_female_a__event_kill_target_heavy_damage_a_", 2):add_subtext("狂信徒", {"目标重创！", "它撑不了多久了！"})
E:add_audio("zealot", "ako_ja", "event_kill_target_destroyed_a_", loc_ako, "ja_loc_zealot_female_a__event_kill_target_destroyed_a_", 3):add_subtext("狂信徒", {"目标已被完全净化。", "神皇的意志得以执行。", "摧毁完成。"})

E:add_audio("zealot", "ako_ja", "guidance_switch_", loc_ako, "ja_loc_zealot_female_a__guidance_switch_", 2):add_subtext("狂信徒", {"这有一个开关。", "去拉下开关。"})
E:add_audio("zealot", "ako_ja", "luggable_mission_pick_up_", loc_ako, "ja_loc_zealot_female_a__luggable_mission_pick_up_", 2):add_subtext("狂信徒", {"我拿到了任务物品。", "掩护我搬运货物。"})
E:add_audio("zealot", "ako_ja", "throwing_grenade_", loc_ako, "ja_loc_zealot_female_a__throwing_grenade_", 3):add_subtext("狂信徒", {"感受火焰吧！", "手雷投掷！", "沐浴在圣火中！"})

E:add_audio("zealot", "ako_ja", "critical_health_", loc_ako, "ja_loc_zealot_female_a__critical_health_", 4, 6):add_subtext("狂信徒", {"我的肉体正在崩坏...", "流血过多...", "信仰不可磨灭...", "还需要战斗..."}):set_priority(1)

E:add_audio("zealot", "ako_ja", "smart_tag_stimm_power_a_", loc_ako, "ja_loc_zealot_female_a__smart_tag_stimm_power_a_", 2):add_subtext("狂信徒", {"红色兴奋剂，赐予我们力量！", "力量药剂！"})
E:add_audio("zealot", "ako_ja", "smart_tag_stimm_speed_a_", loc_ako, "ja_loc_zealot_female_a__smart_tag_stimm_speed_a_", 2):add_subtext("狂信徒", {"蓝色兴奋剂，加快速度！", "敏捷药剂！"})
E:add_audio("zealot", "ako_ja", "smart_tag_stimm_concentration_a_", loc_ako, "ja_loc_zealot_female_a__smart_tag_stimm_concentration_a_", 2):add_subtext("狂信徒", {"黄色兴奋剂，集中精神！", "专注药剂！"})
E:add_audio("zealot", "ako_ja", "smart_tag_vo_small_grenade_", loc_ako, "ja_loc_zealot_female_a__smart_tag_vo_small_grenade_", 2):add_subtext("狂信徒", {"有手雷补给。", "补充爆破物。"})

E:add_audio("zealot", "ako_ja", "calling_for_help_", loc_ako, "ja_loc_zealot_female_a__calling_for_help_", 3):add_subtext("狂信徒", {"我需要援助！", "来人拉我一把！", "神皇啊，请赐予我力量站起来！"})
E:add_audio("zealot", "ako_ja", "response_for_calling_for_help_", loc_ako, "ja_loc_zealot_female_a__response_for_calling_for_help_", 3):add_subtext("狂信徒", {"坚持住，信徒！", "我来救你！", "神皇不允许你死在这里！"})

E:add_audio("zealot", "ako_ja", "response_for_zealot_critical_health_", loc_ako, "ja_loc_zealot_female_a__response_for_zealot_critical_health_", 2):add_subtext("狂信徒", {"快去治疗，不要在这里倒下！", "你需要医疗包。"})
E:add_audio("zealot", "ako_ja", "response_for_veteran_critical_health_", loc_ako, "ja_loc_zealot_female_a__response_for_veteran_critical_health_", 2):add_subtext("狂信徒", {"快去治疗，不要在这里倒下！", "你需要医疗包。"})
E:add_audio("zealot", "ako_ja", "response_for_psyker_critical_health_", loc_ako, "ja_loc_zealot_female_a__response_for_psyker_critical_health_", 2):add_subtext("狂信徒", {"快去治疗，不要在这里倒下！", "你需要医疗包。"})
E:add_audio("zealot", "ako_ja", "response_for_ogryn_critical_health_", loc_ako, "ja_loc_zealot_female_a__response_for_ogryn_critical_health_", 2):add_subtext("狂信徒", {"快去治疗，不要在这里倒下！", "你需要医疗包。"})
E:add_audio("zealot", "ako_ja", "response_for_adamant_critical_health_", loc_ako, "ja_loc_zealot_female_a__response_for_adamant_critical_health_", 2):add_subtext("狂信徒", {"快去治疗，不要在这里倒下！", "你需要医疗包。"})

E:add_audio("zealot", "ako_ja", "knocked_down_multiple_times_zealot_", loc_ako, "ja_loc_zealot_female_a__knocked_down_multiple_times_zealot_", 3):add_subtext("狂信徒", {"站起来，赎罪还未结束！", "不要一再跌倒！", "稳住你的阵脚！"})
E:add_audio("zealot", "ako_ja", "knocked_down_multiple_times_veteran_", loc_ako, "ja_loc_zealot_female_a__knocked_down_multiple_times_veteran_", 3):add_subtext("狂信徒", {"站起来，赎罪还未结束！", "不要一再跌倒！", "稳住你的阵脚！"})
E:add_audio("zealot", "ako_ja", "knocked_down_multiple_times_psyker_", loc_ako, "ja_loc_zealot_female_a__knocked_down_multiple_times_psyker_", 3):add_subtext("狂信徒", {"站起来，赎罪还未结束！", "不要一再跌倒！", "稳住你的阵脚！"})
E:add_audio("zealot", "ako_ja", "knocked_down_multiple_times_ogryn_", loc_ako, "ja_loc_zealot_female_a__knocked_down_multiple_times_ogryn_", 3):add_subtext("狂信徒", {"站起来，赎罪还未结束！", "不要一再跌倒！", "稳住你的阵脚！"})
E:add_audio("zealot", "ako_ja", "knocked_down_multiple_times_adamant_", loc_ako, "ja_loc_zealot_female_a__knocked_down_multiple_times_adamant_", 3):add_subtext("狂信徒", {"站起来，赎罪还未结束！", "不要一再跌倒！", "稳住你的阵脚！"})

E:add_audio("zealot", "ako_ja", "player_death_zealot_", loc_ako, "ja_loc_zealot_female_a__player_death_zealot_", 1):add_subtext("狂信徒", {"一位同胞回归了黄金王座！"})
E:add_audio("zealot", "ako_ja", "player_death_veteran_", loc_ako, "ja_loc_zealot_female_a__player_death_veteran_", 1):add_subtext("狂信徒", {"一位同胞回归了黄金王座！"})
E:add_audio("zealot", "ako_ja", "player_death_psyker_", loc_ako, "ja_loc_zealot_female_a__player_death_psyker_", 1):add_subtext("狂信徒", {"一位同胞回归了黄金王座！"})
E:add_audio("zealot", "ako_ja", "player_death_ogryn_", loc_ako, "ja_loc_zealot_female_a__player_death_ogryn_", 1):add_subtext("狂信徒", {"一位同胞回归了黄金王座！"})
E:add_audio("zealot", "ako_ja", "player_death_adamant_", loc_ako, "ja_loc_zealot_female_a__player_death_adamant_", 1):add_subtext("狂信徒", {"一位同胞回归了黄金王座！"})

E:add_audio("zealot", "ako_ja", "pinned_by_enemies_", loc_ako, "ja_loc_zealot_female_a__pinned_by_enemies_", 3):add_subtext("狂信徒", {"被火力压制了！", "异端的火力太猛，寻找掩体！", "无法反击，被压制了！"})
E:add_audio("zealot", "ako_ja", "response_for_pinned_by_enemies_zealot_", loc_ako, "ja_loc_zealot_female_a__response_for_pinned_by_enemies_zealot_", 3):add_subtext("狂信徒", {"提供掩护射击！", "扔手雷清场！", "顶住火力反击！"})
E:add_audio("zealot", "ako_ja", "response_for_pinned_by_enemies_veteran_", loc_ako, "ja_loc_zealot_female_a__response_for_pinned_by_enemies_veteran_", 3):add_subtext("狂信徒", {"提供掩护射击！", "扔手雷清场！", "顶住火力反击！"})
E:add_audio("zealot", "ako_ja", "response_for_pinned_by_enemies_psyker_", loc_ako, "ja_loc_zealot_female_a__response_for_pinned_by_enemies_psyker_", 3):add_subtext("狂信徒", {"提供掩护射击！", "扔手雷清场！", "顶住火力反击！"})
E:add_audio("zealot", "ako_ja", "response_for_pinned_by_enemies_ogryn_", loc_ako, "ja_loc_zealot_female_a__response_for_pinned_by_enemies_ogryn_", 3):add_subtext("狂信徒", {"提供掩护射击！", "扔手雷清场！", "顶住火力反击！"})

E:add_audio("zealot", "ako_ja", "response_for_zealot_cover_me_", loc_ako, "ja_loc_zealot_female_a__response_for_zealot_cover_me_", 3):add_subtext("狂信徒", {"交给我来掩护！", "你的背后是安全的！", "冲锋吧，我来压制他们！"})
E:add_audio("zealot", "ako_ja", "response_for_veteran_cover_me_", loc_ako, "ja_loc_zealot_female_a__response_for_veteran_cover_me_", 3):add_subtext("狂信徒", {"交给我来掩护！", "你的背后是安全的！", "冲锋吧，我来压制他们！"})
E:add_audio("zealot", "ako_ja", "response_for_psyker_cover_me_", loc_ako, "ja_loc_zealot_female_a__response_for_psyker_cover_me_", 3):add_subtext("狂信徒", {"交给我来掩护！", "你的背后是安全的！", "冲锋吧，我来压制他们！"})
E:add_audio("zealot", "ako_ja", "response_for_ogryn_cover_me_", loc_ako, "ja_loc_zealot_female_a__response_for_ogryn_cover_me_", 3):add_subtext("狂信徒", {"交给我来掩护！", "你的背后是安全的！", "冲锋吧，我来压制他们！"})

E:add_audio("zealot", "ako_ja", "conversation_combat_chaos_spawn_chew_a_", loc_ako, "ja_loc_zealot_female_a__conversation_combat_chaos_spawn_chew_a_", 3):add_subtext("狂信徒", {"怪物在啃咬队友！", "去救下同胞！", "杀掉那头野兽！"})
E:add_audio("zealot", "ako_ja", "conversation_combat_chaos_spawn_chew_b_", loc_ako, "ja_loc_zealot_female_a__conversation_combat_chaos_spawn_chew_b_", 3):add_subtext("狂信徒", {"怪物在啃咬队友！", "去救下同胞！", "杀掉那头野兽！"})
E:add_audio("zealot", "ako_ja", "conversation_combat_chaos_spawn_chew_c_", loc_ako, "ja_loc_zealot_female_a__conversation_combat_chaos_spawn_chew_c_", 3):add_subtext("狂信徒", {"怪物在啃咬队友！", "去救下同胞！", "杀掉那头野兽！"})

E:add_audio("zealot", "ako_ja", "vce_hurt_heavy", play_ako, "play_zealot_female_a__vce_hurt_heavy", 3):set_priority(1)
E:add_audio("zealot", "ako_ja", "vce_catapulted", play_ako, "play_zealot_female_a__vce_catapulted", 2):set_priority(2)
E:add_audio("zealot", "ako_ja", "vce_catapulted_land", play_ako, "play_zealot_female_a__vce_catapulted_land", 2):set_priority(4)
E:add_audio("zealot", "ako_ja", "vce_scream_long", play_ako, "play_zealot_female_a__vce_scream_long", 2):set_priority(2)
E:add_audio("zealot", "ako_ja", "vce_hurt_light", play_ako, "play_zealot_female_a__vce_hurt_light", 5):set_priority(4)
E:add_audio("zealot", "ako_ja", "vce_jump", play_ako, "play_zealot_female_a__vce_jump", 2):set_priority(4)
E:add_audio("zealot", "ako_ja", "vce_land_heavy", play_ako, "play_zealot_female_a__vce_land_heavy", 1):set_priority(4)
E:add_audio("zealot", "ako_ja", "vce_grunt_short", play_ako, "play_zealot_female_a__vce_grunt_short", 9):set_priority(4)
E:add_audio("zealot", "ako_ja", "vce_attack_short", play_ako, "play_zealot_female_a__vce_attack_short", 9):set_priority(4)
E:add_audio("zealot", "ako_ja", "vce_attack_long", play_ako, "play_zealot_female_a__vce_attack_long", 11):set_priority(4)
E:add_audio("zealot", "ako_ja", "vce_coughing", play_ako, "play_zealot_female_a__vce_coughing", 1):set_priority(4)
E:add_audio("zealot", "ako_ja", "vce_getting_up", play_ako, "play_zealot_female_a__vce_getting_up", 1):set_priority(4)
E:add_audio("zealot", "ako_ja", "vce_struggle_heavy", play_ako, "play_zealot_female_a__vce_struggle_heavy", 1):set_priority(4)
E:add_audio("zealot", "ako_ja", "play_hud_heal_2d", play_ako, "play_zealot_female_a__vce_healing", 1, nil, "play_hud_heal_2d")
E:add_audio("zealot", "ako_ja", "play_syringe_power_start", play_ako, "play_syringe_power_start", 1, nil, "play_syringe_power_start"):set_priority(0)
E:add_audio("zealot", "ako_ja", "play_syringe_ability_start", play_ako, "play_syringe_ability_start", 1, nil, "play_syringe_ability_start"):set_priority(0)
E:add_audio("zealot", "ako_ja", "play_syringe_speed_start", play_ako, "play_syringe_speed_start", 1, nil, "play_syringe_speed_start"):set_priority(0)
